[package]
name = "d3d12_integration_test"
version = "0.2.0"
authors = ["red75prime <red75prim@gmail.com>"]

[dependencies]
libc = "*"
lazy_static = "*"
log = "*"
env_logger = "*"
d3d12_safe = { version = "*", path = "lib/d3d12" }
rand = "0.3"

[dependencies.winapi]
git = "https://github.com/red75prime/winapi-rs/"
branch = "dx12"

[dependencies.dxgi-sys]
git = "https://github.com/red75prime/winapi-rs/"
branch = "dx12"

[dependencies.user32-sys]
git = "https://github.com/red75prime/winapi-rs/"
branch = "dx12"

[dependencies.kernel32-sys]
git = "https://github.com/red75prime/winapi-rs/"
branch = "dx12"

# [dependencies.d3d12_sys]
# git = "https://github.com/red75prime/winapi-rs/"
# branch = "dx12"

[dependencies.dxguid-sys]
git = "https://github.com/red75prime/winapi-rs/"
branch = "dx12"
