// This file is autogenerated

use utils::*;

use d3d11_safe::*;
pub trait TD3D11On12Device: TUnknown {
  //  Method CreateWrappedResource
  
  #[allow(non_snake_case)]
  fn create_wrapped_resource<T: TUnknown, T1: TUnknown+HasIID>(&self, resource12: &T, flags11: &D3D11_RESOURCE_FLAGS, in_state: D3D12_RESOURCE_STATES, out_state: D3D12_RESOURCE_STATES) -> HResult<T1> {
    let mut lv1: *mut IUnknown = ptr::null_mut();
    let _hr=unsafe { (*(self.iptr() as *mut ID3D11On12Device)).CreateWrappedResource(resource12.iptr() as *mut _ as *mut _ , flags11, in_state, out_state, T1::iid(), &mut lv1 as *mut *mut _ as *mut *mut c_void) };
    hr2ret(_hr,T1::new(lv1))
  }
  
  //  Method ReleaseWrappedResources
  
  #[allow(non_snake_case)]
  fn release_wrapped_resources<T: TD3D11Resource>(&self, resources: &[&T]) -> () {
    let mut lv1: Vec<*mut IUnknown> = resources.iter().map(|o|o.iptr()).collect();
    let _hr=unsafe { (*(self.iptr() as *mut ID3D11On12Device)).ReleaseWrappedResources(lv1.as_mut_ptr() as *mut *mut _ as *mut *mut _, resources.len() as UINT) };
    ()
  }
  
  //  Method AcquireWrappedResources
  
  #[allow(non_snake_case)]
  fn acquire_wrapped_resources<T: TD3D11Resource>(&self, resources: &[&T]) -> () {
    let mut lv1: Vec<*mut IUnknown> = resources.iter().map(|o|o.iptr()).collect();
    let _hr=unsafe { (*(self.iptr() as *mut ID3D11On12Device)).AcquireWrappedResources(lv1.as_mut_ptr() as *mut *mut _ as *mut *mut _, resources.len() as UINT) };
    ()
  }
  
  
}

impl TUnknown for D3D11On12Device {
  fn new(ptr: *mut IUnknown) -> Self {
    D3D11On12Device(ptr as *mut _)
  }
  fn iptr(&self) -> *mut IUnknown {
    self.0 as *mut _
  }
}
impl Drop for D3D11On12Device {
  fn drop(&mut self) { drop_unknown(self) }
}
impl Clone for D3D11On12Device {
  fn clone(&self) -> Self { clone_unknown(self) }
}
impl TD3D11On12Device for D3D11On12Device {}

pub struct D3D11On12Device(*mut ID3D11On12Device);

impl HasIID for D3D11On12Device {
  fn iid() -> REFGUID { &IID_ID3D11On12Device }
}

