// This file is autogenerated

use utils::*;


pub struct D3D10Blob(*mut ID3D10Blob);

impl HasIID for D3D10Blob {
  fn iid() -> REFGUID { &IID_ID3D10Blob }
  fn new(pp_vtbl : *mut IUnknown) -> Self { D3D10Blob(pp_vtbl as *mut _ as *mut ID3D10Blob) }
  fn iptr(&self) -> *mut IUnknown { self.0 as *mut _ as  *mut IUnknown}
}

impl Drop for D3D10Blob {
  fn drop(&mut self) {
    release_com_ptr(self)
  }
}

impl Clone for D3D10Blob {
  fn clone(&self) -> Self {
    clone_com_ptr(self)
  }
}

impl D3D10Blob {
  //  Method GetBufferPointer
  
  #[allow(non_snake_case)]
  pub fn get_buffer_pointer(&self) -> LPVOID {
  
    let _hr=unsafe { (*(self.0 as *mut ID3D10Blob)).GetBufferPointer() };
    _hr
  }
  
  //  Method GetBufferSize
  
  #[allow(non_snake_case)]
  pub fn get_buffer_size(&self) -> SIZE_T {
  
    let _hr=unsafe { (*(self.0 as *mut ID3D10Blob)).GetBufferSize() };
    _hr
  }
  
  
}

