module annotations_urlmon

open annotations

let urlmon=[
  ("IAuthenticateExVtbl",IAManual, "IAuthenticateVtbl", [
    ("AuthenticateEx",[
      ("This",AThis);
      ("phwnd",ANone);
      ("pszUsername",ANone);
      ("pszPassword",ANone);
      ("pauthinfo",ANone);
    ],MANone);
  ]);
  ("IAuthenticateVtbl",IAManual, "IUnknownVtbl", [
    ("Authenticate",[
      ("This",AThis);
      ("phwnd",ANone);
      ("pszUsername",ANone);
      ("pszPassword",ANone);
    ],MANone);
  ]);
  ("IBindCallbackRedirectVtbl",IAManual, "IUnknownVtbl", [
    ("Redirect",[
      ("This",AThis);
      ("lpcUrl",ANone);
      ("vbCancel",ANone);
    ],MANone);
  ]);
  ("IBindHostVtbl",IAManual, "IUnknownVtbl", [
    ("CreateMoniker",[
      ("This",AThis);
      ("szName",ANone);
      ("pBC",ANone);
      ("ppmk",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("MonikerBindToStorage",[
      ("This",AThis);
      ("pMk",ANone);
      ("pBC",ANone);
      ("pBSC",ANone);
      ("riid",ANone);
      ("ppvObj",ANone);
    ],MANone);
    ("MonikerBindToObject",[
      ("This",AThis);
      ("pMk",ANone);
      ("pBC",ANone);
      ("pBSC",ANone);
      ("riid",ANone);
      ("ppvObj",ANone);
    ],MANone);
  ]);
  ("IBindHttpSecurityVtbl",IAManual, "IUnknownVtbl", [
    ("GetIgnoreCertMask",[
      ("This",AThis);
      ("pdwIgnoreCertMask",ANone);
    ],MANone);
  ]);
  ("IBindProtocolVtbl",IAManual, "IUnknownVtbl", [
    ("CreateBinding",[
      ("This",AThis);
      ("szUrl",ANone);
      ("pbc",ANone);
      ("ppb",ANone);
    ],MANone);
  ]);
  ("IBindStatusCallbackExVtbl",IAManual, "IBindStatusCallbackVtbl", [
    ("GetBindInfoEx",[
      ("This",AThis);
      ("grfBINDF",ANone);
      ("pbindinfo",ANone);
      ("grfBINDF2",ANone);
      ("pdwReserved",ANone);
    ],MANone);
  ]);
  ("IBindStatusCallbackVtbl",IAManual, "IUnknownVtbl", [
    ("OnStartBinding",[
      ("This",AThis);
      ("dwReserved",ANone);
      ("pib",ANone);
    ],MANone);
    ("GetPriority",[
      ("This",AThis);
      ("pnPriority",ANone);
    ],MANone);
    ("OnLowResource",[
      ("This",AThis);
      ("reserved",ANone);
    ],MANone);
    ("OnProgress",[
      ("This",AThis);
      ("ulProgress",ANone);
      ("ulProgressMax",ANone);
      ("ulStatusCode",ANone);
      ("szStatusText",ANone);
    ],MANone);
    ("OnStopBinding",[
      ("This",AThis);
      ("hresult",ANone);
      ("szError",ANone);
    ],MANone);
    ("GetBindInfo",[
      ("This",AThis);
      ("grfBINDF",ANone);
      ("pbindinfo",ANone);
    ],MANone);
    ("OnDataAvailable",[
      ("This",AThis);
      ("grfBSCF",ANone);
      ("dwSize",ANone);
      ("pformatetc",ANone);
      ("pstgmed",ANone);
    ],MANone);
    ("OnObjectAvailable",[
      ("This",AThis);
      ("riid",ANone);
      ("punk",ANone);
    ],MANone);
  ]);
  ("IBindingVtbl",IAManual, "IUnknownVtbl", [
    ("Abort",[
      ("This",AThis);
    ],MANone);
    ("Suspend",[
      ("This",AThis);
    ],MANone);
    ("Resume",[
      ("This",AThis);
    ],MANone);
    ("SetPriority",[
      ("This",AThis);
      ("nPriority",ANone);
    ],MANone);
    ("GetPriority",[
      ("This",AThis);
      ("pnPriority",ANone);
    ],MANone);
    ("GetBindResult",[
      ("This",AThis);
      ("pclsidProtocol",ANone);
      ("pdwResult",ANone);
      ("pszResult",ANone);
      ("pdwReserved",ANone);
    ],MANone);
  ]);
  ("ICatalogFileInfoVtbl",IAManual, "IUnknownVtbl", [
    ("GetCatalogFile",[
      ("This",AThis);
      ("ppszCatalogFile",ANone);
    ],MANone);
    ("GetJavaTrust",[
      ("This",AThis);
      ("ppJavaTrust",ANone);
    ],MANone);
  ]);
  ("ICodeInstallVtbl",IAManual, "IWindowForBindingUIVtbl", [
    ("OnCodeInstallProblem",[
      ("This",AThis);
      ("ulStatusCode",ANone);
      ("szDestination",ANone);
      ("szSource",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IDataFilterVtbl",IAManual, "IUnknownVtbl", [
    ("DoEncode",[
      ("This",AThis);
      ("dwFlags",ANone);
      ("lInBufferSize",ANone);
      ("pbInBuffer",ANone);
      ("lOutBufferSize",ANone);
      ("pbOutBuffer",ANone);
      ("lInBytesAvailable",ANone);
      ("plInBytesRead",ANone);
      ("plOutBytesWritten",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("DoDecode",[
      ("This",AThis);
      ("dwFlags",ANone);
      ("lInBufferSize",ANone);
      ("pbInBuffer",ANone);
      ("lOutBufferSize",ANone);
      ("pbOutBuffer",ANone);
      ("lInBytesAvailable",ANone);
      ("plInBytesRead",ANone);
      ("plOutBytesWritten",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("SetEncodingLevel",[
      ("This",AThis);
      ("dwEncLevel",ANone);
    ],MANone);
  ]);
  ("IEncodingFilterFactoryVtbl",IAManual, "IUnknownVtbl", [
    ("FindBestFilter",[
      ("This",AThis);
      ("pwzCodeIn",ANone);
      ("pwzCodeOut",ANone);
      ("info",ANone);
      ("ppDF",ANone);
    ],MANone);
    ("GetDefaultFilter",[
      ("This",AThis);
      ("pwzCodeIn",ANone);
      ("pwzCodeOut",ANone);
      ("ppDF",ANone);
    ],MANone);
  ]);
  ("IGetBindHandleVtbl",IAManual, "IUnknownVtbl", [
    ("GetBindHandle",[
      ("This",AThis);
      ("enumRequestedHandle",ANone);
      ("pRetHandle",ANone);
    ],MANone);
  ]);
  ("IHttpNegotiate2Vtbl",IAManual, "IHttpNegotiateVtbl", [
    ("GetRootSecurityId",[
      ("This",AThis);
      ("pbSecurityId",ANone);
      ("pcbSecurityId",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IHttpNegotiate3Vtbl",IAManual, "IHttpNegotiate2Vtbl", [
    ("GetSerializedClientCertContext",[
      ("This",AThis);
      ("ppbCert",ANone);
      ("pcbCert",ANone);
    ],MANone);
  ]);
  ("IHttpNegotiateVtbl",IAManual, "IUnknownVtbl", [
    ("BeginningTransaction",[
      ("This",AThis);
      ("szURL",ANone);
      ("szHeaders",ANone);
      ("dwReserved",ANone);
      ("pszAdditionalHeaders",ANone);
    ],MANone);
    ("OnResponse",[
      ("This",AThis);
      ("dwResponseCode",ANone);
      ("szResponseHeaders",ANone);
      ("szRequestHeaders",ANone);
      ("pszAdditionalRequestHeaders",ANone);
    ],MANone);
  ]);
  ("IHttpSecurityVtbl",IAManual, "IWindowForBindingUIVtbl", [
    ("OnSecurityProblem",[
      ("This",AThis);
      ("dwProblem",ANone);
    ],MANone);
  ]);
  ("IInternetBindInfoExVtbl",IAManual, "IInternetBindInfoVtbl", [
    ("GetBindInfoEx",[
      ("This",AThis);
      ("grfBINDF",ANone);
      ("pbindinfo",ANone);
      ("grfBINDF2",ANone);
      ("pdwReserved",ANone);
    ],MANone);
  ]);
  ("IInternetBindInfoVtbl",IAManual, "IUnknownVtbl", [
    ("GetBindInfo",[
      ("This",AThis);
      ("grfBINDF",ANone);
      ("pbindinfo",ANone);
    ],MANone);
    ("GetBindString",[
      ("This",AThis);
      ("ulStringType",ANone);
      ("ppwzStr",ANone);
      ("cEl",ANone);
      ("pcElFetched",ANone);
    ],MANone);
  ]);
  ("IInternetHostSecurityManagerVtbl",IAManual, "IUnknownVtbl", [
    ("GetSecurityId",[
      ("This",AThis);
      ("pbSecurityId",ANone);
      ("pcbSecurityId",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("ProcessUrlAction",[
      ("This",AThis);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwFlags",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("QueryCustomPolicy",[
      ("This",AThis);
      ("guidKey",ANone);
      ("ppPolicy",ANone);
      ("pcbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IInternetPriorityVtbl",IAManual, "IUnknownVtbl", [
    ("SetPriority",[
      ("This",AThis);
      ("nPriority",ANone);
    ],MANone);
    ("GetPriority",[
      ("This",AThis);
      ("pnPriority",ANone);
    ],MANone);
  ]);
  ("IInternetProtocolExVtbl",IAManual, "IInternetProtocolVtbl", [
    ("StartEx",[
      ("This",AThis);
      ("pUri",ANone);
      ("pOIProtSink",ANone);
      ("pOIBindInfo",ANone);
      ("grfPI",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IInternetProtocolInfoVtbl",IAManual, "IUnknownVtbl", [
    ("ParseUrl",[
      ("This",AThis);
      ("pwzUrl",ANone);
      ("ParseAction",ANone);
      ("dwParseFlags",ANone);
      ("pwzResult",ANone);
      ("cchResult",ANone);
      ("pcchResult",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("CombineUrl",[
      ("This",AThis);
      ("pwzBaseUrl",ANone);
      ("pwzRelativeUrl",ANone);
      ("dwCombineFlags",ANone);
      ("pwzResult",ANone);
      ("cchResult",ANone);
      ("pcchResult",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("CompareUrl",[
      ("This",AThis);
      ("pwzUrl1",ANone);
      ("pwzUrl2",ANone);
      ("dwCompareFlags",ANone);
    ],MANone);
    ("QueryInfo",[
      ("This",AThis);
      ("pwzUrl",ANone);
      ("OueryOption",ANone);
      ("dwQueryFlags",ANone);
      ("pBuffer",ANone);
      ("cbBuffer",ANone);
      ("pcbBuf",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IInternetProtocolRootVtbl",IAManual, "IUnknownVtbl", [
    ("Start",[
      ("This",AThis);
      ("szUrl",ANone);
      ("pOIProtSink",ANone);
      ("pOIBindInfo",ANone);
      ("grfPI",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("Continue",[
      ("This",AThis);
      ("pProtocolData",ANone);
    ],MANone);
    ("Abort",[
      ("This",AThis);
      ("hrReason",ANone);
      ("dwOptions",ANone);
    ],MANone);
    ("Terminate",[
      ("This",AThis);
      ("dwOptions",ANone);
    ],MANone);
    ("Suspend",[
      ("This",AThis);
    ],MANone);
    ("Resume",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IInternetProtocolSinkStackableVtbl",IAManual, "IUnknownVtbl", [
    ("SwitchSink",[
      ("This",AThis);
      ("pOIProtSink",ANone);
    ],MANone);
    ("CommitSwitch",[
      ("This",AThis);
    ],MANone);
    ("RollbackSwitch",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IInternetProtocolSinkVtbl",IAManual, "IUnknownVtbl", [
    ("Switch",[
      ("This",AThis);
      ("pProtocolData",ANone);
    ],MANone);
    ("ReportProgress",[
      ("This",AThis);
      ("ulStatusCode",ANone);
      ("szStatusText",ANone);
    ],MANone);
    ("ReportData",[
      ("This",AThis);
      ("grfBSCF",ANone);
      ("ulProgress",ANone);
      ("ulProgressMax",ANone);
    ],MANone);
    ("ReportResult",[
      ("This",AThis);
      ("hrResult",ANone);
      ("dwError",ANone);
      ("szResult",ANone);
    ],MANone);
  ]);
  ("IInternetProtocolVtbl",IAManual, "IInternetProtocolRootVtbl", [
    ("Read",[
      ("This",AThis);
      ("pv",ANone);
      ("cb",ANone);
      ("pcbRead",ANone);
    ],MANone);
    ("Seek",[
      ("This",AThis);
      ("dlibMove",ANone);
      ("dwOrigin",ANone);
      ("plibNewPosition",ANone);
    ],MANone);
    ("LockRequest",[
      ("This",AThis);
      ("dwOptions",ANone);
    ],MANone);
    ("UnlockRequest",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IInternetSecurityManagerEx2Vtbl",IAManual, "IInternetSecurityManagerExVtbl", [
    ("MapUrlToZoneEx2",[
      ("This",AThis);
      ("pUri",ANone);
      ("pdwZone",ANone);
      ("dwFlags",ANone);
      ("ppwszMappedUrl",ANone);
      ("pdwOutFlags",ANone);
    ],MANone);
    ("ProcessUrlActionEx2",[
      ("This",AThis);
      ("pUri",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwFlags",ANone);
      ("dwReserved",ANone);
      ("pdwOutFlags",ANone);
    ],MANone);
    ("GetSecurityIdEx2",[
      ("This",AThis);
      ("pUri",ANone);
      ("pbSecurityId",ANone);
      ("pcbSecurityId",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("QueryCustomPolicyEx2",[
      ("This",AThis);
      ("pUri",ANone);
      ("guidKey",ANone);
      ("ppPolicy",ANone);
      ("pcbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IInternetSecurityManagerExVtbl",IAManual, "IInternetSecurityManagerVtbl", [
    ("ProcessUrlActionEx",[
      ("This",AThis);
      ("pwszUrl",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwFlags",ANone);
      ("dwReserved",ANone);
      ("pdwOutFlags",ANone);
    ],MANone);
  ]);
  ("IInternetSecurityManagerVtbl",IAManual, "IUnknownVtbl", [
    ("SetSecuritySite",[
      ("This",AThis);
      ("pSite",ANone);
    ],MANone);
    ("GetSecuritySite",[
      ("This",AThis);
      ("ppSite",ANone);
    ],MANone);
    ("MapUrlToZone",[
      ("This",AThis);
      ("pwszUrl",ANone);
      ("pdwZone",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("GetSecurityId",[
      ("This",AThis);
      ("pwszUrl",ANone);
      ("pbSecurityId",ANone);
      ("pcbSecurityId",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("ProcessUrlAction",[
      ("This",AThis);
      ("pwszUrl",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwFlags",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("QueryCustomPolicy",[
      ("This",AThis);
      ("pwszUrl",ANone);
      ("guidKey",ANone);
      ("ppPolicy",ANone);
      ("pcbPolicy",ANone);
      ("pContext",ANone);
      ("cbContext",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("SetZoneMapping",[
      ("This",AThis);
      ("dwZone",ANone);
      ("lpszPattern",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("GetZoneMappings",[
      ("This",AThis);
      ("dwZone",ANone);
      ("ppenumString",ANone);
      ("dwFlags",ANone);
    ],MANone);
  ]);
  ("IInternetSecurityMgrSiteVtbl",IAManual, "IUnknownVtbl", [
    ("GetWindow",[
      ("This",AThis);
      ("phwnd",ANone);
    ],MANone);
    ("EnableModeless",[
      ("This",AThis);
      ("fEnable",ANone);
    ],MANone);
  ]);
  ("IInternetSessionVtbl",IAManual, "IUnknownVtbl", [
    ("RegisterNameSpace",[
      ("This",AThis);
      ("pCF",ANone);
      ("rclsid",ANone);
      ("pwzProtocol",ANone);
      ("cPatterns",ANone);
      ("ppwzPatterns",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("UnregisterNameSpace",[
      ("This",AThis);
      ("pCF",ANone);
      ("pszProtocol",ANone);
    ],MANone);
    ("RegisterMimeFilter",[
      ("This",AThis);
      ("pCF",ANone);
      ("rclsid",ANone);
      ("pwzType",ANone);
    ],MANone);
    ("UnregisterMimeFilter",[
      ("This",AThis);
      ("pCF",ANone);
      ("pwzType",ANone);
    ],MANone);
    ("CreateBinding",[
      ("This",AThis);
      ("pBC",ANone);
      ("szUrl",ANone);
      ("pUnkOuter",ANone);
      ("ppUnk",ANone);
      ("ppOInetProt",ANone);
      ("dwOption",ANone);
    ],MANone);
    ("SetSessionOption",[
      ("This",AThis);
      ("dwOption",ANone);
      ("pBuffer",ANone);
      ("dwBufferLength",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("GetSessionOption",[
      ("This",AThis);
      ("dwOption",ANone);
      ("pBuffer",ANone);
      ("pdwBufferLength",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IInternetThreadSwitchVtbl",IAManual, "IUnknownVtbl", [
    ("Prepare",[
      ("This",AThis);
    ],MANone);
    ("Continue",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IInternetVtbl",IAManual, "IUnknownVtbl", [
  ]);
  ("IInternetZoneManagerEx2Vtbl",IAManual, "IInternetZoneManagerExVtbl", [
    ("GetZoneAttributesEx",[
      ("This",AThis);
      ("dwZone",ANone);
      ("pZoneAttributes",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("GetZoneSecurityState",[
      ("This",AThis);
      ("dwZoneIndex",ANone);
      ("fRespectPolicy",ANone);
      ("pdwState",ANone);
      ("pfPolicyEncountered",ANone);
    ],MANone);
    ("GetIESecurityState",[
      ("This",AThis);
      ("fRespectPolicy",ANone);
      ("pdwState",ANone);
      ("pfPolicyEncountered",ANone);
      ("fNoCache",ANone);
    ],MANone);
    ("FixUnsecureSettings",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IInternetZoneManagerExVtbl",IAManual, "IInternetZoneManagerVtbl", [
    ("GetZoneActionPolicyEx",[
      ("This",AThis);
      ("dwZone",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("urlZoneReg",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("SetZoneActionPolicyEx",[
      ("This",AThis);
      ("dwZone",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("urlZoneReg",ANone);
      ("dwFlags",ANone);
    ],MANone);
  ]);
  ("IInternetZoneManagerVtbl",IAManual, "IUnknownVtbl", [
    ("GetZoneAttributes",[
      ("This",AThis);
      ("dwZone",ANone);
      ("pZoneAttributes",ANone);
    ],MANone);
    ("SetZoneAttributes",[
      ("This",AThis);
      ("dwZone",ANone);
      ("pZoneAttributes",ANone);
    ],MANone);
    ("GetZoneCustomPolicy",[
      ("This",AThis);
      ("dwZone",ANone);
      ("guidKey",ANone);
      ("ppPolicy",ANone);
      ("pcbPolicy",ANone);
      ("urlZoneReg",ANone);
    ],MANone);
    ("SetZoneCustomPolicy",[
      ("This",AThis);
      ("dwZone",ANone);
      ("guidKey",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("urlZoneReg",ANone);
    ],MANone);
    ("GetZoneActionPolicy",[
      ("This",AThis);
      ("dwZone",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("urlZoneReg",ANone);
    ],MANone);
    ("SetZoneActionPolicy",[
      ("This",AThis);
      ("dwZone",ANone);
      ("dwAction",ANone);
      ("pPolicy",ANone);
      ("cbPolicy",ANone);
      ("urlZoneReg",ANone);
    ],MANone);
    ("PromptAction",[
      ("This",AThis);
      ("dwAction",ANone);
      ("hwndParent",ANone);
      ("pwszUrl",ANone);
      ("pwszText",ANone);
      ("dwPromptFlags",ANone);
    ],MANone);
    ("LogAction",[
      ("This",AThis);
      ("dwAction",ANone);
      ("pwszUrl",ANone);
      ("pwszText",ANone);
      ("dwLogFlags",ANone);
    ],MANone);
    ("CreateZoneEnumerator",[
      ("This",AThis);
      ("pdwEnum",ANone);
      ("pdwCount",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("GetZoneAt",[
      ("This",AThis);
      ("dwEnum",ANone);
      ("dwIndex",ANone);
      ("pdwZone",ANone);
    ],MANone);
    ("DestroyZoneEnumerator",[
      ("This",AThis);
      ("dwEnum",ANone);
    ],MANone);
    ("CopyTemplatePoliciesToZone",[
      ("This",AThis);
      ("dwTemplate",ANone);
      ("dwZone",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IMonikerPropVtbl",IAManual, "IUnknownVtbl", [
    ("PutProperty",[
      ("This",AThis);
      ("mkp",ANone);
      ("val",ANone);
    ],MANone);
  ]);
  ("IPersistMonikerVtbl",IAManual, "IUnknownVtbl", [
    ("GetClassID",[
      ("This",AThis);
      ("pClassID",ANone);
    ],MANone);
    ("IsDirty",[
      ("This",AThis);
    ],MANone);
    ("Load",[
      ("This",AThis);
      ("fFullyAvailable",ANone);
      ("pimkName",ANone);
      ("pibc",ANone);
      ("grfMode",ANone);
    ],MANone);
    ("Save",[
      ("This",AThis);
      ("pimkName",ANone);
      ("pbc",ANone);
      ("fRemember",ANone);
    ],MANone);
    ("SaveCompleted",[
      ("This",AThis);
      ("pimkName",ANone);
      ("pibc",ANone);
    ],MANone);
    ("GetCurMoniker",[
      ("This",AThis);
      ("ppimkName",ANone);
    ],MANone);
  ]);
  ("ISoftDistExtVtbl",IAManual, "IUnknownVtbl", [
    ("ProcessSoftDist",[
      ("This",AThis);
      ("szCDFURL",ANone);
      ("pSoftDistElement",ANone);
      ("lpsdi",ANone);
    ],MANone);
    ("GetFirstCodeBase",[
      ("This",AThis);
      ("szCodeBase",ANone);
      ("dwMaxSize",ANone);
    ],MANone);
    ("GetNextCodeBase",[
      ("This",AThis);
      ("szCodeBase",ANone);
      ("dwMaxSize",ANone);
    ],MANone);
    ("AsyncInstallDistributionUnit",[
      ("This",AThis);
      ("pbc",ANone);
      ("pvReserved",ANone);
      ("flags",ANone);
      ("lpcbh",ANone);
    ],MANone);
  ]);
  ("IUriBuilderFactoryVtbl",IAManual, "IUnknownVtbl", [
    ("CreateIUriBuilder",[
      ("This",AThis);
      ("dwFlags",ANone);
      ("dwReserved",ANone);
      ("ppIUriBuilder",ANone);
    ],MANone);
    ("CreateInitializedIUriBuilder",[
      ("This",AThis);
      ("dwFlags",ANone);
      ("dwReserved",ANone);
      ("ppIUriBuilder",ANone);
    ],MANone);
  ]);
  ("IUriBuilderVtbl",IAManual, "IUnknownVtbl", [
    ("CreateUriSimple",[
      ("This",AThis);
      ("dwAllowEncodingPropertyMask",ANone);
      ("dwReserved",ANone);
      ("ppIUri",ANone);
    ],MANone);
    ("CreateUri",[
      ("This",AThis);
      ("dwCreateFlags",ANone);
      ("dwAllowEncodingPropertyMask",ANone);
      ("dwReserved",ANone);
      ("ppIUri",ANone);
    ],MANone);
    ("CreateUriWithFlags",[
      ("This",AThis);
      ("dwCreateFlags",ANone);
      ("dwUriBuilderFlags",ANone);
      ("dwAllowEncodingPropertyMask",ANone);
      ("dwReserved",ANone);
      ("ppIUri",ANone);
    ],MANone);
    ("GetIUri",[
      ("This",AThis);
      ("ppIUri",ANone);
    ],MANone);
    ("SetIUri",[
      ("This",AThis);
      ("pIUri",ANone);
    ],MANone);
    ("GetFragment",[
      ("This",AThis);
      ("pcchFragment",ANone);
      ("ppwzFragment",ANone);
    ],MANone);
    ("GetHost",[
      ("This",AThis);
      ("pcchHost",ANone);
      ("ppwzHost",ANone);
    ],MANone);
    ("GetPassword",[
      ("This",AThis);
      ("pcchPassword",ANone);
      ("ppwzPassword",ANone);
    ],MANone);
    ("GetPath",[
      ("This",AThis);
      ("pcchPath",ANone);
      ("ppwzPath",ANone);
    ],MANone);
    ("GetPort",[
      ("This",AThis);
      ("pfHasPort",ANone);
      ("pdwPort",ANone);
    ],MANone);
    ("GetQuery",[
      ("This",AThis);
      ("pcchQuery",ANone);
      ("ppwzQuery",ANone);
    ],MANone);
    ("GetSchemeName",[
      ("This",AThis);
      ("pcchSchemeName",ANone);
      ("ppwzSchemeName",ANone);
    ],MANone);
    ("GetUserNameA",[
      ("This",AThis);
      ("pcchUserName",ANone);
      ("ppwzUserName",ANone);
    ],MANone);
    ("SetFragment",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("SetHost",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("SetPassword",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("SetPath",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("SetPort",[
      ("This",AThis);
      ("fHasPort",ANone);
      ("dwNewValue",ANone);
    ],MANone);
    ("SetQuery",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("SetSchemeName",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("SetUserName",[
      ("This",AThis);
      ("pwzNewValue",ANone);
    ],MANone);
    ("RemoveProperties",[
      ("This",AThis);
      ("dwPropertyMask",ANone);
    ],MANone);
    ("HasBeenModified",[
      ("This",AThis);
      ("pfModified",ANone);
    ],MANone);
  ]);
  ("IUriContainerVtbl",IAManual, "IUnknownVtbl", [
    ("GetIUri",[
      ("This",AThis);
      ("ppIUri",ANone);
    ],MANone);
  ]);
  ("IUriVtbl",IAManual, "IUnknownVtbl", [
    ("GetPropertyBSTR",[
      ("This",AThis);
      ("uriProp",ANone);
      ("pbstrProperty",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("GetPropertyLength",[
      ("This",AThis);
      ("uriProp",ANone);
      ("pcchProperty",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("GetPropertyDWORD",[
      ("This",AThis);
      ("uriProp",ANone);
      ("pdwProperty",ANone);
      ("dwFlags",ANone);
    ],MANone);
    ("HasProperty",[
      ("This",AThis);
      ("uriProp",ANone);
      ("pfHasProperty",ANone);
    ],MANone);
    ("GetAbsoluteUri",[
      ("This",AThis);
      ("pbstrAbsoluteUri",ANone);
    ],MANone);
    ("GetAuthority",[
      ("This",AThis);
      ("pbstrAuthority",ANone);
    ],MANone);
    ("GetDisplayUri",[
      ("This",AThis);
      ("pbstrDisplayString",ANone);
    ],MANone);
    ("GetDomain",[
      ("This",AThis);
      ("pbstrDomain",ANone);
    ],MANone);
    ("GetExtension",[
      ("This",AThis);
      ("pbstrExtension",ANone);
    ],MANone);
    ("GetFragment",[
      ("This",AThis);
      ("pbstrFragment",ANone);
    ],MANone);
    ("GetHost",[
      ("This",AThis);
      ("pbstrHost",ANone);
    ],MANone);
    ("GetPassword",[
      ("This",AThis);
      ("pbstrPassword",ANone);
    ],MANone);
    ("GetPath",[
      ("This",AThis);
      ("pbstrPath",ANone);
    ],MANone);
    ("GetPathAndQuery",[
      ("This",AThis);
      ("pbstrPathAndQuery",ANone);
    ],MANone);
    ("GetQuery",[
      ("This",AThis);
      ("pbstrQuery",ANone);
    ],MANone);
    ("GetRawUri",[
      ("This",AThis);
      ("pbstrRawUri",ANone);
    ],MANone);
    ("GetSchemeName",[
      ("This",AThis);
      ("pbstrSchemeName",ANone);
    ],MANone);
    ("GetUserInfo",[
      ("This",AThis);
      ("pbstrUserInfo",ANone);
    ],MANone);
    ("GetUserNameA",[
      ("This",AThis);
      ("pbstrUserName",ANone);
    ],MANone);
    ("GetHostType",[
      ("This",AThis);
      ("pdwHostType",ANone);
    ],MANone);
    ("GetPort",[
      ("This",AThis);
      ("pdwPort",ANone);
    ],MANone);
    ("GetScheme",[
      ("This",AThis);
      ("pdwScheme",ANone);
    ],MANone);
    ("GetZone",[
      ("This",AThis);
      ("pdwZone",ANone);
    ],MANone);
    ("GetProperties",[
      ("This",AThis);
      ("pdwFlags",ANone);
    ],MANone);
    ("IsEqual",[
      ("This",AThis);
      ("pUri",ANone);
      ("pfEqual",ANone);
    ],MANone);
  ]);
  ("IWinInetCacheHints2Vtbl",IAManual, "IWinInetCacheHintsVtbl", [
    ("SetCacheExtension2",[
      ("This",AThis);
      ("pwzExt",ANone);
      ("pwzCacheFile",ANone);
      ("pcchCacheFile",ANone);
      ("pdwWinInetError",ANone);
      ("pdwReserved",ANone);
    ],MANone);
  ]);
  ("IWinInetCacheHintsVtbl",IAManual, "IUnknownVtbl", [
    ("SetCacheExtension",[
      ("This",AThis);
      ("pwzExt",ANone);
      ("pszCacheFile",ANone);
      ("pcbCacheFile",ANone);
      ("pdwWinInetError",ANone);
      ("pdwReserved",ANone);
    ],MANone);
  ]);
  ("IWinInetFileStreamVtbl",IAManual, "IUnknownVtbl", [
    ("SetHandleForUnlock",[
      ("This",AThis);
      ("hWinInetLockHandle",ANone);
      ("dwReserved",ANone);
    ],MANone);
    ("SetDeleteFile",[
      ("This",AThis);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IWinInetHttpInfoVtbl",IAManual, "IWinInetInfoVtbl", [
    ("QueryInfo",[
      ("This",AThis);
      ("dwOption",ANone);
      ("pBuffer",ANone);
      ("pcbBuf",ANone);
      ("pdwFlags",ANone);
      ("pdwReserved",ANone);
    ],MANone);
  ]);
  ("IWinInetHttpTimeoutsVtbl",IAManual, "IUnknownVtbl", [
    ("GetRequestTimeouts",[
      ("This",AThis);
      ("pdwConnectTimeout",ANone);
      ("pdwSendTimeout",ANone);
      ("pdwReceiveTimeout",ANone);
    ],MANone);
  ]);
  ("IWinInetInfoVtbl",IAManual, "IUnknownVtbl", [
    ("QueryOption",[
      ("This",AThis);
      ("dwOption",ANone);
      ("pBuffer",ANone);
      ("pcbBuf",ANone);
    ],MANone);
  ]);
  ("IWindowForBindingUIVtbl",IAManual, "IUnknownVtbl", [
    ("GetWindow",[
      ("This",AThis);
      ("rguidReason",ANone);
      ("phwnd",ANone);
    ],MANone);
  ]);
  ("IWrappedProtocolVtbl",IAManual, "IUnknownVtbl", [
    ("GetWrapperCode",[
      ("This",AThis);
      ("pnCode",ANone);
      ("dwReserved",ANone);
    ],MANone);
  ]);
  ("IZoneIdentifier2Vtbl",IAManual, "IZoneIdentifierVtbl", [
    ("GetLastWriterPackageFamilyName",[
      ("This",AThis);
      ("packageFamilyName",ANone);
    ],MANone);
    ("SetLastWriterPackageFamilyName",[
      ("This",AThis);
      ("packageFamilyName",ANone);
    ],MANone);
    ("RemoveLastWriterPackageFamilyName",[
      ("This",AThis);
    ],MANone);
    ("GetAppZoneId",[
      ("This",AThis);
      ("zone",ANone);
    ],MANone);
    ("SetAppZoneId",[
      ("This",AThis);
      ("zone",ANone);
    ],MANone);
    ("RemoveAppZoneId",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IZoneIdentifierVtbl",IAManual, "IUnknownVtbl", [
    ("GetId",[
      ("This",AThis);
      ("pdwZone",ANone);
    ],MANone);
    ("SetId",[
      ("This",AThis);
      ("dwZone",ANone);
    ],MANone);
    ("Remove",[
      ("This",AThis);
    ],MANone);
  ]);
  ]
