module annotations_d2d1

open annotations
open custom_impls

let d2d1 =
 [
  ("ID2D1BitmapBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetExtendModeX",[
      ("This",AThis);
      ("extendModeX",ANone);
    ],MANone);
    ("SetExtendModeY",[
      ("This",AThis);
      ("extendModeY",ANone);
    ],MANone);
    ("SetInterpolationMode",[
      ("This",AThis);
      ("interpolationMode",ANone);
    ],MANone);
    ("SetBitmap",[
      ("This",AThis);
      ("bitmap",InComPtr);
    ],MANone);
    ("GetExtendModeX",[
      ("This",AThis);
    ],MANone);
    ("GetExtendModeY",[
      ("This",AThis);
    ],MANone);
    ("GetInterpolationMode",[
      ("This",AThis);
    ],MANone);
    ("GetBitmap",[
      ("This",AThis);
      ("bitmap",OutReturnOptionalComPtr);
    ],MANone);
  ]);
  ("ID2D1BitmapRenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("GetBitmap",[
      ("This",AThis);
      ("bitmap",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1BitmapVtbl",IAAutogen(Set.ofList []), "ID2D1ImageVtbl", [
    ("GetSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetPixelSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetPixelFormat",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetDpi",[
      ("This",AThis);
      ("dpiX",OutReturn);
      ("dpiY",OutReturn);
    ],MANone);
    ("CopyFromBitmap",[
      ("This",AThis);
      ("destPoint",InOptional);
      ("bitmap",InComPtr);
      ("srcRect",InOptional);
    ],MANone);
    ("CopyFromRenderTarget",[
      ("This",AThis);
      ("destPoint",InOptional);
      ("renderTarget",InComPtr);
      ("srcRect",InOptional);
    ],MANone);
    ("CopyFromMemory",[
      ("This",AThis);
      ("dstRect",InOptional);
      ("srcData",ANone);
      ("pitch",ANone);
    ],MAUnsafe);
  ]);
  ("ID2D1BrushVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("SetOpacity",[
      ("This",AThis);
      ("opacity",ANone);
    ],MANone);
    ("SetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("GetOpacity",[
      ("This",AThis);
    ],MANone);
    ("GetTransform",[
      ("This",AThis);
      ("transform",OutReturn);
    ],MANone);
  ]);
  ("ID2D1DCRenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("BindDC",[
      ("This",AThis);
      ("hDC",ANone);
      ("pSubRect",ANone);
    ],MANone);
  ]);
  ("ID2D1DrawingStateBlockVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetDescription",[
      ("This",AThis);
      ("stateDescription",OutReturn);
    ],MANone);
    ("SetDescription",[
      ("This",AThis);
      ("stateDescription",ANone);
    ],MANone);
    ("SetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",InComPtr);
    ],MANone);
    ("GetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1EllipseGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetEllipse",[
      ("This",AThis);
      ("ellipse",OutReturn);
    ],MANone);
  ]);
  ("ID2D1FactoryVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("ReloadSystemMetrics",[
      ("This",AThis);
    ],MANone);
    ("GetDesktopDpi",[
      ("This",AThis);
      ("dpiX",OutReturn);
      ("dpiY",OutReturn);
    ],MANone);
    ("CreateRectangleGeometry",[
      ("This",AThis);
      ("rectangle",ANone);
      ("rectangleGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateRoundedRectangleGeometry",[
      ("This",AThis);
      ("roundedRectangle",ANone);
      ("roundedRectangleGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateEllipseGeometry",[
      ("This",AThis);
      ("ellipse",ANone);
      ("ellipseGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateGeometryGroup",[
      ("This",AThis);
      ("fillMode",ANone);
      ("geometries",InComPtrArrayOfSize "geometriesCount");
      ("geometriesCount",ANone);
      ("geometryGroup",OutReturnComPtr);
    ],MANone);
    ("CreateTransformedGeometry",[
      ("This",AThis);
      ("sourceGeometry",InComPtr);
      ("transform",InOptional);
      ("transformedGeometry",OutReturnComPtr);
    ],MANone);
    ("CreatePathGeometry",[
      ("This",AThis);
      ("pathGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateStrokeStyle",[
      ("This",AThis);
      ("strokeStyleProperties",ANone);
      ("dashes",InOptionalArrayOfSize "dashesCount");
      ("dashesCount",ANone);
      ("strokeStyle",OutReturnComPtr);
    ],MANone);
    ("CreateDrawingStateBlock",[
      ("This",AThis);
      ("drawingStateDescription",InOptional);
      ("textRenderingParams",InOptionalComPtr);
      ("drawingStateBlock",OutReturnComPtr);
    ],MANone);
    ("CreateWicBitmapRenderTarget",[
      ("This",AThis);
      ("target",InComPtr);
      ("renderTargetProperties",InOptional);
      ("renderTarget",OutReturnComPtr);
    ],MADontImplement);
    ("CreateHwndRenderTarget",[
      ("This",AThis);
      ("renderTargetProperties",ANone);
      ("hwndRenderTargetProperties",ANone);
      ("hwndRenderTarget",OutReturnComPtr);
    ],MANone);
    ("CreateDxgiSurfaceRenderTarget",[
      ("This",AThis);
      ("dxgiSurface",InComPtr);
      ("renderTargetProperties",ANone);
      ("renderTarget",OutReturnComPtr);
    ],MANone);
    ("CreateDCRenderTarget",[
      ("This",AThis);
      ("renderTargetProperties",ANone);
      ("dcRenderTarget",OutReturnComPtr);
    ],MANone);
  ]);
  // TODO: add 'private' flag to IAAutogen flags
  ("ID2D1GdiInteropRenderTargetVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetDC",[
      ("This",AThis);
      ("mode",ANone);
      ("hdc",OutReturn);
    ],MANone);
    ("ReleaseDC",[
      ("This",AThis);
      ("update",InOptional);
    ],MANone);
  ]);
  ("ID2D1GeometryGroupVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetFillMode",[
      ("This",AThis);
    ],MANone);
    ("GetSourceGeometryCount",[
      ("This",AThis);
    ],MANone);
    ("GetSourceGeometries",[
      ("This",AThis);
      ("geometries",OutReturnComPtr);
      ("geometriesCount",ANone);
    ], MACustom id2d1geometrygroup_getsourcegeometries); // Handmade implementation
  ]);
  ("ID2D1GeometrySinkVtbl",IAAutogen(Set.ofList []), "ID2D1SimplifiedGeometrySinkVtbl", [
    ("AddLine",[
      ("This",AThis);
      ("point",ANone);
    ],MANone);
    ("AddBezier",[
      ("This",AThis);
      ("bezier",ANone);
    ],MANone);
    ("AddQuadraticBezier",[
      ("This",AThis);
      ("bezier",ANone);
    ],MANone);
    ("AddQuadraticBeziers",[
      ("This",AThis);
      ("beziers",InArrayOfSize "beziersCount");
      ("beziersCount",ANone);
    ],MANone);
    ("AddArc",[
      ("This",AThis);
      ("arc",ANone);
    ],MANone);
  ]);
  ("ID2D1GeometryVtbl", IAAutogen (Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetBounds",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("bounds",OutReturn);
    ],MANone);
    ("GetWidenedBounds",[
      ("This",AThis);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("bounds",OutReturn);
    ],MANone);
    ("StrokeContainsPoint",[
      ("This",AThis);
      ("point",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("contains",OutReturn);
    ],MANone);
    ("FillContainsPoint",[
      ("This",AThis);
      ("point",ANone);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("contains",OutReturn);
    ],MANone);
    ("CompareWithGeometry",[
      ("This",AThis);
      ("inputGeometry",InComPtr);
      ("inputGeometryTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("relation",OutReturn);
    ],MANone);
    ("Simplify",[
      ("This",AThis);
      ("simplificationOption",ANone);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
    ("Tessellate",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("tessellationSink",InComPtr);
    ],MANone);
    ("CombineWithGeometry",[
      ("This",AThis);
      ("inputGeometry",InComPtr);
      ("combineMode",ANone);
      ("inputGeometryTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
    ("Outline",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
    ("ComputeArea",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("area",OutReturn);
    ],MANone);
    ("ComputeLength",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("length",OutReturn);
    ],MANone);
    ("ComputePointAtLength",[
      ("This",AThis);
      ("length",ANone);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("point",OutReturn);
      ("unitTangentVector",OutReturn);
    ],MANone);
    ("Widen",[
      ("This",AThis);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
  ]);
  ("ID2D1GradientStopCollectionVtbl", IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetGradientStopCount",[
      ("This",AThis);
    ],MANone);
    ("GetGradientStops",[
      ("This",AThis);
      ("gradientStops", OutArrayOfSize "gradientStopsCount");
      ("gradientStopsCount", ANone);
    ],MANone);
    ("GetColorInterpolationGamma",[
      ("This",AThis);
    ],MANone);
    ("GetExtendMode",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1HwndRenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("CheckWindowState",[
      ("This",AThis);
    ],MANone);
    ("Resize",[
      ("This",AThis);
      ("pixelSize",ANone);
    ],MANone);
    ("GetHwnd",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1ImageVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [  ]);
  ("ID2D1LayerVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
      ("GetSize",[
          ("This",AThis);
          ("__ret_val",OutReturn);
        ],MANone);
  ]);
  ("ID2D1LinearGradientBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetStartPoint",[
      ("This",AThis);
      ("startPoint",ANone);
    ],MANone);
    ("SetEndPoint",[
      ("This",AThis);
      ("endPoint",ANone);
    ],MANone);
    ("GetStartPoint",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetEndPoint",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetGradientStopCollection",[
      ("This",AThis);
      ("gradientStopCollection",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1MeshVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("Open",[
      ("This",AThis);
      ("tessellationSink",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1PathGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("Open",[
      ("This",AThis);
      ("geometrySink",OutReturnComPtr);
    ],MANone);
    ("Stream",[
      ("This",AThis);
      ("geometrySink",InComPtr);
    ],MANone);
    ("GetSegmentCount",[
      ("This",AThis);
      ("count",OutReturn);
    ],MANone);
    ("GetFigureCount",[
      ("This",AThis);
      ("count",OutReturn);
    ],MANone);
  ]);
  ("ID2D1RadialGradientBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetCenter",[
      ("This",AThis);
      ("center",ANone);
    ],MANone);
    ("SetGradientOriginOffset",[
      ("This",AThis);
      ("gradientOriginOffset",ANone);
    ],MANone);
    ("SetRadiusX",[
      ("This",AThis);
      ("radiusX",ANone);
    ],MANone);
    ("SetRadiusY",[
      ("This",AThis);
      ("radiusY",ANone);
    ],MANone);
    ("GetCenter",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetGradientOriginOffset",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetRadiusX",[
      ("This",AThis);
    ],MANone);
    ("GetRadiusY",[
      ("This",AThis);
    ],MANone);
    ("GetGradientStopCollection",[
      ("This",AThis);
      ("gradientStopCollection",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1RectangleGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetRect",[
      ("This",AThis);
      ("rect",OutReturn);
    ],MANone);
  ]);
  ("ID2D1RenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("CreateBitmap",[
      ("This",AThis);
      ("size",ANone);
      ("srcData",ANone);
      ("pitch",ANone);
      ("bitmapProperties",ANone);
      ("bitmap",OutReturnComPtr);
    ],MAUnsafe);
    ("CreateBitmapFromWicBitmap",[
      ("This",AThis);
      ("wicBitmapSource",InComPtr);
      ("bitmapProperties",InOptional);
      ("bitmap",OutReturnComPtr);
    ],MADontImplement); // 
    ("CreateSharedBitmap",[
      ("This",AThis);
      ("riid",ANone);
      ("data",InInterface "riid");
      ("bitmapProperties",InOptional);
      ("bitmap",OutReturnComPtr);
    ],MANone);
    ("CreateBitmapBrush",[
      ("This",AThis);
      ("bitmap",InComPtr);
      ("bitmapBrushProperties",InOptional);
      ("brushProperties",InOptional);
      ("bitmapBrush",OutReturnComPtr);
    ],MANone);
    ("CreateSolidColorBrush",[
      ("This",AThis);
      ("color",ANone);
      ("brushProperties",InOptional);
      ("solidColorBrush",OutReturnComPtr);
    ],MANone);
    ("CreateGradientStopCollection",[
      ("This",AThis);
      ("gradientStops",InArrayOfSize "gradientStopsCount");
      ("gradientStopsCount",ANone);
      ("colorInterpolationGamma",ANone);
      ("extendMode",ANone);
      ("gradientStopCollection",OutReturnComPtr);
    ],MANone);
    ("CreateLinearGradientBrush",[
      ("This",AThis);
      ("linearGradientBrushProperties",ANone);
      ("brushProperties",InOptional);
      ("gradientStopCollection",InComPtr);
      ("linearGradientBrush",OutReturnComPtr);
    ],MANone);
    ("CreateRadialGradientBrush",[
      ("This",AThis);
      ("radialGradientBrushProperties",ANone);
      ("brushProperties",InOptional);
      ("gradientStopCollection",InComPtr);
      ("radialGradientBrush",OutReturnComPtr);
    ],MANone);
    ("CreateCompatibleRenderTarget",[
      ("This",AThis);
      ("desiredSize",InOptional);
      ("desiredPixelSize",InOptional);
      ("desiredFormat",InOptional);
      ("options",ANone);
      ("bitmapRenderTarget",OutReturnComPtr);
    ],MANone);
    ("CreateLayer",[
      ("This",AThis);
      ("size",InOptional);
      ("layer",OutReturnComPtr);
    ],MANone);
    ("CreateMesh",[
      ("This",AThis);
      ("mesh",OutReturnComPtr);
    ],MANone);
    ("DrawLine",[
      ("This",AThis);
      ("point0",ANone);
      ("point1",ANone);
      ("brush",InComPtr);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
    ],MANone);
    ("DrawRectangle",[
      ("This",AThis);
      ("rect",ANone);
      ("brush",InComPtr);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
    ],MANone);
    ("FillRectangle",[
      ("This",AThis);
      ("rect",ANone);
      ("brush",InComPtr);
    ],MANone);
    ("DrawRoundedRectangle",[
      ("This",AThis);
      ("roundedRect",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillRoundedRectangle",[
      ("This",AThis);
      ("roundedRect",ANone);
      ("brush",ANone);
    ],MANone);
    ("DrawEllipse",[
      ("This",AThis);
      ("ellipse",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillEllipse",[
      ("This",AThis);
      ("ellipse",ANone);
      ("brush",ANone);
    ],MANone);
    ("DrawGeometry",[
      ("This",AThis);
      ("geometry",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillGeometry",[
      ("This",AThis);
      ("geometry",ANone);
      ("brush",ANone);
      ("opacityBrush",ANone);
    ],MANone);
    ("FillMesh",[
      ("This",AThis);
      ("mesh",ANone);
      ("brush",ANone);
    ],MANone);
    ("FillOpacityMask",[
      ("This",AThis);
      ("opacityMask",ANone);
      ("brush",ANone);
      ("content",ANone);
      ("destinationRectangle",ANone);
      ("sourceRectangle",ANone);
    ],MANone);
    ("DrawBitmap",[
      ("This",AThis);
      ("bitmap",ANone);
      ("destinationRectangle",ANone);
      ("opacity",ANone);
      ("interpolationMode",ANone);
      ("sourceRectangle",ANone);
    ],MANone);
    ("DrawText",[
      ("This",AThis);
      ("string", InArrayOfSize "stringLength");
      ("stringLength",ANone);
      ("textFormat",InComPtr);
      ("layoutRect",ANone);
      ("defaultForegroundBrush",InComPtr);
      ("options",ANone);
      ("measuringMode",ANone);
    ],MANone);
    ("DrawTextLayout",[
      ("This",AThis);
      ("origin",ANone);
      ("textLayout",InComPtr);
      ("defaultForegroundBrush",InComPtr);
      ("options",ANone);
    ],MANone);
    ("DrawGlyphRun",[
      ("This",AThis);
      ("baselineOrigin",ANone);
      ("glyphRun",ANone);
      ("foregroundBrush",ANone);
      ("measuringMode",ANone);
    ],MANone);
    ("SetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("GetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("SetAntialiasMode",[
      ("This",AThis);
      ("antialiasMode",ANone);
    ],MANone);
    ("GetAntialiasMode",[
      ("This",AThis);
    ],MANone);
    ("SetTextAntialiasMode",[
      ("This",AThis);
      ("textAntialiasMode",ANone);
    ],MANone);
    ("GetTextAntialiasMode",[
      ("This",AThis);
    ],MANone);
    ("SetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",ANone);
    ],MANone);
    ("GetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",ANone);
    ],MANone);
    ("SetTags",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("GetTags",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("PushLayer",[
      ("This",AThis);
      ("layerParameters",ANone);
      ("layer",ANone);
    ],MANone);
    ("PopLayer",[
      ("This",AThis);
    ],MANone);
    ("Flush",[
      ("This",AThis);
      ("tag1",OutOptional);
      ("tag2",OutOptional);
    ],MANone);
    ("SaveDrawingState",[
      ("This",AThis);
      ("drawingStateBlock",ANone);
    ],MANone);
    ("RestoreDrawingState",[
      ("This",AThis);
      ("drawingStateBlock",ANone);
    ],MANone);
    ("PushAxisAlignedClip",[
      ("This",AThis);
      ("clipRect",ANone);
      ("antialiasMode",ANone);
    ],MANone);
    ("PopAxisAlignedClip",[
      ("This",AThis);
    ],MANone);
    ("Clear",[
      ("This",AThis);
      ("clearColor",ANone);
    ],MANone);
    ("BeginDraw",[
      ("This",AThis);
    ],MANone);
    ("EndDraw",[
      ("This",AThis);
      ("tag1",OutOptional);
      ("tag2",OutOptional);
    ],MANone);
    ("GetPixelFormat",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("SetDpi",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
    ("GetDpi",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
    ("GetSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetPixelSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetMaximumBitmapSize",[
      ("This",AThis);
    ],MANone);
    ("IsSupported",[
      ("This",AThis);
      ("renderTargetProperties",ANone);
    ],MANone);
  ]);
  ("ID2D1ResourceVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetFactory",[
      ("This",AThis);
      ("factory",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1RoundedRectangleGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetRoundedRect",[
      ("This",AThis);
      ("roundedRect",ANone);
    ],MANone);
  ]);
  ("ID2D1SimplifiedGeometrySinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("SetFillMode",[
      ("This",AThis);
      ("fillMode",ANone);
    ],MANone);
    ("SetSegmentFlags",[
      ("This",AThis);
      ("vertexFlags",ANone);
    ],MANone);
    ("BeginFigure",[
      ("This",AThis);
      ("startPoint",ANone);
      ("figureBegin",ANone);
    ],MANone);
    ("AddLines",[
      ("This",AThis);
      ("points",ANone);
      ("pointsCount",ANone);
    ],MANone);
    ("AddBeziers",[
      ("This",AThis);
      ("beziers",ANone);
      ("beziersCount",ANone);
    ],MANone);
    ("EndFigure",[
      ("This",AThis);
      ("figureEnd",ANone);
    ],MANone);
    ("Close",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1SolidColorBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetColor",[
      ("This",AThis);
      ("color",ANone);
    ],MANone);
    ("GetColor",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
  ]);
  ("ID2D1StrokeStyleVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetStartCap",[
      ("This",AThis);
    ],MANone);
    ("GetEndCap",[
      ("This",AThis);
    ],MANone);
    ("GetDashCap",[
      ("This",AThis);
    ],MANone);
    ("GetMiterLimit",[
      ("This",AThis);
    ],MANone);
    ("GetLineJoin",[
      ("This",AThis);
    ],MANone);
    ("GetDashOffset",[
      ("This",AThis);
    ],MANone);
    ("GetDashStyle",[
      ("This",AThis);
    ],MANone);
    ("GetDashesCount",[
      ("This",AThis);
    ],MANone);
    ("GetDashes",[
      ("This",AThis);
      ("dashes",ANone);
      ("dashesCount",ANone);
    ],MANone);
  ]);
  ("ID2D1TessellationSinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("AddTriangles",[
      ("This",AThis);
      ("triangles",ANone);
      ("trianglesCount",ANone);
    ],MANone);
    ("Close",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1TransformedGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetSourceGeometry",[
      ("This",AThis);
      ("sourceGeometry",ANone);
    ],MANone);
    ("GetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
  ]);
 ]

let d2d1_1 = [
  ("ID2D1Bitmap1Vtbl",IAAutogen(Set.ofList []), "ID2D1BitmapVtbl", [
    ("GetColorContext",[
      ("This",AThis);
      ("colorContext",ANone);
    ],MANone);
    ("GetOptions",[
      ("This",AThis);
    ],MANone);
    ("GetSurface",[
      ("This",AThis);
      ("dxgiSurface",ANone);
    ],MANone);
    ("Map",[
      ("This",AThis);
      ("options",ANone);
      ("mappedRect",ANone);
    ],MANone);
    ("Unmap",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1BitmapBrush1Vtbl",IAAutogen(Set.ofList []), "ID2D1BitmapBrushVtbl", [
    ("SetInterpolationMode1",[
      ("This",AThis);
      ("interpolationMode",ANone);
    ],MANone);
    ("GetInterpolationMode1",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1ColorContextVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetColorSpace",[
      ("This",AThis);
    ],MANone);
    ("GetProfileSize",[
      ("This",AThis);
    ],MANone);
    ("GetProfile",[
      ("This",AThis);
      ("profile",ANone);
      ("profileSize",ANone);
    ],MANone);
  ]);
  ("ID2D1CommandListVtbl",IAAutogen(Set.ofList []), "ID2D1ImageVtbl", [
    ("Stream",[
      ("This",AThis);
      ("sink",ANone);
    ],MANone);
    ("Close",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1CommandSinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("BeginDraw",[
      ("This",AThis);
    ],MANone);
    ("EndDraw",[
      ("This",AThis);
    ],MANone);
    ("SetAntialiasMode",[
      ("This",AThis);
      ("antialiasMode",ANone);
    ],MANone);
    ("SetTags",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("SetTextAntialiasMode",[
      ("This",AThis);
      ("textAntialiasMode",ANone);
    ],MANone);
    ("SetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",ANone);
    ],MANone);
    ("SetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("SetPrimitiveBlend",[
      ("This",AThis);
      ("primitiveBlend",ANone);
    ],MANone);
    ("SetUnitMode",[
      ("This",AThis);
      ("unitMode",ANone);
    ],MANone);
    ("Clear",[
      ("This",AThis);
      ("color",ANone);
    ],MANone);
    ("DrawGlyphRun",[
      ("This",AThis);
      ("baselineOrigin",ANone);
      ("glyphRun",ANone);
      ("glyphRunDescription",ANone);
      ("foregroundBrush",ANone);
      ("measuringMode",ANone);
    ],MANone);
    ("DrawLine",[
      ("This",AThis);
      ("point0",ANone);
      ("point1",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("DrawGeometry",[
      ("This",AThis);
      ("geometry",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("DrawRectangle",[
      ("This",AThis);
      ("rect",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("DrawBitmap",[
      ("This",AThis);
      ("bitmap",ANone);
      ("destinationRectangle",ANone);
      ("opacity",ANone);
      ("interpolationMode",ANone);
      ("sourceRectangle",ANone);
      ("perspectiveTransform",ANone);
    ],MANone);
    ("DrawImage",[
      ("This",AThis);
      ("image",ANone);
      ("targetOffset",ANone);
      ("imageRectangle",ANone);
      ("interpolationMode",ANone);
      ("compositeMode",ANone);
    ],MANone);
    ("DrawGdiMetafile",[
      ("This",AThis);
      ("gdiMetafile",ANone);
      ("targetOffset",ANone);
    ],MANone);
    ("FillMesh",[
      ("This",AThis);
      ("mesh",ANone);
      ("brush",ANone);
    ],MANone);
    ("FillOpacityMask",[
      ("This",AThis);
      ("opacityMask",ANone);
      ("brush",ANone);
      ("destinationRectangle",ANone);
      ("sourceRectangle",ANone);
    ],MANone);
    ("FillGeometry",[
      ("This",AThis);
      ("geometry",ANone);
      ("brush",ANone);
      ("opacityBrush",ANone);
    ],MANone);
    ("FillRectangle",[
      ("This",AThis);
      ("rect",ANone);
      ("brush",ANone);
    ],MANone);
    ("PushAxisAlignedClip",[
      ("This",AThis);
      ("clipRect",ANone);
      ("antialiasMode",ANone);
    ],MANone);
    ("PushLayer",[
      ("This",AThis);
      ("layerParameters1",ANone);
      ("layer",ANone);
    ],MANone);
    ("PopAxisAlignedClip",[
      ("This",AThis);
    ],MANone);
    ("PopLayer",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1DeviceContextVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("CreateBitmap",[
      ("This",AThis);
      ("size",ANone);
      ("sourceData",ANone);
      ("pitch",ANone);
      ("bitmapProperties",ANone);
      ("bitmap",ANone);
    ],MANone);
    ("CreateBitmapFromWicBitmap",[
      ("This",AThis);
      ("wicBitmapSource",ANone);
      ("bitmapProperties",ANone);
      ("bitmap",ANone);
    ],MADontImplement);
    ("CreateColorContext",[
      ("This",AThis);
      ("space",ANone);
      ("profile",ANone);
      ("profileSize",ANone);
      ("colorContext",ANone);
    ],MANone);
    ("CreateColorContextFromFilename",[
      ("This",AThis);
      ("filename",ANone);
      ("colorContext",ANone);
    ],MANone);
    ("CreateColorContextFromWicColorContext",[
      ("This",AThis);
      ("wicColorContext",ANone);
      ("colorContext",ANone);
    ],MADontImplement);
    ("CreateBitmapFromDxgiSurface",[
      ("This",AThis);
      ("surface",InComPtr);
      ("bitmapProperties",ANone);
      ("bitmap",OutReturnComPtr);
    ],MANone);
    ("CreateEffect",[
      ("This",AThis);
      ("effectId",ANone);
      ("effect",ANone);
    ],MANone);
    ("CreateGradientStopCollection",[
      ("This",AThis);
      ("straightAlphaGradientStops",ANone);
      ("straightAlphaGradientStopsCount",ANone);
      ("preInterpolationSpace",ANone);
      ("postInterpolationSpace",ANone);
      ("bufferPrecision",ANone);
      ("extendMode",ANone);
      ("colorInterpolationMode",ANone);
      ("gradientStopCollection1",ANone);
    ],MANone);
    ("CreateImageBrush",[
      ("This",AThis);
      ("image",ANone);
      ("imageBrushProperties",ANone);
      ("brushProperties",ANone);
      ("imageBrush",ANone);
    ],MANone);
    ("CreateBitmapBrush",[
      ("This",AThis);
      ("bitmap",ANone);
      ("bitmapBrushProperties",ANone);
      ("brushProperties",ANone);
      ("bitmapBrush",ANone);
    ],MANone);
    ("CreateCommandList",[
      ("This",AThis);
      ("commandList",ANone);
    ],MANone);
    ("IsDxgiFormatSupported",[
      ("This",AThis);
      ("format",ANone);
    ],MANone);
    ("IsBufferPrecisionSupported",[
      ("This",AThis);
      ("bufferPrecision",ANone);
    ],MANone);
    ("GetImageLocalBounds",[
      ("This",AThis);
      ("image",ANone);
      ("localBounds",ANone);
    ],MANone);
    ("GetImageWorldBounds",[
      ("This",AThis);
      ("image",ANone);
      ("worldBounds",ANone);
    ],MANone);
    ("GetGlyphRunWorldBounds",[
      ("This",AThis);
      ("baselineOrigin",ANone);
      ("glyphRun",ANone);
      ("measuringMode",ANone);
      ("bounds",ANone);
    ],MANone);
    ("GetDevice",[
      ("This",AThis);
      ("device",ANone);
    ],MANone);
    ("SetTarget",[
      ("This",AThis);
      ("image",InOptionalComPtr);
    ],MANone);
    ("GetTarget",[
      ("This",AThis);
      ("image",ANone);
    ],MANone);
    ("SetRenderingControls",[
      ("This",AThis);
      ("renderingControls",ANone);
    ],MANone);
    ("GetRenderingControls",[
      ("This",AThis);
      ("renderingControls",ANone);
    ],MANone);
    ("SetPrimitiveBlend",[
      ("This",AThis);
      ("primitiveBlend",ANone);
    ],MANone);
    ("GetPrimitiveBlend",[
      ("This",AThis);
    ],MANone);
    ("SetUnitMode",[
      ("This",AThis);
      ("unitMode",ANone);
    ],MANone);
    ("GetUnitMode",[
      ("This",AThis);
    ],MANone);
    ("DrawGlyphRun",[
      ("This",AThis);
      ("baselineOrigin",ANone);
      ("glyphRun",ANone);
      ("glyphRunDescription",ANone);
      ("foregroundBrush",ANone);
      ("measuringMode",ANone);
    ],MAMangle "DrawGlyphRunDC");
    ("DrawImage",[
      ("This",AThis);
      ("image",ANone);
      ("targetOffset",ANone);
      ("imageRectangle",ANone);
      ("interpolationMode",ANone);
      ("compositeMode",ANone);
    ],MANone);
    ("DrawGdiMetafile",[
      ("This",AThis);
      ("gdiMetafile",ANone);
      ("targetOffset",ANone);
    ],MANone);
    ("DrawBitmap",[
      ("This",AThis);
      ("bitmap",ANone);
      ("destinationRectangle",ANone);
      ("opacity",ANone);
      ("interpolationMode",ANone);
      ("sourceRectangle",ANone);
      ("perspectiveTransform",ANone);
    ],MAMangle "DrawBitmapDC");
    ("PushLayer",[
      ("This",AThis);
      ("layerParameters",ANone);
      ("layer",ANone);
    ],MAMangle "PushLayerDC"); // Overloaded method
    ("InvalidateEffectInputRectangle",[
      ("This",AThis);
      ("effect",ANone);
      ("input",ANone);
      ("inputRectangle",ANone);
    ],MANone);
    ("GetEffectInvalidRectangleCount",[
      ("This",AThis);
      ("effect",ANone);
      ("rectangleCount",ANone);
    ],MANone);
    ("GetEffectInvalidRectangles",[
      ("This",AThis);
      ("effect",ANone);
      ("rectangles",ANone);
      ("rectanglesCount",ANone);
    ],MANone);
    ("GetEffectRequiredInputRectangles",[
      ("This",AThis);
      ("renderEffect",ANone);
      ("renderImageRectangle",ANone);
      ("inputDescriptions",ANone);
      ("requiredInputRects",ANone);
      ("inputCount",ANone);
    ],MANone);
    ("FillOpacityMask",[
      ("This",AThis);
      ("opacityMask",ANone);
      ("brush",ANone);
      ("destinationRectangle",ANone);
      ("sourceRectangle",ANone);
    ],MAMangle "FillOpacityMaskDC");
  ]);
  ("ID2D1DeviceVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("CreateDeviceContext",[
      ("This",AThis);
      ("options",ANone);
      ("deviceContext",OutReturnComPtr);
    ],MANone);
    ("CreatePrintControl",[
      ("This",AThis);
      ("wicFactory",ANone);
      ("documentTarget",ANone);
      ("printControlProperties",ANone);
      ("printControl",ANone);
    ],MADontImplement);
    ("SetMaximumTextureMemory",[
      ("This",AThis);
      ("maximumInBytes",ANone);
    ],MANone);
    ("GetMaximumTextureMemory",[
      ("This",AThis);
    ],MANone);
    ("ClearResources",[
      ("This",AThis);
      ("millisecondsSinceUse",ANone);
    ],MANone);
  ]);
  ("ID2D1DrawingStateBlock1Vtbl",IAAutogen(Set.ofList []), "ID2D1DrawingStateBlockVtbl", [
    ("GetDescription",[
      ("This",AThis);
      ("stateDescription",ANone);
    ],MAMangle "GetDescription1");
    ("SetDescription",[
      ("This",AThis);
      ("stateDescription",ANone);
    ],MAMangle "SetDescription1");
  ]);
  ("ID2D1EffectVtbl",IAAutogen(Set.ofList []), "ID2D1PropertiesVtbl", [
    ("SetInput",[
      ("This",AThis);
      ("index",ANone);
      ("input",ANone);
      ("invalidate",ANone);
    ],MANone);
    ("SetInputCount",[
      ("This",AThis);
      ("inputCount",ANone);
    ],MANone);
    ("GetInput",[
      ("This",AThis);
      ("index",ANone);
      ("input",ANone);
    ],MANone);
    ("GetInputCount",[
      ("This",AThis);
    ],MANone);
    ("GetOutput",[
      ("This",AThis);
      ("outputImage",ANone);
    ],MANone);
  ]);
  ("ID2D1Factory1Vtbl",IAAutogen(Set.ofList []), "ID2D1FactoryVtbl", [
    ("CreateDevice",[
      ("This",AThis);
      ("dxgiDevice",InComPtr);
      ("d2dDevice",OutReturnComPtr);
    ],MANone);
    ("CreateStrokeStyle",[
      ("This",AThis);
      ("strokeStyleProperties",ANone);
      ("dashes",ANone);
      ("dashesCount",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("CreatePathGeometry",[
      ("This",AThis);
      ("pathGeometry",ANone);
    ],MANone);
    ("CreateDrawingStateBlock",[
      ("This",AThis);
      ("drawingStateDescription",ANone);
      ("textRenderingParams",ANone);
      ("drawingStateBlock",ANone);
    ],MANone);
    ("CreateGdiMetafile",[
      ("This",AThis);
      ("metafileStream",ANone);
      ("metafile",ANone);
    ],MANone);
    ("RegisterEffectFromStream",[
      ("This",AThis);
      ("classId",ANone);
      ("propertyXml",ANone);
      ("bindings",ANone);
      ("bindingsCount",ANone);
      ("effectFactory",ANone);
    ],MANone);
    ("RegisterEffectFromString",[
      ("This",AThis);
      ("classId",ANone);
      ("propertyXml",ANone);
      ("bindings",ANone);
      ("bindingsCount",ANone);
      ("effectFactory",ANone);
    ],MANone);
    ("UnregisterEffect",[
      ("This",AThis);
      ("classId",ANone);
    ],MANone);
    ("GetRegisteredEffects",[
      ("This",AThis);
      ("effects",ANone);
      ("effectsCount",ANone);
      ("effectsReturned",ANone);
      ("effectsRegistered",ANone);
    ],MANone);
    ("GetEffectProperties",[
      ("This",AThis);
      ("effectId",ANone);
      ("properties",ANone);
    ],MANone);
  ]);
  ("ID2D1GdiMetafileSinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("ProcessRecord",[
      ("This",AThis);
      ("recordType",ANone);
      ("recordData",ANone);
      ("recordDataSize",ANone);
    ],MANone);
  ]);
  ("ID2D1GdiMetafileVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("Stream",[
      ("This",AThis);
      ("sink",ANone);
    ],MANone);
    ("GetBounds",[
      ("This",AThis);
      ("bounds",ANone);
    ],MANone);
  ]);
  ("ID2D1GradientStopCollection1Vtbl",IAAutogen(Set.ofList []), "ID2D1GradientStopCollectionVtbl", [
    ("GetGradientStops1",[
      ("This",AThis);
      ("gradientStops",ANone);
      ("gradientStopsCount",ANone);
    ],MANone);
    ("GetPreInterpolationSpace",[
      ("This",AThis);
    ],MANone);
    ("GetPostInterpolationSpace",[
      ("This",AThis);
    ],MANone);
    ("GetBufferPrecision",[
      ("This",AThis);
    ],MANone);
    ("GetColorInterpolationMode",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1ImageBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetImage",[
      ("This",AThis);
      ("image",ANone);
    ],MANone);
    ("SetExtendModeX",[
      ("This",AThis);
      ("extendModeX",ANone);
    ],MANone);
    ("SetExtendModeY",[
      ("This",AThis);
      ("extendModeY",ANone);
    ],MANone);
    ("SetInterpolationMode",[
      ("This",AThis);
      ("interpolationMode",ANone);
    ],MANone);
    ("SetSourceRectangle",[
      ("This",AThis);
      ("sourceRectangle",ANone);
    ],MANone);
    ("GetImage",[
      ("This",AThis);
      ("image",ANone);
    ],MANone);
    ("GetExtendModeX",[
      ("This",AThis);
    ],MANone);
    ("GetExtendModeY",[
      ("This",AThis);
    ],MANone);
    ("GetInterpolationMode",[
      ("This",AThis);
    ],MANone);
    ("GetSourceRectangle",[
      ("This",AThis);
      ("sourceRectangle",ANone);
    ],MANone);
  ]);
  ("ID2D1MultithreadVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetMultithreadProtected",[
      ("This",AThis);
    ],MANone);
    ("Enter",[
      ("This",AThis);
    ],MANone);
    ("Leave",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1PathGeometry1Vtbl",IAAutogen(Set.ofList []), "ID2D1PathGeometryVtbl", [
    ("ComputePointAndSegmentAtLength",[
      ("This",AThis);
      ("length",ANone);
      ("startSegment",ANone);
      ("worldTransform",ANone);
      ("flatteningTolerance",ANone);
      ("pointDescription",ANone);
    ],MANone);
  ]);
  ("ID2D1PrintControlVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("AddPage",[
      ("This",AThis);
      ("commandList",ANone);
      ("pageSize",ANone);
      ("pagePrintTicketStream",ANone);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("Close",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1PropertiesVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetPropertyCount",[
      ("This",AThis);
    ],MANone);
    ("GetPropertyName",[
      ("This",AThis);
      ("index",ANone);
      ("name",ANone);
      ("nameCount",ANone);
    ],MANone);
    ("GetPropertyNameLength",[
      ("This",AThis);
      ("index",ANone);
    ],MANone);
    ("GetType",[
      ("This",AThis);
      ("index",ANone);
    ],MANone);
    ("GetPropertyIndex",[
      ("This",AThis);
      ("name",ANone);
    ],MANone);
    ("SetValueByName",[
      ("This",AThis);
      ("name",ANone);
      ("type_",ANone);
      ("data",ANone);
      ("dataSize",ANone);
    ],MANone);
    ("SetValue",[
      ("This",AThis);
      ("index",ANone);
      ("type_",ANone);
      ("data",ANone);
      ("dataSize",ANone);
    ],MANone);
    ("GetValueByName",[
      ("This",AThis);
      ("name",ANone);
      ("type_",ANone);
      ("data",ANone);
      ("dataSize",ANone);
    ],MANone);
    ("GetValue",[
      ("This",AThis);
      ("index",ANone);
      ("type_",ANone);
      ("data",ANone);
      ("dataSize",ANone);
    ],MANone);
    ("GetValueSize",[
      ("This",AThis);
      ("index",ANone);
    ],MANone);
    ("GetSubProperties",[
      ("This",AThis);
      ("index",ANone);
      ("subProperties",ANone);
    ],MANone);
  ]);
  ("ID2D1StrokeStyle1Vtbl",IAAutogen(Set.ofList []), "ID2D1StrokeStyleVtbl", [
    ("GetStrokeTransformType",[
      ("This",AThis);
    ],MANone);
  ]);
  ]

let d2d1_2=[
  ("ID2D1CommandSink1Vtbl",IAManual, "ID2D1CommandSinkVtbl", [
    ("SetPrimitiveBlend1",[
      ("This",AThis);
      ("primitiveBlend",ANone);
    ],MANone);
  ]);
  ("ID2D1Device1Vtbl",IAAutogen(Set.empty), "ID2D1DeviceVtbl", [
    ("GetRenderingPriority",[
      ("This",AThis);
    ],MANone);
    ("SetRenderingPriority",[
      ("This",AThis);
      ("renderingPriority",ANone);
    ],MANone);
    ("CreateDeviceContext",[
      ("This",AThis);
      ("options",ANone);
      ("deviceContext1",OutReturnComPtr);
    ],MAMangle "CreateDeviceContext1");
  ]);
  ("ID2D1DeviceContext1Vtbl",IAAutogen(Set.empty), "ID2D1DeviceContextVtbl", [
    ("CreateFilledGeometryRealization",[
      ("This",AThis);
      ("geometry",ANone);
      ("flatteningTolerance",ANone);
      ("geometryRealization",ANone);
    ],MANone);
    ("CreateStrokedGeometryRealization",[
      ("This",AThis);
      ("geometry",ANone);
      ("flatteningTolerance",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
      ("geometryRealization",ANone);
    ],MANone);
    ("DrawGeometryRealization",[
      ("This",AThis);
      ("geometryRealization",ANone);
      ("brush",ANone);
    ],MANone);
  ]);
  ("ID2D1Factory2Vtbl",IAAutogen(Set.empty), "ID2D1Factory1Vtbl", [
    ("CreateDevice",[
      ("This",AThis);
      ("dxgiDevice",InComPtr);
      ("d2dDevice1",OutReturnComPtr);
    ],MAMangle "CreateDevice2");
  ]);
  ("ID2D1GeometryRealizationVtbl",IAManual, "ID2D1ResourceVtbl", [ ]);
  ]

let d2d1_3 = [
  ("ID2D1CommandSink2Vtbl",IAManual, "ID2D1CommandSink1Vtbl", [
    ("DrawInk",[
      ("This",AThis);
      ("ink",ANone);
      ("brush",ANone);
      ("inkStyle",ANone);
    ],MANone);
    ("DrawGradientMesh",[
      ("This",AThis);
      ("gradientMesh",ANone);
    ],MANone);
    ("DrawGdiMetafile",[
      ("This",AThis);
      ("gdiMetafile",ANone);
      ("destinationRectangle",ANone);
      ("sourceRectangle",ANone);
    ],MANone);
  ]);
  ("ID2D1Device2Vtbl",IAAutogen(Set.empty), "ID2D1Device1Vtbl", [
    ("CreateDeviceContext",[
      ("This",AThis);
      ("options",ANone);
      ("deviceContext2",OutReturnComPtr);
    ],MAMangle "CreateDeviceContext2");
    ("FlushDeviceContexts",[
      ("This",AThis);
      ("bitmap",ANone);
    ],MANone);
    ("GetDxgiDevice",[
      ("This",AThis);
      ("dxgiDevice",ANone);
    ],MANone);
  ]);
  ("ID2D1DeviceContext2Vtbl",IAAutogen(Set.empty), "ID2D1DeviceContext1Vtbl", [
    ("CreateInk",[
      ("This",AThis);
      ("startPoint",ANone);
      ("ink",ANone);
    ],MANone);
    ("CreateInkStyle",[
      ("This",AThis);
      ("inkStyleProperties",ANone);
      ("inkStyle",ANone);
    ],MANone);
    ("CreateGradientMesh",[
      ("This",AThis);
      ("patches",ANone);
      ("patchesCount",ANone);
      ("gradientMesh",ANone);
    ],MANone);
    ("CreateImageSourceFromWic",[
      ("This",AThis);
      ("wicBitmapSource",ANone);
      ("loadingOptions",ANone);
      ("alphaMode",ANone);
      ("imageSource",ANone);
    ],MADontImplement);
    ("CreateLookupTable3D",[
      ("This",AThis);
      ("precision",ANone);
      ("extents",ANone);
      ("data",ANone);
      ("dataCount",ANone);
      ("strides",ANone);
      ("lookupTable",ANone);
    ],MANone);
    ("CreateImageSourceFromDxgi",[
      ("This",AThis);
      ("surfaces",ANone);
      ("surfaceCount",ANone);
      ("colorSpace",ANone);
      ("options",ANone);
      ("imageSource",ANone);
    ],MANone);
    ("GetGradientMeshWorldBounds",[
      ("This",AThis);
      ("gradientMesh",ANone);
      ("pBounds",ANone);
    ],MANone);
    ("DrawInk",[
      ("This",AThis);
      ("ink",ANone);
      ("brush",ANone);
      ("inkStyle",ANone);
    ],MANone);
    ("DrawGradientMesh",[
      ("This",AThis);
      ("gradientMesh",ANone);
    ],MANone);
    ("DrawGdiMetafile",[
      ("This",AThis);
      ("gdiMetafile",ANone);
      ("destinationRectangle",ANone);
      ("sourceRectangle",ANone);
    ],MAMangle "DrawGdiMetafile2");
    ("CreateTransformedImageSource",[
      ("This",AThis);
      ("imageSource",ANone);
      ("properties",ANone);
      ("transformedImageSource",ANone);
    ],MANone);
  ]);
  ("ID2D1Factory3Vtbl",IAAutogen(Set.empty), "ID2D1Factory2Vtbl", [
    ("CreateDevice",[
      ("This",AThis);
      ("dxgiDevice",InComPtr);
      ("d2dDevice2",OutReturnComPtr);
    ],MAMangle "CreateDevice3");
  ]);
  ("ID2D1GdiMetafile1Vtbl",IAManual, "ID2D1GdiMetafileVtbl", [
    ("GetDpi",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
    ("GetSourceBounds",[
      ("This",AThis);
      ("bounds",ANone);
    ],MANone);
  ]);
  ("ID2D1GdiMetafileSink1Vtbl",IAManual, "ID2D1GdiMetafileSinkVtbl", [
    ("ProcessRecord",[
      ("This",AThis);
      ("recordType",ANone);
      ("recordData",ANone);
      ("recordDataSize",ANone);
      ("flags",ANone);
    ],MANone);
  ]);
  ("ID2D1GradientMeshVtbl",IAManual, "ID2D1ResourceVtbl", [
    ("GetPatchCount",[
      ("This",AThis);
    ],MANone);
    ("GetPatches",[
      ("This",AThis);
      ("startIndex",ANone);
      ("patches",ANone);
      ("patchesCount",ANone);
    ],MANone);
  ]);
  ("ID2D1ImageSourceFromWicVtbl",IAManual, "ID2D1ImageSourceVtbl", [
    ("EnsureCached",[
      ("This",AThis);
      ("rectangleToFill",ANone);
    ],MANone);
    ("TrimCache",[
      ("This",AThis);
      ("rectangleToPreserve",ANone);
    ],MANone);
    ("GetSource",[
      ("This",AThis);
      ("wicBitmapSource",ANone);
    ],MANone);
  ]);
  ("ID2D1ImageSourceVtbl",IAManual, "ID2D1ImageVtbl", [
    ("OfferResources",[
      ("This",AThis);
    ],MANone);
    ("TryReclaimResources",[
      ("This",AThis);
      ("resourcesDiscarded",ANone);
    ],MANone);
  ]);
  ("ID2D1InkStyleVtbl",IAManual, "ID2D1ResourceVtbl", [
    ("SetNibTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("GetNibTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("SetNibShape",[
      ("This",AThis);
      ("nibShape",ANone);
    ],MANone);
    ("GetNibShape",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1InkVtbl",IAManual, "ID2D1ResourceVtbl", [
    ("SetStartPoint",[
      ("This",AThis);
      ("startPoint",ANone);
    ],MANone);
    ("GetStartPoint",[
      ("This",AThis);
      ("__ret_val",ANone);
    ],MANone);
    ("AddSegments",[
      ("This",AThis);
      ("segments",ANone);
      ("segmentsCount",ANone);
    ],MANone);
    ("RemoveSegmentsAtEnd",[
      ("This",AThis);
      ("segmentsCount",ANone);
    ],MANone);
    ("SetSegments",[
      ("This",AThis);
      ("startSegment",ANone);
      ("segments",ANone);
      ("segmentsCount",ANone);
    ],MANone);
    ("SetSegmentAtEnd",[
      ("This",AThis);
      ("segment",ANone);
    ],MANone);
    ("GetSegmentCount",[
      ("This",AThis);
    ],MANone);
    ("GetSegments",[
      ("This",AThis);
      ("startSegment",ANone);
      ("segments",ANone);
      ("segmentsCount",ANone);
    ],MANone);
    ("StreamAsGeometry",[
      ("This",AThis);
      ("inkStyle",ANone);
      ("worldTransform",ANone);
      ("flatteningTolerance",ANone);
      ("geometrySink",ANone);
    ],MANone);
    ("GetBounds",[
      ("This",AThis);
      ("inkStyle",ANone);
      ("worldTransform",ANone);
      ("bounds",ANone);
    ],MANone);
  ]);
  ("ID2D1LookupTable3DVtbl",IAManual, "ID2D1ResourceVtbl", [  ]);
  ("ID2D1TransformedImageSourceVtbl",IAManual, "ID2D1ImageVtbl", [
    ("GetSource",[
      ("This",AThis);
      ("imageSource",ANone);
    ],MANone);
    ("GetProperties",[
      ("This",AThis);
      ("properties",ANone);
    ],MANone);
  ]);
  ]
