module annotations_d3d11

open annotations

let d3d11=[
  ("ID3D11AsynchronousVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetDataSize",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID3D11AuthenticatedChannelVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetCertificateSize",[
      ("This",AThis);
      ("pCertificateSize",ANone);
    ],MANone);
    ("GetCertificate",[
      ("This",AThis);
      ("CertificateSize",ANone);
      ("pCertificate",ANone);
    ],MANone);
    ("GetChannelHandle",[
      ("This",AThis);
      ("pChannelHandle",ANone);
    ],MANone);
  ]);
  ("ID3D11BlendStateVtbl",IAAutogen(Set.empty), "ID3D11DeviceChildVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",OutReturn);
    ],MANone);
  ]);
  ("ID3D11BufferVtbl",IAManual, "ID3D11ResourceVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11ClassInstanceVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetClassLinkage",[
      ("This",AThis);
      ("ppLinkage",ANone);
    ],MANone);
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
    ("GetInstanceName",[
      ("This",AThis);
      ("pInstanceName",ANone);
      ("pBufferLength",ANone);
    ],MANone);
    ("GetTypeName",[
      ("This",AThis);
      ("pTypeName",ANone);
      ("pBufferLength",ANone);
    ],MANone);
  ]);
  ("ID3D11ClassLinkageVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetClassInstance",[
      ("This",AThis);
      ("pClassInstanceName",ANone);
      ("InstanceIndex",ANone);
      ("ppInstance",ANone);
    ],MANone);
    ("CreateClassInstance",[
      ("This",AThis);
      ("pClassTypeName",ANone);
      ("ConstantBufferOffset",ANone);
      ("ConstantVectorOffset",ANone);
      ("TextureOffset",ANone);
      ("SamplerOffset",ANone);
      ("ppInstance",ANone);
    ],MANone);
  ]);
  ("ID3D11CommandListVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetContextFlags",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID3D11ComputeShaderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11CounterVtbl",IAManual, "ID3D11AsynchronousVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11CryptoSessionVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetCryptoType",[
      ("This",AThis);
      ("pCryptoType",ANone);
    ],MANone);
    ("GetDecoderProfile",[
      ("This",AThis);
      ("pDecoderProfile",ANone);
    ],MANone);
    ("GetCertificateSize",[
      ("This",AThis);
      ("pCertificateSize",ANone);
    ],MANone);
    ("GetCertificate",[
      ("This",AThis);
      ("CertificateSize",ANone);
      ("pCertificate",ANone);
    ],MANone);
    ("GetCryptoSessionHandle",[
      ("This",AThis);
      ("pCryptoSessionHandle",ANone);
    ],MANone);
  ]);
  ("ID3D11DepthStencilStateVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11DepthStencilViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11DeviceChildVtbl",IAAutogen(Set.empty), "IUnknownVtbl", [
    ("GetDevice",[
      ("This",AThis);
      ("ppDevice",ANone);
    ],MANone);
    ("GetPrivateData",[
      ("This",AThis);
      ("guid",ANone);
      ("pDataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("SetPrivateData",[
      ("This",AThis);
      ("guid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("SetPrivateDataInterface",[
      ("This",AThis);
      ("guid",ANone);
      ("pData",ANone);
    ],MANone);
  ]);
  ("ID3D11DeviceContextVtbl",IAAutogen(Set.empty), "ID3D11DeviceChildVtbl", [
    ("VSSetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("PSSetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("PSSetShader",[
      ("This",AThis);
      ("pPixelShader",ANone);
      ("ppClassInstances",ANone);
      ("NumClassInstances",ANone);
    ],MANone);
    ("PSSetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("VSSetShader",[
      ("This",AThis);
      ("pVertexShader",ANone);
      ("ppClassInstances",ANone);
      ("NumClassInstances",ANone);
    ],MANone);
    ("DrawIndexed",[
      ("This",AThis);
      ("IndexCount",ANone);
      ("StartIndexLocation",ANone);
      ("BaseVertexLocation",ANone);
    ],MANone);
    ("Draw",[
      ("This",AThis);
      ("VertexCount",ANone);
      ("StartVertexLocation",ANone);
    ],MANone);
    ("Map",[
      ("This",AThis);
      ("pResource",ANone);
      ("Subresource",ANone);
      ("MapType",ANone);
      ("MapFlags",ANone);
      ("pMappedResource",ANone);
    ],MANone);
    ("Unmap",[
      ("This",AThis);
      ("pResource",ANone);
      ("Subresource",ANone);
    ],MANone);
    ("PSSetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("IASetInputLayout",[
      ("This",AThis);
      ("pInputLayout",ANone);
    ],MANone);
    ("IASetVertexBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppVertexBuffers",ANone);
      ("pStrides",ANone);
      ("pOffsets",ANone);
    ],MANone);
    ("IASetIndexBuffer",[
      ("This",AThis);
      ("pIndexBuffer",ANone);
      ("Format",ANone);
      ("Offset",ANone);
    ],MANone);
    ("DrawIndexedInstanced",[
      ("This",AThis);
      ("IndexCountPerInstance",ANone);
      ("InstanceCount",ANone);
      ("StartIndexLocation",ANone);
      ("BaseVertexLocation",ANone);
      ("StartInstanceLocation",ANone);
    ],MANone);
    ("DrawInstanced",[
      ("This",AThis);
      ("VertexCountPerInstance",ANone);
      ("InstanceCount",ANone);
      ("StartVertexLocation",ANone);
      ("StartInstanceLocation",ANone);
    ],MANone);
    ("GSSetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("GSSetShader",[
      ("This",AThis);
      ("pShader",ANone);
      ("ppClassInstances",ANone);
      ("NumClassInstances",ANone);
    ],MANone);
    ("IASetPrimitiveTopology",[
      ("This",AThis);
      ("Topology",ANone);
    ],MANone);
    ("VSSetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("VSSetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("Begin",[
      ("This",AThis);
      ("pAsync",ANone);
    ],MANone);
    ("End",[
      ("This",AThis);
      ("pAsync",ANone);
    ],MANone);
    ("GetData",[
      ("This",AThis);
      ("pAsync",ANone);
      ("pData",ANone);
      ("DataSize",ANone);
      ("GetDataFlags",ANone);
    ],MANone);
    ("SetPredication",[
      ("This",AThis);
      ("pPredicate",ANone);
      ("PredicateValue",ANone);
    ],MANone);
    ("GSSetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("GSSetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("OMSetRenderTargets",[
      ("This",AThis);
      ("NumViews",ANone);
      ("ppRenderTargetViews",ANone);
      ("pDepthStencilView",ANone);
    ],MANone);
    ("OMSetRenderTargetsAndUnorderedAccessViews",[
      ("This",AThis);
      ("NumRTVs",ANone);
      ("ppRenderTargetViews",ANone);
      ("pDepthStencilView",ANone);
      ("UAVStartSlot",ANone);
      ("NumUAVs",ANone);
      ("ppUnorderedAccessViews",ANone);
      ("pUAVInitialCounts",ANone);
    ],MANone);
    ("OMSetBlendState",[
      ("This",AThis);
      ("pBlendState",InOptionalComPtr);
      ("BlendFactor",InOptional);
      ("SampleMask",ANone);
    ],MANone);
    ("OMSetDepthStencilState",[
      ("This",AThis);
      ("pDepthStencilState",ANone);
      ("StencilRef",ANone);
    ],MANone);
    ("SOSetTargets",[
      ("This",AThis);
      ("NumBuffers",ANone);
      ("ppSOTargets",ANone);
      ("pOffsets",ANone);
    ],MANone);
    ("DrawAuto",[
      ("This",AThis);
    ],MANone);
    ("DrawIndexedInstancedIndirect",[
      ("This",AThis);
      ("pBufferForArgs",ANone);
      ("AlignedByteOffsetForArgs",ANone);
    ],MANone);
    ("DrawInstancedIndirect",[
      ("This",AThis);
      ("pBufferForArgs",ANone);
      ("AlignedByteOffsetForArgs",ANone);
    ],MANone);
    ("Dispatch",[
      ("This",AThis);
      ("ThreadGroupCountX",ANone);
      ("ThreadGroupCountY",ANone);
      ("ThreadGroupCountZ",ANone);
    ],MANone);
    ("DispatchIndirect",[
      ("This",AThis);
      ("pBufferForArgs",ANone);
      ("AlignedByteOffsetForArgs",ANone);
    ],MANone);
    ("RSSetState",[
      ("This",AThis);
      ("pRasterizerState",ANone);
    ],MANone);
    ("RSSetViewports",[
      ("This",AThis);
      ("NumViewports",ANone);
      ("pViewports",ANone);
    ],MANone);
    ("RSSetScissorRects",[
      ("This",AThis);
      ("NumRects",ANone);
      ("pRects",ANone);
    ],MANone);
    ("CopySubresourceRegion",[
      ("This",AThis);
      ("pDstResource",ANone);
      ("DstSubresource",ANone);
      ("DstX",ANone);
      ("DstY",ANone);
      ("DstZ",ANone);
      ("pSrcResource",ANone);
      ("SrcSubresource",ANone);
      ("pSrcBox",ANone);
    ],MANone);
    ("CopyResource",[
      ("This",AThis);
      ("pDstResource",ANone);
      ("pSrcResource",ANone);
    ],MANone);
    ("UpdateSubresource",[
      ("This",AThis);
      ("pDstResource",ANone);
      ("DstSubresource",ANone);
      ("pDstBox",ANone);
      ("pSrcData",ANone);
      ("SrcRowPitch",ANone);
      ("SrcDepthPitch",ANone);
    ],MANone);
    ("CopyStructureCount",[
      ("This",AThis);
      ("pDstBuffer",ANone);
      ("DstAlignedByteOffset",ANone);
      ("pSrcView",ANone);
    ],MANone);
    ("ClearRenderTargetView",[
      ("This",AThis);
      ("pRenderTargetView",ANone);
      ("ColorRGBA",ANone);
    ],MANone);
    ("ClearUnorderedAccessViewUint",[
      ("This",AThis);
      ("pUnorderedAccessView",ANone);
      ("Values",ANone);
    ],MANone);
    ("ClearUnorderedAccessViewFloat",[
      ("This",AThis);
      ("pUnorderedAccessView",ANone);
      ("Values",ANone);
    ],MANone);
    ("ClearDepthStencilView",[
      ("This",AThis);
      ("pDepthStencilView",ANone);
      ("ClearFlags",ANone);
      ("Depth",ANone);
      ("Stencil",ANone);
    ],MANone);
    ("GenerateMips",[
      ("This",AThis);
      ("pShaderResourceView",ANone);
    ],MANone);
    ("SetResourceMinLOD",[
      ("This",AThis);
      ("pResource",ANone);
      ("MinLOD",ANone);
    ],MANone);
    ("GetResourceMinLOD",[
      ("This",AThis);
      ("pResource",ANone);
    ],MANone);
    ("ResolveSubresource",[
      ("This",AThis);
      ("pDstResource",ANone);
      ("DstSubresource",ANone);
      ("pSrcResource",ANone);
      ("SrcSubresource",ANone);
      ("Format",ANone);
    ],MANone);
    ("ExecuteCommandList",[
      ("This",AThis);
      ("pCommandList",ANone);
      ("RestoreContextState",ANone);
    ],MANone);
    ("HSSetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("HSSetShader",[
      ("This",AThis);
      ("pHullShader",ANone);
      ("ppClassInstances",ANone);
      ("NumClassInstances",ANone);
    ],MANone);
    ("HSSetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("HSSetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("DSSetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("DSSetShader",[
      ("This",AThis);
      ("pDomainShader",ANone);
      ("ppClassInstances",ANone);
      ("NumClassInstances",ANone);
    ],MANone);
    ("DSSetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("DSSetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("CSSetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("CSSetUnorderedAccessViews",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumUAVs",ANone);
      ("ppUnorderedAccessViews",ANone);
      ("pUAVInitialCounts",ANone);
    ],MANone);
    ("CSSetShader",[
      ("This",AThis);
      ("pComputeShader",ANone);
      ("ppClassInstances",ANone);
      ("NumClassInstances",ANone);
    ],MANone);
    ("CSSetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("CSSetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("VSGetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("PSGetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("PSGetShader",[
      ("This",AThis);
      ("ppPixelShader",ANone);
      ("ppClassInstances",ANone);
      ("pNumClassInstances",ANone);
    ],MANone);
    ("PSGetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("VSGetShader",[
      ("This",AThis);
      ("ppVertexShader",ANone);
      ("ppClassInstances",ANone);
      ("pNumClassInstances",ANone);
    ],MANone);
    ("PSGetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("IAGetInputLayout",[
      ("This",AThis);
      ("ppInputLayout",ANone);
    ],MANone);
    ("IAGetVertexBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppVertexBuffers",ANone);
      ("pStrides",ANone);
      ("pOffsets",ANone);
    ],MANone);
    ("IAGetIndexBuffer",[
      ("This",AThis);
      ("pIndexBuffer",ANone);
      ("Format",ANone);
      ("Offset",ANone);
    ],MANone);
    ("GSGetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("GSGetShader",[
      ("This",AThis);
      ("ppGeometryShader",ANone);
      ("ppClassInstances",ANone);
      ("pNumClassInstances",ANone);
    ],MANone);
    ("IAGetPrimitiveTopology",[
      ("This",AThis);
      ("pTopology",ANone);
    ],MANone);
    ("VSGetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("VSGetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("GetPredication",[
      ("This",AThis);
      ("ppPredicate",ANone);
      ("pPredicateValue",ANone);
    ],MANone);
    ("GSGetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("GSGetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("OMGetRenderTargets",[
      ("This",AThis);
      ("NumViews",ANone);
      ("ppRenderTargetViews",ANone);
      ("ppDepthStencilView",ANone);
    ],MANone);
    ("OMGetRenderTargetsAndUnorderedAccessViews",[
      ("This",AThis);
      ("NumRTVs",ANone);
      ("ppRenderTargetViews",ANone);
      ("ppDepthStencilView",ANone);
      ("UAVStartSlot",ANone);
      ("NumUAVs",ANone);
      ("ppUnorderedAccessViews",ANone);
    ],MANone);
    ("OMGetBlendState",[
      ("This",AThis);
      ("ppBlendState",OutReturnComPtr);
      ("BlendFactor",OutOptional);
      ("pSampleMask",OutOptional);
    ],MANone);
    ("OMGetDepthStencilState",[
      ("This",AThis);
      ("ppDepthStencilState",ANone);
      ("pStencilRef",ANone);
    ],MANone);
    ("SOGetTargets",[
      ("This",AThis);
      ("NumBuffers",ANone);
      ("ppSOTargets",ANone);
    ],MANone);
    ("RSGetState",[
      ("This",AThis);
      ("ppRasterizerState",ANone);
    ],MANone);
    ("RSGetViewports",[
      ("This",AThis);
      ("pNumViewports",ANone);
      ("pViewports",ANone);
    ],MANone);
    ("RSGetScissorRects",[
      ("This",AThis);
      ("pNumRects",ANone);
      ("pRects",ANone);
    ],MANone);
    ("HSGetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("HSGetShader",[
      ("This",AThis);
      ("ppHullShader",ANone);
      ("ppClassInstances",ANone);
      ("pNumClassInstances",ANone);
    ],MANone);
    ("HSGetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("HSGetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("DSGetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("DSGetShader",[
      ("This",AThis);
      ("ppDomainShader",ANone);
      ("ppClassInstances",ANone);
      ("pNumClassInstances",ANone);
    ],MANone);
    ("DSGetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("DSGetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("CSGetShaderResources",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumViews",ANone);
      ("ppShaderResourceViews",ANone);
    ],MANone);
    ("CSGetUnorderedAccessViews",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumUAVs",ANone);
      ("ppUnorderedAccessViews",ANone);
    ],MANone);
    ("CSGetShader",[
      ("This",AThis);
      ("ppComputeShader",ANone);
      ("ppClassInstances",ANone);
      ("pNumClassInstances",ANone);
    ],MANone);
    ("CSGetSamplers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumSamplers",ANone);
      ("ppSamplers",ANone);
    ],MANone);
    ("CSGetConstantBuffers",[
      ("This",AThis);
      ("StartSlot",ANone);
      ("NumBuffers",ANone);
      ("ppConstantBuffers",ANone);
    ],MANone);
    ("ClearState",[
      ("This",AThis);
    ],MANone);
    ("Flush",[
      ("This",AThis);
    ],MANone);
    ("GetType",[
      ("This",AThis);
    ],MANone);
    ("GetContextFlags",[
      ("This",AThis);
    ],MANone);
    ("FinishCommandList",[
      ("This",AThis);
      ("RestoreDeferredContextState",ANone);
      ("ppCommandList",ANone);
    ],MANone);
  ]);
  ("ID3D11DeviceVtbl",IAAutogen(Set.empty), "IUnknownVtbl", [
    ("CreateBuffer",[
      ("This",AThis);
      ("pDesc",ANone);
      ("pInitialData",ANone);
      ("ppBuffer",ANone);
    ],MANone);
    ("CreateTexture1D",[
      ("This",AThis);
      ("pDesc",ANone);
      ("pInitialData",ANone);
      ("ppTexture1D",ANone);
    ],MANone);
    ("CreateTexture2D",[
      ("This",AThis);
      ("pDesc",ANone);
      ("pInitialData",ANone);
      ("ppTexture2D",ANone);
    ],MANone);
    ("CreateTexture3D",[
      ("This",AThis);
      ("pDesc",ANone);
      ("pInitialData",ANone);
      ("ppTexture3D",ANone);
    ],MANone);
    ("CreateShaderResourceView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pDesc",ANone);
      ("ppSRView",ANone);
    ],MANone);
    ("CreateUnorderedAccessView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pDesc",ANone);
      ("ppUAView",ANone);
    ],MANone);
    ("CreateRenderTargetView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pDesc",ANone);
      ("ppRTView",ANone);
    ],MANone);
    ("CreateDepthStencilView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pDesc",ANone);
      ("ppDepthStencilView",ANone);
    ],MANone);
    ("CreateInputLayout",[
      ("This",AThis);
      ("pInputElementDescs",ANone);
      ("NumElements",ANone);
      ("pShaderBytecodeWithInputSignature",ANone);
      ("BytecodeLength",ANone);
      ("ppInputLayout",ANone);
    ],MANone);
    ("CreateVertexShader",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pClassLinkage",ANone);
      ("ppVertexShader",ANone);
    ],MANone);
    ("CreateGeometryShader",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pClassLinkage",ANone);
      ("ppGeometryShader",ANone);
    ],MANone);
    ("CreateGeometryShaderWithStreamOutput",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pSODeclaration",ANone);
      ("NumEntries",ANone);
      ("pBufferStrides",ANone);
      ("NumStrides",ANone);
      ("RasterizedStream",ANone);
      ("pClassLinkage",ANone);
      ("ppGeometryShader",ANone);
    ],MANone);
    ("CreatePixelShader",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pClassLinkage",ANone);
      ("ppPixelShader",ANone);
    ],MANone);
    ("CreateHullShader",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pClassLinkage",ANone);
      ("ppHullShader",ANone);
    ],MANone);
    ("CreateDomainShader",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pClassLinkage",ANone);
      ("ppDomainShader",ANone);
    ],MANone);
    ("CreateComputeShader",[
      ("This",AThis);
      ("pShaderBytecode",ANone);
      ("BytecodeLength",ANone);
      ("pClassLinkage",ANone);
      ("ppComputeShader",ANone);
    ],MANone);
    ("CreateClassLinkage",[
      ("This",AThis);
      ("ppLinkage",ANone);
    ],MANone);
    ("CreateBlendState",[
      ("This",AThis);
      ("pBlendStateDesc",ANone);
      ("ppBlendState",ANone);
    ],MANone);
    ("CreateDepthStencilState",[
      ("This",AThis);
      ("pDepthStencilDesc",ANone);
      ("ppDepthStencilState",ANone);
    ],MANone);
    ("CreateRasterizerState",[
      ("This",AThis);
      ("pRasterizerDesc",ANone);
      ("ppRasterizerState",ANone);
    ],MANone);
    ("CreateSamplerState",[
      ("This",AThis);
      ("pSamplerDesc",ANone);
      ("ppSamplerState",ANone);
    ],MANone);
    ("CreateQuery",[
      ("This",AThis);
      ("pQueryDesc",ANone);
      ("ppQuery",ANone);
    ],MANone);
    ("CreatePredicate",[
      ("This",AThis);
      ("pPredicateDesc",ANone);
      ("ppPredicate",ANone);
    ],MANone);
    ("CreateCounter",[
      ("This",AThis);
      ("pCounterDesc",ANone);
      ("ppCounter",ANone);
    ],MANone);
    ("CreateDeferredContext",[
      ("This",AThis);
      ("ContextFlags",ANone);
      ("ppDeferredContext",ANone);
    ],MANone);
    ("OpenSharedResource",[
      ("This",AThis);
      ("hResource",ANone);
      ("ReturnedInterface",ANone);
      ("ppResource",ANone);
    ],MANone);
    ("CheckFormatSupport",[
      ("This",AThis);
      ("Format",ANone);
      ("pFormatSupport",ANone);
    ],MANone);
    ("CheckMultisampleQualityLevels",[
      ("This",AThis);
      ("Format",ANone);
      ("SampleCount",ANone);
      ("pNumQualityLevels",ANone);
    ],MANone);
    ("CheckCounterInfo",[
      ("This",AThis);
      ("pCounterInfo",ANone);
    ],MANone);
    ("CheckCounter",[
      ("This",AThis);
      ("pDesc",ANone);
      ("pType",ANone);
      ("pActiveCounters",ANone);
      ("szName",ANone);
      ("pNameLength",ANone);
      ("szUnits",ANone);
      ("pUnitsLength",ANone);
      ("szDescription",ANone);
      ("pDescriptionLength",ANone);
    ],MANone);
    ("CheckFeatureSupport",[
      ("This",AThis);
      ("Feature",ANone);
      ("pFeatureSupportData",ANone);
      ("FeatureSupportDataSize",ANone);
    ],MANone);
    ("GetPrivateData",[
      ("This",AThis);
      ("guid",ANone);
      ("pDataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("SetPrivateData",[
      ("This",AThis);
      ("guid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("SetPrivateDataInterface",[
      ("This",AThis);
      ("guid",ANone);
      ("pData",ANone);
    ],MANone);
    ("GetFeatureLevel",[
      ("This",AThis);
    ],MANone);
    ("GetCreationFlags",[
      ("This",AThis);
    ],MANone);
    ("GetDeviceRemovedReason",[
      ("This",AThis);
    ],MANone);
    ("GetImmediateContext",[
      ("This",AThis);
      ("ppImmediateContext",ANone);
    ],MANone);
    ("SetExceptionMode",[
      ("This",AThis);
      ("RaiseFlags",ANone);
    ],MANone);
    ("GetExceptionMode",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID3D11DomainShaderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11GeometryShaderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11HullShaderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11InputLayoutVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11PixelShaderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11PredicateVtbl",IAManual, "ID3D11QueryVtbl", [
  ]);
  ("ID3D11QueryVtbl",IAManual, "ID3D11AsynchronousVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11RasterizerStateVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11RenderTargetViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11ResourceVtbl",IAAutogen(Set.empty), "ID3D11DeviceChildVtbl", [
    ("GetType",[
      ("This",AThis);
      ("pResourceDimension",ANone);
    ],MANone);
    ("SetEvictionPriority",[
      ("This",AThis);
      ("EvictionPriority",ANone);
    ],MANone);
    ("GetEvictionPriority",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID3D11SamplerStateVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11ShaderResourceViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11Texture1DVtbl",IAManual, "ID3D11ResourceVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11Texture2DVtbl",IAManual, "ID3D11ResourceVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11Texture3DVtbl",IAManual, "ID3D11ResourceVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11UnorderedAccessViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11VertexShaderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
  ]);
  ("ID3D11VideoContextVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetDecoderBuffer",[
      ("This",AThis);
      ("pDecoder",ANone);
      ("Type",ANone);
      ("pBufferSize",ANone);
      ("ppBuffer",ANone);
    ],MANone);
    ("ReleaseDecoderBuffer",[
      ("This",AThis);
      ("pDecoder",ANone);
      ("Type",ANone);
    ],MANone);
    ("DecoderBeginFrame",[
      ("This",AThis);
      ("pDecoder",ANone);
      ("pView",ANone);
      ("ContentKeySize",ANone);
      ("pContentKey",ANone);
    ],MANone);
    ("DecoderEndFrame",[
      ("This",AThis);
      ("pDecoder",ANone);
    ],MANone);
    ("SubmitDecoderBuffers",[
      ("This",AThis);
      ("pDecoder",ANone);
      ("NumBuffers",ANone);
      ("pBufferDesc",ANone);
    ],MANone);
    ("DecoderExtension",[
      ("This",AThis);
      ("pDecoder",ANone);
      ("pExtensionData",ANone);
    ],MANone);
    ("VideoProcessorSetOutputTargetRect",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("Enable",ANone);
      ("pRect",ANone);
    ],MANone);
    ("VideoProcessorSetOutputBackgroundColor",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("YCbCr",ANone);
      ("pColor",ANone);
    ],MANone);
    ("VideoProcessorSetOutputColorSpace",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pColorSpace",ANone);
    ],MANone);
    ("VideoProcessorSetOutputAlphaFillMode",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("AlphaFillMode",ANone);
      ("StreamIndex",ANone);
    ],MANone);
    ("VideoProcessorSetOutputConstriction",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("Enable",ANone);
      ("Size",ANone);
    ],MANone);
    ("VideoProcessorSetOutputStereoMode",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("Enable",ANone);
    ],MANone);
    ("VideoProcessorSetOutputExtension",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pExtensionGuid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("VideoProcessorGetOutputTargetRect",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("Enabled",ANone);
      ("pRect",ANone);
    ],MANone);
    ("VideoProcessorGetOutputBackgroundColor",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pYCbCr",ANone);
      ("pColor",ANone);
    ],MANone);
    ("VideoProcessorGetOutputColorSpace",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pColorSpace",ANone);
    ],MANone);
    ("VideoProcessorGetOutputAlphaFillMode",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pAlphaFillMode",ANone);
      ("pStreamIndex",ANone);
    ],MANone);
    ("VideoProcessorGetOutputConstriction",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pEnabled",ANone);
      ("pSize",ANone);
    ],MANone);
    ("VideoProcessorGetOutputStereoMode",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pEnabled",ANone);
    ],MANone);
    ("VideoProcessorGetOutputExtension",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pExtensionGuid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("VideoProcessorSetStreamFrameFormat",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("FrameFormat",ANone);
    ],MANone);
    ("VideoProcessorSetStreamColorSpace",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pColorSpace",ANone);
    ],MANone);
    ("VideoProcessorSetStreamOutputRate",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("OutputRate",ANone);
      ("RepeatFrame",ANone);
      ("pCustomRate",ANone);
    ],MANone);
    ("VideoProcessorSetStreamSourceRect",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("pRect",ANone);
    ],MANone);
    ("VideoProcessorSetStreamDestRect",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("pRect",ANone);
    ],MANone);
    ("VideoProcessorSetStreamAlpha",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("Alpha",ANone);
    ],MANone);
    ("VideoProcessorSetStreamPalette",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Count",ANone);
      ("pEntries",ANone);
    ],MANone);
    ("VideoProcessorSetStreamPixelAspectRatio",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("pSourceAspectRatio",ANone);
      ("pDestinationAspectRatio",ANone);
    ],MANone);
    ("VideoProcessorSetStreamLumaKey",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("Lower",ANone);
      ("Upper",ANone);
    ],MANone);
    ("VideoProcessorSetStreamStereoFormat",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("Format",ANone);
      ("LeftViewFrame0",ANone);
      ("BaseViewFrame0",ANone);
      ("FlipMode",ANone);
      ("MonoOffset",ANone);
    ],MANone);
    ("VideoProcessorSetStreamAutoProcessingMode",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
    ],MANone);
    ("VideoProcessorSetStreamFilter",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Filter",ANone);
      ("Enable",ANone);
      ("Level",ANone);
    ],MANone);
    ("VideoProcessorSetStreamExtension",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pExtensionGuid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("VideoProcessorGetStreamFrameFormat",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pFrameFormat",ANone);
    ],MANone);
    ("VideoProcessorGetStreamColorSpace",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pColorSpace",ANone);
    ],MANone);
    ("VideoProcessorGetStreamOutputRate",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pOutputRate",ANone);
      ("pRepeatFrame",ANone);
      ("pCustomRate",ANone);
    ],MANone);
    ("VideoProcessorGetStreamSourceRect",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnabled",ANone);
      ("pRect",ANone);
    ],MANone);
    ("VideoProcessorGetStreamDestRect",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnabled",ANone);
      ("pRect",ANone);
    ],MANone);
    ("VideoProcessorGetStreamAlpha",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnabled",ANone);
      ("pAlpha",ANone);
    ],MANone);
    ("VideoProcessorGetStreamPalette",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Count",ANone);
      ("pEntries",ANone);
    ],MANone);
    ("VideoProcessorGetStreamPixelAspectRatio",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnabled",ANone);
      ("pSourceAspectRatio",ANone);
      ("pDestinationAspectRatio",ANone);
    ],MANone);
    ("VideoProcessorGetStreamLumaKey",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnabled",ANone);
      ("pLower",ANone);
      ("pUpper",ANone);
    ],MANone);
    ("VideoProcessorGetStreamStereoFormat",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnable",ANone);
      ("pFormat",ANone);
      ("pLeftViewFrame0",ANone);
      ("pBaseViewFrame0",ANone);
      ("pFlipMode",ANone);
      ("MonoOffset",ANone);
    ],MANone);
    ("VideoProcessorGetStreamAutoProcessingMode",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnabled",ANone);
    ],MANone);
    ("VideoProcessorGetStreamFilter",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Filter",ANone);
      ("pEnabled",ANone);
      ("pLevel",ANone);
    ],MANone);
    ("VideoProcessorGetStreamExtension",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pExtensionGuid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("VideoProcessorBlt",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("pView",ANone);
      ("OutputFrame",ANone);
      ("StreamCount",ANone);
      ("pStreams",ANone);
    ],MANone);
    ("NegotiateCryptoSessionKeyExchange",[
      ("This",AThis);
      ("pCryptoSession",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("EncryptionBlt",[
      ("This",AThis);
      ("pCryptoSession",ANone);
      ("pSrcSurface",ANone);
      ("pDstSurface",ANone);
      ("IVSize",ANone);
      ("pIV",ANone);
    ],MANone);
    ("DecryptionBlt",[
      ("This",AThis);
      ("pCryptoSession",ANone);
      ("pSrcSurface",ANone);
      ("pDstSurface",ANone);
      ("pEncryptedBlockInfo",ANone);
      ("ContentKeySize",ANone);
      ("pContentKey",ANone);
      ("IVSize",ANone);
      ("pIV",ANone);
    ],MANone);
    ("StartSessionKeyRefresh",[
      ("This",AThis);
      ("pCryptoSession",ANone);
      ("RandomNumberSize",ANone);
      ("pRandomNumber",ANone);
    ],MANone);
    ("FinishSessionKeyRefresh",[
      ("This",AThis);
      ("pCryptoSession",ANone);
    ],MANone);
    ("GetEncryptionBltKey",[
      ("This",AThis);
      ("pCryptoSession",ANone);
      ("KeySize",ANone);
      ("pReadbackKey",ANone);
    ],MANone);
    ("NegotiateAuthenticatedChannelKeyExchange",[
      ("This",AThis);
      ("pChannel",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("QueryAuthenticatedChannel",[
      ("This",AThis);
      ("pChannel",ANone);
      ("InputSize",ANone);
      ("pInput",ANone);
      ("OutputSize",ANone);
      ("pOutput",ANone);
    ],MANone);
    ("ConfigureAuthenticatedChannel",[
      ("This",AThis);
      ("pChannel",ANone);
      ("InputSize",ANone);
      ("pInput",ANone);
      ("pOutput",ANone);
    ],MANone);
    ("VideoProcessorSetStreamRotation",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("Enable",ANone);
      ("Rotation",ANone);
    ],MANone);
    ("VideoProcessorGetStreamRotation",[
      ("This",AThis);
      ("pVideoProcessor",ANone);
      ("StreamIndex",ANone);
      ("pEnable",ANone);
      ("pRotation",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoDecoderOutputViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoDecoderVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetCreationParameters",[
      ("This",AThis);
      ("pVideoDesc",ANone);
      ("pConfig",ANone);
    ],MANone);
    ("GetDriverHandle",[
      ("This",AThis);
      ("pDriverHandle",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoDeviceVtbl",IAManual, "IUnknownVtbl", [
    ("CreateVideoDecoder",[
      ("This",AThis);
      ("pVideoDesc",ANone);
      ("pConfig",ANone);
      ("ppDecoder",ANone);
    ],MANone);
    ("CreateVideoProcessor",[
      ("This",AThis);
      ("pEnum",ANone);
      ("RateConversionIndex",ANone);
      ("ppVideoProcessor",ANone);
    ],MANone);
    ("CreateAuthenticatedChannel",[
      ("This",AThis);
      ("ChannelType",ANone);
      ("ppAuthenticatedChannel",ANone);
    ],MANone);
    ("CreateCryptoSession",[
      ("This",AThis);
      ("pCryptoType",ANone);
      ("pDecoderProfile",ANone);
      ("pKeyExchangeType",ANone);
      ("ppCryptoSession",ANone);
    ],MANone);
    ("CreateVideoDecoderOutputView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pDesc",ANone);
      ("ppVDOVView",ANone);
    ],MANone);
    ("CreateVideoProcessorInputView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pEnum",ANone);
      ("pDesc",ANone);
      ("ppVPIView",ANone);
    ],MANone);
    ("CreateVideoProcessorOutputView",[
      ("This",AThis);
      ("pResource",ANone);
      ("pEnum",ANone);
      ("pDesc",ANone);
      ("ppVPOView",ANone);
    ],MANone);
    ("CreateVideoProcessorEnumerator",[
      ("This",AThis);
      ("pDesc",ANone);
      ("ppEnum",ANone);
    ],MANone);
    ("GetVideoDecoderProfileCount",[
      ("This",AThis);
    ],MANone);
    ("GetVideoDecoderProfile",[
      ("This",AThis);
      ("Index",ANone);
      ("pDecoderProfile",ANone);
    ],MANone);
    ("CheckVideoDecoderFormat",[
      ("This",AThis);
      ("pDecoderProfile",ANone);
      ("Format",ANone);
      ("pSupported",ANone);
    ],MANone);
    ("GetVideoDecoderConfigCount",[
      ("This",AThis);
      ("pDesc",ANone);
      ("pCount",ANone);
    ],MANone);
    ("GetVideoDecoderConfig",[
      ("This",AThis);
      ("pDesc",ANone);
      ("Index",ANone);
      ("pConfig",ANone);
    ],MANone);
    ("GetContentProtectionCaps",[
      ("This",AThis);
      ("pCryptoType",ANone);
      ("pDecoderProfile",ANone);
      ("pCaps",ANone);
    ],MANone);
    ("CheckCryptoKeyExchange",[
      ("This",AThis);
      ("pCryptoType",ANone);
      ("pDecoderProfile",ANone);
      ("Index",ANone);
      ("pKeyExchangeType",ANone);
    ],MANone);
    ("SetPrivateData",[
      ("This",AThis);
      ("guid",ANone);
      ("DataSize",ANone);
      ("pData",ANone);
    ],MANone);
    ("SetPrivateDataInterface",[
      ("This",AThis);
      ("guid",ANone);
      ("pData",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoProcessorEnumeratorVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetVideoProcessorContentDesc",[
      ("This",AThis);
      ("pContentDesc",ANone);
    ],MANone);
    ("CheckVideoProcessorFormat",[
      ("This",AThis);
      ("Format",ANone);
      ("pFlags",ANone);
    ],MANone);
    ("GetVideoProcessorCaps",[
      ("This",AThis);
      ("pCaps",ANone);
    ],MANone);
    ("GetVideoProcessorRateConversionCaps",[
      ("This",AThis);
      ("TypeIndex",ANone);
      ("pCaps",ANone);
    ],MANone);
    ("GetVideoProcessorCustomRate",[
      ("This",AThis);
      ("TypeIndex",ANone);
      ("CustomRateIndex",ANone);
      ("pRate",ANone);
    ],MANone);
    ("GetVideoProcessorFilterRange",[
      ("This",AThis);
      ("Filter",ANone);
      ("pRange",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoProcessorInputViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoProcessorOutputViewVtbl",IAManual, "ID3D11ViewVtbl", [
    ("GetDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
  ]);
  ("ID3D11VideoProcessorVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetContentDesc",[
      ("This",AThis);
      ("pDesc",ANone);
    ],MANone);
    ("GetRateConversionCaps",[
      ("This",AThis);
      ("pCaps",ANone);
    ],MANone);
  ]);
  ("ID3D11ViewVtbl",IAManual, "ID3D11DeviceChildVtbl", [
    ("GetResource",[
      ("This",AThis);
      ("ppResource",ANone);
    ],MANone);
  ]);
  ]
