module annotations_d2d1

open annotations
open custom_impls

let d2d1 =
 [
  ("ID2D1BitmapBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetExtendModeX",[
      ("This",AThis);
      ("extendModeX",ANone);
    ],MANone);
    ("SetExtendModeY",[
      ("This",AThis);
      ("extendModeY",ANone);
    ],MANone);
    ("SetInterpolationMode",[
      ("This",AThis);
      ("interpolationMode",ANone);
    ],MANone);
    ("SetBitmap",[
      ("This",AThis);
      ("bitmap",InComPtr);
    ],MANone);
    ("GetExtendModeX",[
      ("This",AThis);
    ],MANone);
    ("GetExtendModeY",[
      ("This",AThis);
    ],MANone);
    ("GetInterpolationMode",[
      ("This",AThis);
    ],MANone);
    ("GetBitmap",[
      ("This",AThis);
      ("bitmap",OutReturnOptionalComPtr);
    ],MANone);
  ]);
  ("ID2D1BitmapRenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("GetBitmap",[
      ("This",AThis);
      ("bitmap",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1BitmapVtbl",IAAutogen(Set.ofList []), "ID2D1ImageVtbl", [
    ("GetSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetPixelSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetPixelFormat",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetDpi",[
      ("This",AThis);
      ("dpiX",OutReturn);
      ("dpiY",OutReturn);
    ],MANone);
    ("CopyFromBitmap",[
      ("This",AThis);
      ("destPoint",InOptional);
      ("bitmap",InComPtr);
      ("srcRect",InOptional);
    ],MANone);
    ("CopyFromRenderTarget",[
      ("This",AThis);
      ("destPoint",InOptional);
      ("renderTarget",InComPtr);
      ("srcRect",InOptional);
    ],MANone);
    ("CopyFromMemory",[
      ("This",AThis);
      ("dstRect",InOptional);
      ("srcData",ANone);
      ("pitch",ANone);
    ],MAUnsafe);
  ]);
  ("ID2D1BrushVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("SetOpacity",[
      ("This",AThis);
      ("opacity",ANone);
    ],MANone);
    ("SetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("GetOpacity",[
      ("This",AThis);
    ],MANone);
    ("GetTransform",[
      ("This",AThis);
      ("transform",OutReturn);
    ],MANone);
  ]);
  ("ID2D1DCRenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("BindDC",[
      ("This",AThis);
      ("hDC",ANone);
      ("pSubRect",ANone);
    ],MANone);
  ]);
  ("ID2D1DrawingStateBlockVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetDescription",[
      ("This",AThis);
      ("stateDescription",OutReturn);
    ],MANone);
    ("SetDescription",[
      ("This",AThis);
      ("stateDescription",ANone);
    ],MANone);
    ("SetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",InComPtr);
    ],MANone);
    ("GetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1EllipseGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetEllipse",[
      ("This",AThis);
      ("ellipse",OutReturn);
    ],MANone);
  ]);
  ("ID2D1FactoryVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("ReloadSystemMetrics",[
      ("This",AThis);
    ],MANone);
    ("GetDesktopDpi",[
      ("This",AThis);
      ("dpiX",OutReturn);
      ("dpiY",OutReturn);
    ],MANone);
    ("CreateRectangleGeometry",[
      ("This",AThis);
      ("rectangle",ANone);
      ("rectangleGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateRoundedRectangleGeometry",[
      ("This",AThis);
      ("roundedRectangle",ANone);
      ("roundedRectangleGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateEllipseGeometry",[
      ("This",AThis);
      ("ellipse",ANone);
      ("ellipseGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateGeometryGroup",[
      ("This",AThis);
      ("fillMode",ANone);
      ("geometries",InComPtrArrayOfSize "geometriesCount");
      ("geometriesCount",ANone);
      ("geometryGroup",OutReturnComPtr);
    ],MANone);
    ("CreateTransformedGeometry",[
      ("This",AThis);
      ("sourceGeometry",InComPtr);
      ("transform",InOptional);
      ("transformedGeometry",OutReturnComPtr);
    ],MANone);
    ("CreatePathGeometry",[
      ("This",AThis);
      ("pathGeometry",OutReturnComPtr);
    ],MANone);
    ("CreateStrokeStyle",[
      ("This",AThis);
      ("strokeStyleProperties",ANone);
      ("dashes",InOptionalArrayOfSize "dashesCount");
      ("dashesCount",ANone);
      ("strokeStyle",OutReturnComPtr);
    ],MANone);
    ("CreateDrawingStateBlock",[
      ("This",AThis);
      ("drawingStateDescription",InOptional);
      ("textRenderingParams",InOptionalComPtr);
      ("drawingStateBlock",OutReturnComPtr);
    ],MANone);
    ("CreateWicBitmapRenderTarget",[
      ("This",AThis);
      ("target",InComPtr);
      ("renderTargetProperties",InOptional);
      ("renderTarget",OutReturnComPtr);
    ],MANone);
    ("CreateHwndRenderTarget",[
      ("This",AThis);
      ("renderTargetProperties",ANone);
      ("hwndRenderTargetProperties",ANone);
      ("hwndRenderTarget",OutReturnComPtr);
    ],MANone);
    ("CreateDxgiSurfaceRenderTarget",[
      ("This",AThis);
      ("dxgiSurface",InComPtr);
      ("renderTargetProperties",ANone);
      ("renderTarget",OutReturnComPtr);
    ],MANone);
    ("CreateDCRenderTarget",[
      ("This",AThis);
      ("renderTargetProperties",ANone);
      ("dcRenderTarget",OutReturnComPtr);
    ],MANone);
  ]);
  // TODO: add 'private' flag to IAAutogen flags
  ("ID2D1GdiInteropRenderTargetVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetDC",[
      ("This",AThis);
      ("mode",ANone);
      ("hdc",OutReturn);
    ],MANone);
    ("ReleaseDC",[
      ("This",AThis);
      ("update",InOptional);
    ],MANone);
  ]);
  ("ID2D1GeometryGroupVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetFillMode",[
      ("This",AThis);
    ],MANone);
    ("GetSourceGeometryCount",[
      ("This",AThis);
    ],MANone);
    ("GetSourceGeometries",[
      ("This",AThis);
      ("geometries",OutReturnComPtr);
      ("geometriesCount",ANone);
    ], MACustom id2d1geometrygroup_getsourcegeometries); // Handmade implementation
  ]);
  ("ID2D1GeometrySinkVtbl",IAAutogen(Set.ofList []), "ID2D1SimplifiedGeometrySinkVtbl", [
    ("AddLine",[
      ("This",AThis);
      ("point",ANone);
    ],MANone);
    ("AddBezier",[
      ("This",AThis);
      ("bezier",ANone);
    ],MANone);
    ("AddQuadraticBezier",[
      ("This",AThis);
      ("bezier",ANone);
    ],MANone);
    ("AddQuadraticBeziers",[
      ("This",AThis);
      ("beziers",InArrayOfSize "beziersCount");
      ("beziersCount",ANone);
    ],MANone);
    ("AddArc",[
      ("This",AThis);
      ("arc",ANone);
    ],MANone);
  ]);
  ("ID2D1GeometryVtbl", IAAutogen (Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetBounds",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("bounds",OutReturn);
    ],MANone);
    ("GetWidenedBounds",[
      ("This",AThis);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("bounds",OutReturn);
    ],MANone);
    ("StrokeContainsPoint",[
      ("This",AThis);
      ("point",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("contains",OutReturn);
    ],MANone);
    ("FillContainsPoint",[
      ("This",AThis);
      ("point",ANone);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("contains",OutReturn);
    ],MANone);
    ("CompareWithGeometry",[
      ("This",AThis);
      ("inputGeometry",InComPtr);
      ("inputGeometryTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("relation",OutReturn);
    ],MANone);
    ("Simplify",[
      ("This",AThis);
      ("simplificationOption",ANone);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
    ("Tessellate",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("tessellationSink",InComPtr);
    ],MANone);
    ("CombineWithGeometry",[
      ("This",AThis);
      ("inputGeometry",InComPtr);
      ("combineMode",ANone);
      ("inputGeometryTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
    ("Outline",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
    ("ComputeArea",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("area",OutReturn);
    ],MANone);
    ("ComputeLength",[
      ("This",AThis);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("length",OutReturn);
    ],MANone);
    ("ComputePointAtLength",[
      ("This",AThis);
      ("length",ANone);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("point",OutReturn);
      ("unitTangentVector",OutReturn);
    ],MANone);
    ("Widen",[
      ("This",AThis);
      ("strokeWidth",ANone);
      ("strokeStyle",InOptionalComPtr);
      ("worldTransform",InOptional);
      ("flatteningTolerance",ANone);
      ("geometrySink",InComPtr);
    ],MANone);
  ]);
  ("ID2D1GradientStopCollectionVtbl", IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetGradientStopCount",[
      ("This",AThis);
    ],MANone);
    ("GetGradientStops",[
      ("This",AThis);
      ("gradientStops", OutArrayOfSize "gradientStopsCount");
      ("gradientStopsCount", ANone);
    ],MANone);
    ("GetColorInterpolationGamma",[
      ("This",AThis);
    ],MANone);
    ("GetExtendMode",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1HwndRenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1RenderTargetVtbl", [
    ("CheckWindowState",[
      ("This",AThis);
    ],MANone);
    ("Resize",[
      ("This",AThis);
      ("pixelSize",ANone);
    ],MANone);
    ("GetHwnd",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1ImageVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
  ]);
  ("ID2D1LayerVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
  ]);
  ("ID2D1LinearGradientBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetStartPoint",[
      ("This",AThis);
      ("startPoint",ANone);
    ],MANone);
    ("SetEndPoint",[
      ("This",AThis);
      ("endPoint",ANone);
    ],MANone);
    ("GetStartPoint",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetEndPoint",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetGradientStopCollection",[
      ("This",AThis);
      ("gradientStopCollection",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1MeshVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("Open",[
      ("This",AThis);
      ("tessellationSink",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1PathGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("Open",[
      ("This",AThis);
      ("geometrySink",OutReturnComPtr);
    ],MANone);
    ("Stream",[
      ("This",AThis);
      ("geometrySink",InComPtr);
    ],MANone);
    ("GetSegmentCount",[
      ("This",AThis);
      ("count",OutReturn);
    ],MANone);
    ("GetFigureCount",[
      ("This",AThis);
      ("count",OutReturn);
    ],MANone);
  ]);
  ("ID2D1RadialGradientBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetCenter",[
      ("This",AThis);
      ("center",ANone);
    ],MANone);
    ("SetGradientOriginOffset",[
      ("This",AThis);
      ("gradientOriginOffset",ANone);
    ],MANone);
    ("SetRadiusX",[
      ("This",AThis);
      ("radiusX",ANone);
    ],MANone);
    ("SetRadiusY",[
      ("This",AThis);
      ("radiusY",ANone);
    ],MANone);
    ("GetCenter",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetGradientOriginOffset",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetRadiusX",[
      ("This",AThis);
    ],MANone);
    ("GetRadiusY",[
      ("This",AThis);
    ],MANone);
    ("GetGradientStopCollection",[
      ("This",AThis);
      ("gradientStopCollection",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1RectangleGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetRect",[
      ("This",AThis);
      ("rect",OutReturn);
    ],MANone);
  ]);
  ("ID2D1RenderTargetVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("CreateBitmap",[
      ("This",AThis);
      ("size",ANone);
      ("srcData",ANone);
      ("pitch",ANone);
      ("bitmapProperties",ANone);
      ("bitmap",OutReturnComPtr);
    ],MAUnsafe);
    ("CreateBitmapFromWicBitmap",[
      ("This",AThis);
      ("wicBitmapSource",InComPtr);
      ("bitmapProperties",InOptional);
      ("bitmap",OutReturnComPtr);
    ],MANone);
    ("CreateSharedBitmap",[
      ("This",AThis);
      ("riid",ANone);
      ("data",InInterface "riid");
      ("bitmapProperties",InOptional);
      ("bitmap",OutReturnComPtr);
    ],MANone);
    ("CreateBitmapBrush",[
      ("This",AThis);
      ("bitmap",InComPtr);
      ("bitmapBrushProperties",InOptional);
      ("brushProperties",InOptional);
      ("bitmapBrush",OutReturnComPtr);
    ],MANone);
    ("CreateSolidColorBrush",[
      ("This",AThis);
      ("color",ANone);
      ("brushProperties",InOptional);
      ("solidColorBrush",OutReturnComPtr);
    ],MANone);
    ("CreateGradientStopCollection",[
      ("This",AThis);
      ("gradientStops",InArrayOfSize "gradientStopsCount");
      ("gradientStopsCount",ANone);
      ("colorInterpolationGamma",ANone);
      ("extendMode",ANone);
      ("gradientStopCollection",OutReturnComPtr);
    ],MANone);
    ("CreateLinearGradientBrush",[
      ("This",AThis);
      ("linearGradientBrushProperties",ANone);
      ("brushProperties",InOptional);
      ("gradientStopCollection",InComPtr);
      ("linearGradientBrush",OutReturnComPtr);
    ],MANone);
    ("CreateRadialGradientBrush",[
      ("This",AThis);
      ("radialGradientBrushProperties",ANone);
      ("brushProperties",InOptional);
      ("gradientStopCollection",InComPtr);
      ("radialGradientBrush",OutReturnComPtr);
    ],MANone);
    // Continue here
    ("CreateCompatibleRenderTarget",[
      ("This",AThis);
      ("desiredSize",ANone);
      ("desiredPixelSize",ANone);
      ("desiredFormat",ANone);
      ("options",ANone);
      ("bitmapRenderTarget",ANone);
    ],MANone);
    ("CreateLayer",[
      ("This",AThis);
      ("size",ANone);
      ("layer",ANone);
    ],MANone);
    ("CreateMesh",[
      ("This",AThis);
      ("mesh",ANone);
    ],MANone);
    ("DrawLine",[
      ("This",AThis);
      ("point0",ANone);
      ("point1",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("DrawRectangle",[
      ("This",AThis);
      ("rect",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillRectangle",[
      ("This",AThis);
      ("rect",ANone);
      ("brush",ANone);
    ],MANone);
    ("DrawRoundedRectangle",[
      ("This",AThis);
      ("roundedRect",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillRoundedRectangle",[
      ("This",AThis);
      ("roundedRect",ANone);
      ("brush",ANone);
    ],MANone);
    ("DrawEllipse",[
      ("This",AThis);
      ("ellipse",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillEllipse",[
      ("This",AThis);
      ("ellipse",ANone);
      ("brush",ANone);
    ],MANone);
    ("DrawGeometry",[
      ("This",AThis);
      ("geometry",ANone);
      ("brush",ANone);
      ("strokeWidth",ANone);
      ("strokeStyle",ANone);
    ],MANone);
    ("FillGeometry",[
      ("This",AThis);
      ("geometry",ANone);
      ("brush",ANone);
      ("opacityBrush",ANone);
    ],MANone);
    ("FillMesh",[
      ("This",AThis);
      ("mesh",ANone);
      ("brush",ANone);
    ],MANone);
    ("FillOpacityMask",[
      ("This",AThis);
      ("opacityMask",ANone);
      ("brush",ANone);
      ("content",ANone);
      ("destinationRectangle",ANone);
      ("sourceRectangle",ANone);
    ],MANone);
    ("DrawBitmap",[
      ("This",AThis);
      ("bitmap",ANone);
      ("destinationRectangle",ANone);
      ("opacity",ANone);
      ("interpolationMode",ANone);
      ("sourceRectangle",ANone);
    ],MANone);
    ("DrawText",[
      ("This",AThis);
      ("string",ANone);
      ("stringLength",ANone);
      ("textFormat",ANone);
      ("layoutRect",ANone);
      ("defaultForegroundBrush",ANone);
      ("options",ANone);
      ("measuringMode",ANone);
    ],MANone);
    ("DrawTextLayout",[
      ("This",AThis);
      ("origin",ANone);
      ("textLayout",ANone);
      ("defaultForegroundBrush",ANone);
      ("options",ANone);
    ],MANone);
    ("DrawGlyphRun",[
      ("This",AThis);
      ("baselineOrigin",ANone);
      ("glyphRun",ANone);
      ("foregroundBrush",ANone);
      ("measuringMode",ANone);
    ],MANone);
    ("SetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("GetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
    ("SetAntialiasMode",[
      ("This",AThis);
      ("antialiasMode",ANone);
    ],MANone);
    ("GetAntialiasMode",[
      ("This",AThis);
    ],MANone);
    ("SetTextAntialiasMode",[
      ("This",AThis);
      ("textAntialiasMode",ANone);
    ],MANone);
    ("GetTextAntialiasMode",[
      ("This",AThis);
    ],MANone);
    ("SetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",ANone);
    ],MANone);
    ("GetTextRenderingParams",[
      ("This",AThis);
      ("textRenderingParams",ANone);
    ],MANone);
    ("SetTags",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("GetTags",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("PushLayer",[
      ("This",AThis);
      ("layerParameters",ANone);
      ("layer",ANone);
    ],MANone);
    ("PopLayer",[
      ("This",AThis);
    ],MANone);
    ("Flush",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("SaveDrawingState",[
      ("This",AThis);
      ("drawingStateBlock",ANone);
    ],MANone);
    ("RestoreDrawingState",[
      ("This",AThis);
      ("drawingStateBlock",ANone);
    ],MANone);
    ("PushAxisAlignedClip",[
      ("This",AThis);
      ("clipRect",ANone);
      ("antialiasMode",ANone);
    ],MANone);
    ("PopAxisAlignedClip",[
      ("This",AThis);
    ],MANone);
    ("Clear",[
      ("This",AThis);
      ("clearColor",ANone);
    ],MANone);
    ("BeginDraw",[
      ("This",AThis);
    ],MANone);
    ("EndDraw",[
      ("This",AThis);
      ("tag1",ANone);
      ("tag2",ANone);
    ],MANone);
    ("GetPixelFormat",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("SetDpi",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
    ("GetDpi",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
    ("GetSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetPixelSize",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
    ("GetMaximumBitmapSize",[
      ("This",AThis);
    ],MANone);
    ("IsSupported",[
      ("This",AThis);
      ("renderTargetProperties",ANone);
    ],MANone);
  ]);
  ("ID2D1ResourceVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetFactory",[
      ("This",AThis);
      ("factory",OutReturnComPtr);
    ],MANone);
  ]);
  ("ID2D1RoundedRectangleGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetRoundedRect",[
      ("This",AThis);
      ("roundedRect",ANone);
    ],MANone);
  ]);
  ("ID2D1SimplifiedGeometrySinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("SetFillMode",[
      ("This",AThis);
      ("fillMode",ANone);
    ],MANone);
    ("SetSegmentFlags",[
      ("This",AThis);
      ("vertexFlags",ANone);
    ],MANone);
    ("BeginFigure",[
      ("This",AThis);
      ("startPoint",ANone);
      ("figureBegin",ANone);
    ],MANone);
    ("AddLines",[
      ("This",AThis);
      ("points",ANone);
      ("pointsCount",ANone);
    ],MANone);
    ("AddBeziers",[
      ("This",AThis);
      ("beziers",ANone);
      ("beziersCount",ANone);
    ],MANone);
    ("EndFigure",[
      ("This",AThis);
      ("figureEnd",ANone);
    ],MANone);
    ("Close",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1SolidColorBrushVtbl",IAAutogen(Set.ofList []), "ID2D1BrushVtbl", [
    ("SetColor",[
      ("This",AThis);
      ("color",ANone);
    ],MANone);
    ("GetColor",[
      ("This",AThis);
      ("__ret_val",OutReturn);
    ],MANone);
  ]);
  ("ID2D1StrokeStyleVtbl",IAAutogen(Set.ofList []), "ID2D1ResourceVtbl", [
    ("GetStartCap",[
      ("This",AThis);
    ],MANone);
    ("GetEndCap",[
      ("This",AThis);
    ],MANone);
    ("GetDashCap",[
      ("This",AThis);
    ],MANone);
    ("GetMiterLimit",[
      ("This",AThis);
    ],MANone);
    ("GetLineJoin",[
      ("This",AThis);
    ],MANone);
    ("GetDashOffset",[
      ("This",AThis);
    ],MANone);
    ("GetDashStyle",[
      ("This",AThis);
    ],MANone);
    ("GetDashesCount",[
      ("This",AThis);
    ],MANone);
    ("GetDashes",[
      ("This",AThis);
      ("dashes",ANone);
      ("dashesCount",ANone);
    ],MANone);
  ]);
  ("ID2D1TessellationSinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("AddTriangles",[
      ("This",AThis);
      ("triangles",ANone);
      ("trianglesCount",ANone);
    ],MANone);
    ("Close",[
      ("This",AThis);
    ],MANone);
  ]);
  ("ID2D1TransformedGeometryVtbl",IAAutogen(Set.ofList []), "ID2D1GeometryVtbl", [
    ("GetSourceGeometry",[
      ("This",AThis);
      ("sourceGeometry",ANone);
    ],MANone);
    ("GetTransform",[
      ("This",AThis);
      ("transform",ANone);
    ],MANone);
  ]);
 ]
