---
modules:
    - name: d3d12_dxgi
      output-path: ../../dx_dxgi/src/
      include-path: 
        - .\Include\10.0.10586.0\um\
        - .\Include\10.0.10586.0\shared\
        - .\Include\10.0.10586.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - d3d12.h
          - d3d12sdklayers.h
          - d3dcommon.h
          - dxgi.h
          - dxgi1_2.h
          - dxgi1_3.h
          - dxgi1_4.h
      no-winapi-gen: true
      no-enum-conversion: false
    - name: d3d12shader
      output-path: ../../dx_dxgi/src/
      include-path: 
        - .\Include\10.0.10586.0\um\
        - .\Include\10.0.10586.0\shared\
        - .\Include\10.0.10586.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - d3d12shader.h
      no-winapi-gen: false
      no-enum-conversion: false

# modules:
#    - name: dwrite
#      output-path: ../../dx_dxgi/src/
#      include-path: 
#        - ./Include/10.0.10240.0/um/
#        - ./Include/10.0.10240.0/shared/
#        - ./Include/10.0.10240.0/ucrt/
#      precompiled-header: ./PCH/Common_PCH.h
#      headers:
#          - dwrite.h
#      no-winapi-gen: true

