---
modules:
    - name: d3d12_dxgi
      output-path: ../../dx_dxgi/src/
      include-path: 
        - .\Include\10.0.10586.0\um\
        - .\Include\10.0.10586.0\shared\
        - .\Include\10.0.10586.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d3d12.h
          - name: d3d12sdklayers.h
          - name: d3dcommon.h
          - name: dxgi.h
          - name: dxgi1_2.h
            uses:
              - dxgi_safe
          - name: dxgi1_3.h
            uses:
              - dxgi_safe
              - dxgi1_2_safe
          - name: dxgi1_4.h
            uses:
              - dxgi_safe
              - dxgi1_2_safe
              - dxgi1_3_safe
      no-winapi-gen: true
      no-enum-conversion: false
    - name: d3d12shader
      output-path: ../../dx_dxgi/src/
      include-path: 
        - .\Include\10.0.10586.0\um\
        - .\Include\10.0.10586.0\shared\
        - .\Include\10.0.10586.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d3d12shader.h
      no-winapi-gen: false
      no-enum-conversion: false

    - name: d2d1
      output-path: ../../d2d1/src
      include-path: 
        - .\Include\10.0.10586.0\um\
        - .\Include\10.0.10586.0\shared\
        - .\Include\10.0.10586.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d2d1.h
            uses:
              - dwrite_safe
      no-winapi-gen: false
      no-enum-conversion: false
      
    - name: dwrite
      output-path: ../../d2d1/src
      include-path: 
        - .\Include\10.0.10586.0\um\
        - .\Include\10.0.10586.0\shared\
        - .\Include\10.0.10586.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: dwrite.h
      no-winapi-gen: false
      no-enum-conversion: false
      

