---
modules:
    - name: d3d12_dxgi
      output-path: ../../dx_dxgi/src/
      include-path: 
        - ./Include/10.0.10240.0/um/
        - ./Include/10.0.10240.0/shared/
        - ./Include/10.0.10240.0/ucrt/
#      precompiled-header: ./PCH/DXGI_PCH.h
      headers:
          - d3d12.h
      no-winapi-gen: true

# modules:
#    - name: dwrite
#      output-path: ../../dx_dxgi/src/
#      include-path: 
#        - ./Include/10.0.10240.0/um/
#        - ./Include/10.0.10240.0/shared/
#        - ./Include/10.0.10240.0/ucrt/
#      precompiled-header: ./PCH/Common_PCH.h
#      headers:
#          - dwrite.h
#      no-winapi-gen: true

