module annotations_objidl

open annotations

let objidl=[
  ("AsyncIAdviseSink2Vtbl",IAAutogen(Set.ofList []), "AsyncIAdviseSinkVtbl", [
    ("Begin_OnLinkSrcChange",[
      ("This",AThis);
      ("pmk",ANone);
    ],MANone);
    ("Finish_OnLinkSrcChange",[
      ("This",AThis);
    ],MANone);
  ]);
  ("AsyncIAdviseSinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Begin_OnDataChange",[
      ("This",AThis);
      ("pFormatetc",ANone);
      ("pStgmed",ANone);
    ],MANone);
    ("Finish_OnDataChange",[
      ("This",AThis);
    ],MANone);
    ("Begin_OnViewChange",[
      ("This",AThis);
      ("dwAspect",ANone);
      ("lindex",ANone);
    ],MANone);
    ("Finish_OnViewChange",[
      ("This",AThis);
    ],MANone);
    ("Begin_OnRename",[
      ("This",AThis);
      ("pmk",ANone);
    ],MANone);
    ("Finish_OnRename",[
      ("This",AThis);
    ],MANone);
    ("Begin_OnSave",[
      ("This",AThis);
    ],MANone);
    ("Finish_OnSave",[
      ("This",AThis);
    ],MANone);
    ("Begin_OnClose",[
      ("This",AThis);
    ],MANone);
    ("Finish_OnClose",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IAdviseSink2Vtbl",IAAutogen(Set.ofList []), "IAdviseSinkVtbl", [
    ("OnLinkSrcChange",[
      ("This",AThis);
      ("pmk",ANone);
    ],MANone);
  ]);
  ("IAdviseSinkVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("OnDataChange",[
      ("This",AThis);
      ("pFormatetc",ANone);
      ("pStgmed",ANone);
    ],MANone);
    ("OnViewChange",[
      ("This",AThis);
      ("dwAspect",ANone);
      ("lindex",ANone);
    ],MANone);
    ("OnRename",[
      ("This",AThis);
      ("pmk",ANone);
    ],MANone);
    ("OnSave",[
      ("This",AThis);
    ],MANone);
    ("OnClose",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IApartmentShutdownVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("OnUninitialize",[
      ("This",AThis);
      ("ui64ApartmentIdentifier",ANone);
    ],MANone);
  ]);
  ("IBindCtxVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("RegisterObjectBound",[
      ("This",AThis);
      ("punk",ANone);
    ],MANone);
    ("RevokeObjectBound",[
      ("This",AThis);
      ("punk",ANone);
    ],MANone);
    ("ReleaseBoundObjects",[
      ("This",AThis);
    ],MANone);
    ("SetBindOptions",[
      ("This",AThis);
      ("pbindopts",ANone);
    ],MANone);
    ("GetBindOptions",[
      ("This",AThis);
      ("pbindopts",ANone);
    ],MANone);
    ("GetRunningObjectTable",[
      ("This",AThis);
      ("pprot",ANone);
    ],MANone);
    ("RegisterObjectParam",[
      ("This",AThis);
      ("pszKey",ANone);
      ("punk",ANone);
    ],MANone);
    ("GetObjectParam",[
      ("This",AThis);
      ("pszKey",ANone);
      ("ppunk",ANone);
    ],MANone);
    ("EnumObjectParam",[
      ("This",AThis);
      ("ppenum",ANone);
    ],MANone);
    ("RevokeObjectParam",[
      ("This",AThis);
      ("pszKey",ANone);
    ],MANone);
  ]);
  ("IBlockingLockVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Lock",[
      ("This",AThis);
      ("dwTimeout",ANone);
    ],MANone);
    ("Unlock",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IClassActivatorVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetClassObject",[
      ("This",AThis);
      ("rclsid",ANone);
      ("dwClassContext",ANone);
      ("locale",ANone);
      ("riid",ANone);
      ("ppv",ANone);
    ],MANone);
  ]);
  ("IDataAdviseHolderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Advise",[
      ("This",AThis);
      ("pDataObject",ANone);
      ("pFetc",ANone);
      ("advf",ANone);
      ("pAdvise",ANone);
      ("pdwConnection",ANone);
    ],MANone);
    ("Unadvise",[
      ("This",AThis);
      ("dwConnection",ANone);
    ],MANone);
    ("EnumAdvise",[
      ("This",AThis);
      ("ppenumAdvise",ANone);
    ],MANone);
    ("SendOnDataChange",[
      ("This",AThis);
      ("pDataObject",ANone);
      ("dwReserved",ANone);
      ("advf",ANone);
    ],MANone);
  ]);
  ("IDataObjectVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetData",[
      ("This",AThis);
      ("pformatetcIn",ANone);
      ("pmedium",ANone);
    ],MANone);
    ("GetDataHere",[
      ("This",AThis);
      ("pformatetc",ANone);
      ("pmedium",ANone);
    ],MANone);
    ("QueryGetData",[
      ("This",AThis);
      ("pformatetc",ANone);
    ],MANone);
    ("GetCanonicalFormatEtc",[
      ("This",AThis);
      ("pformatectIn",ANone);
      ("pformatetcOut",ANone);
    ],MANone);
    ("SetData",[
      ("This",AThis);
      ("pformatetc",ANone);
      ("pmedium",ANone);
      ("fRelease",ANone);
    ],MANone);
    ("EnumFormatEtc",[
      ("This",AThis);
      ("dwDirection",ANone);
      ("ppenumFormatEtc",ANone);
    ],MANone);
    ("DAdvise",[
      ("This",AThis);
      ("pformatetc",ANone);
      ("advf",ANone);
      ("pAdvSink",ANone);
      ("pdwConnection",ANone);
    ],MANone);
    ("DUnadvise",[
      ("This",AThis);
      ("dwConnection",ANone);
    ],MANone);
    ("EnumDAdvise",[
      ("This",AThis);
      ("ppenumAdvise",ANone);
    ],MANone);
  ]);
  ("IDirectWriterLockVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("WaitForWriteAccess",[
      ("This",AThis);
      ("dwTimeout",ANone);
    ],MANone);
    ("ReleaseWriteAccess",[
      ("This",AThis);
    ],MANone);
    ("HaveWriteAccess",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IDummyHICONIncluderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Dummy",[
      ("This",AThis);
      ("h1",ANone);
      ("h2",ANone);
    ],MANone);
  ]);
  ("IEnumFORMATETCVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Next",[
      ("This",AThis);
      ("celt",ANone);
      ("rgelt",ANone);
      ("pceltFetched",ANone);
    ],MANone);
    ("Skip",[
      ("This",AThis);
      ("celt",ANone);
    ],MANone);
    ("Reset",[
      ("This",AThis);
    ],MANone);
    ("Clone",[
      ("This",AThis);
      ("ppenum",ANone);
    ],MANone);
  ]);
  ("IEnumMonikerVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Next",[
      ("This",AThis);
      ("celt",ANone);
      ("rgelt",ANone);
      ("pceltFetched",ANone);
    ],MANone);
    ("Skip",[
      ("This",AThis);
      ("celt",ANone);
    ],MANone);
    ("Reset",[
      ("This",AThis);
    ],MANone);
    ("Clone",[
      ("This",AThis);
      ("ppenum",ANone);
    ],MANone);
  ]);
  ("IEnumSTATDATAVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Next",[
      ("This",AThis);
      ("celt",ANone);
      ("rgelt",ANone);
      ("pceltFetched",ANone);
    ],MANone);
    ("Skip",[
      ("This",AThis);
      ("celt",ANone);
    ],MANone);
    ("Reset",[
      ("This",AThis);
    ],MANone);
    ("Clone",[
      ("This",AThis);
      ("ppenum",ANone);
    ],MANone);
  ]);
  ("IEnumSTATSTGVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Next",[
      ("This",AThis);
      ("celt",ANone);
      ("rgelt",ANone);
      ("pceltFetched",ANone);
    ],MANone);
    ("Skip",[
      ("This",AThis);
      ("celt",ANone);
    ],MANone);
    ("Reset",[
      ("This",AThis);
    ],MANone);
    ("Clone",[
      ("This",AThis);
      ("ppenum",ANone);
    ],MANone);
  ]);
  ("IFillLockBytesVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("FillAppend",[
      ("This",AThis);
      ("pv",ANone);
      ("cb",ANone);
      ("pcbWritten",ANone);
    ],MANone);
    ("FillAt",[
      ("This",AThis);
      ("ulOffset",ANone);
      ("pv",ANone);
      ("cb",ANone);
      ("pcbWritten",ANone);
    ],MANone);
    ("SetFillSize",[
      ("This",AThis);
      ("ulSize",ANone);
    ],MANone);
    ("Terminate",[
      ("This",AThis);
      ("bCanceled",ANone);
    ],MANone);
  ]);
  ("IForegroundTransferVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("AllowForegroundTransfer",[
      ("This",AThis);
      ("lpvReserved",ANone);
    ],MANone);
  ]);
  ("IInitializeSpyVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("PreInitialize",[
      ("This",AThis);
      ("dwCoInit",ANone);
      ("dwCurThreadAptRefs",ANone);
    ],MANone);
    ("PostInitialize",[
      ("This",AThis);
      ("hrCoInit",ANone);
      ("dwCoInit",ANone);
      ("dwNewThreadAptRefs",ANone);
    ],MANone);
    ("PreUninitialize",[
      ("This",AThis);
      ("dwCurThreadAptRefs",ANone);
    ],MANone);
    ("PostUninitialize",[
      ("This",AThis);
      ("dwNewThreadAptRefs",ANone);
    ],MANone);
  ]);
  ("ILayoutStorageVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("LayoutScript",[
      ("This",AThis);
      ("pStorageLayout",ANone);
      ("nEntries",ANone);
      ("glfInterleavedFlag",ANone);
    ],MANone);
    ("BeginMonitor",[
      ("This",AThis);
    ],MANone);
    ("EndMonitor",[
      ("This",AThis);
    ],MANone);
    ("ReLayoutDocfile",[
      ("This",AThis);
      ("pwcsNewDfName",ANone);
    ],MANone);
    ("ReLayoutDocfileOnILockBytes",[
      ("This",AThis);
      ("pILockBytes",ANone);
    ],MANone);
  ]);
  ("ILockBytesVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("ReadAt",[
      ("This",AThis);
      ("ulOffset",ANone);
      ("pv",ANone);
      ("cb",ANone);
      ("pcbRead",ANone);
    ],MANone);
    ("WriteAt",[
      ("This",AThis);
      ("ulOffset",ANone);
      ("pv",ANone);
      ("cb",ANone);
      ("pcbWritten",ANone);
    ],MANone);
    ("Flush",[
      ("This",AThis);
    ],MANone);
    ("SetSize",[
      ("This",AThis);
      ("cb",ANone);
    ],MANone);
    ("LockRegion",[
      ("This",AThis);
      ("libOffset",ANone);
      ("cb",ANone);
      ("dwLockType",ANone);
    ],MANone);
    ("UnlockRegion",[
      ("This",AThis);
      ("libOffset",ANone);
      ("cb",ANone);
      ("dwLockType",ANone);
    ],MANone);
    ("Stat",[
      ("This",AThis);
      ("pstatstg",ANone);
      ("grfStatFlag",ANone);
    ],MANone);
  ]);
  ("IMallocSpyVtbl",IAManual, "IUnknownVtbl", [
    ("PreAlloc",[
      ("This",AThis);
      ("cbRequest",ANone);
    ],MANone);
    ("PostAlloc",[
      ("This",AThis);
      ("pActual",ANone);
    ],MANone);
    ("PreFree",[
      ("This",AThis);
      ("pRequest",ANone);
      ("fSpyed",ANone);
    ],MANone);
    ("PostFree",[
      ("This",AThis);
      ("fSpyed",ANone);
    ],MANone);
    ("PreRealloc",[
      ("This",AThis);
      ("pRequest",ANone);
      ("cbRequest",ANone);
      ("ppNewRequest",ANone);
      ("fSpyed",ANone);
    ],MANone);
    ("PostRealloc",[
      ("This",AThis);
      ("pActual",ANone);
      ("fSpyed",ANone);
    ],MANone);
    ("PreGetSize",[
      ("This",AThis);
      ("pRequest",ANone);
      ("fSpyed",ANone);
    ],MANone);
    ("PostGetSize",[
      ("This",AThis);
      ("cbActual",ANone);
      ("fSpyed",ANone);
    ],MANone);
    ("PreDidAlloc",[
      ("This",AThis);
      ("pRequest",ANone);
      ("fSpyed",ANone);
    ],MANone);
    ("PostDidAlloc",[
      ("This",AThis);
      ("pRequest",ANone);
      ("fSpyed",ANone);
      ("fActual",ANone);
    ],MANone);
    ("PreHeapMinimize",[
      ("This",AThis);
    ],MANone);
    ("PostHeapMinimize",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IMessageFilterVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("HandleInComingCall",[
      ("This",AThis);
      ("dwCallType",ANone);
      ("htaskCaller",ANone);
      ("dwTickCount",ANone);
      ("lpInterfaceInfo",ANone);
    ],MANone);
    ("RetryRejectedCall",[
      ("This",AThis);
      ("htaskCallee",ANone);
      ("dwTickCount",ANone);
      ("dwRejectType",ANone);
    ],MANone);
    ("MessagePending",[
      ("This",AThis);
      ("htaskCallee",ANone);
      ("dwTickCount",ANone);
      ("dwPendingType",ANone);
    ],MANone);
  ]);
  ("IMonikerVtbl",IAAutogen(Set.ofList []), "IPersistStreamVtbl", [
    ("BindToObject",[
      ("This",AThis);
      ("pbc",ANone);
      ("pmkToLeft",ANone);
      ("riidResult",ANone);
      ("ppvResult",ANone);
    ],MANone);
    ("BindToStorage",[
      ("This",AThis);
      ("pbc",ANone);
      ("pmkToLeft",ANone);
      ("riid",ANone);
      ("ppvObj",ANone);
    ],MANone);
    ("Reduce",[
      ("This",AThis);
      ("pbc",ANone);
      ("dwReduceHowFar",ANone);
      ("ppmkToLeft",ANone);
      ("ppmkReduced",ANone);
    ],MANone);
    ("ComposeWith",[
      ("This",AThis);
      ("pmkRight",ANone);
      ("fOnlyIfNotGeneric",ANone);
      ("ppmkComposite",ANone);
    ],MANone);
    ("Enum",[
      ("This",AThis);
      ("fForward",ANone);
      ("ppenumMoniker",ANone);
    ],MANone);
    ("IsEqual",[
      ("This",AThis);
      ("pmkOtherMoniker",ANone);
    ],MANone);
    ("Hash",[
      ("This",AThis);
      ("pdwHash",ANone);
    ],MANone);
    ("IsRunning",[
      ("This",AThis);
      ("pbc",ANone);
      ("pmkToLeft",ANone);
      ("pmkNewlyRunning",ANone);
    ],MANone);
    ("GetTimeOfLastChange",[
      ("This",AThis);
      ("pbc",ANone);
      ("pmkToLeft",ANone);
      ("pFileTime",ANone);
    ],MANone);
    ("Inverse",[
      ("This",AThis);
      ("ppmk",ANone);
    ],MANone);
    ("CommonPrefixWith",[
      ("This",AThis);
      ("pmkOther",ANone);
      ("ppmkPrefix",ANone);
    ],MANone);
    ("RelativePathTo",[
      ("This",AThis);
      ("pmkOther",ANone);
      ("ppmkRelPath",ANone);
    ],MANone);
    ("GetDisplayName",[
      ("This",AThis);
      ("pbc",ANone);
      ("pmkToLeft",ANone);
      ("ppszDisplayName",ANone);
    ],MANone);
    ("ParseDisplayName",[
      ("This",AThis);
      ("pbc",ANone);
      ("pmkToLeft",ANone);
      ("pszDisplayName",ANone);
      ("pchEaten",ANone);
      ("ppmkOut",ANone);
    ],MANone);
    ("IsSystemMoniker",[
      ("This",AThis);
      ("pdwMksys",ANone);
    ],MANone);
  ]);
  ("IOplockStorageVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("CreateStorageEx",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("grfMode",ANone);
      ("stgfmt",ANone);
      ("grfAttrs",ANone);
      ("riid",ANone);
      ("ppstgOpen",ANone);
    ],MANone);
    ("OpenStorageEx",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("grfMode",ANone);
      ("stgfmt",ANone);
      ("grfAttrs",ANone);
      ("riid",ANone);
      ("ppstgOpen",ANone);
    ],MANone);
  ]);
  ("IPersistFileVtbl",IAAutogen(Set.ofList []), "IPersistVtbl", [
    ("IsDirty",[
      ("This",AThis);
    ],MANone);
    ("Load",[
      ("This",AThis);
      ("pszFileName",ANone);
      ("dwMode",ANone);
    ],MANone);
    ("Save",[
      ("This",AThis);
      ("pszFileName",ANone);
      ("fRemember",ANone);
    ],MANone);
    ("SaveCompleted",[
      ("This",AThis);
      ("pszFileName",ANone);
    ],MANone);
    ("GetCurFile",[
      ("This",AThis);
      ("ppszFileName",ANone);
    ],MANone);
  ]);
  ("IPersistStorageVtbl",IAAutogen(Set.ofList []), "IPersistVtbl", [
    ("IsDirty",[
      ("This",AThis);
    ],MANone);
    ("InitNew",[
      ("This",AThis);
      ("pStg",ANone);
    ],MANone);
    ("Load",[
      ("This",AThis);
      ("pStg",ANone);
    ],MANone);
    ("Save",[
      ("This",AThis);
      ("pStgSave",ANone);
      ("fSameAsLoad",ANone);
    ],MANone);
    ("SaveCompleted",[
      ("This",AThis);
      ("pStgNew",ANone);
    ],MANone);
    ("HandsOffStorage",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IPersistStreamVtbl",IAAutogen(Set.ofList []), "IPersistVtbl", [
    ("IsDirty",[
      ("This",AThis);
    ],MANone);
    ("Load",[
      ("This",AThis);
      ("pStm",ANone);
    ],MANone);
    ("Save",[
      ("This",AThis);
      ("pStm",ANone);
      ("fClearDirty",ANone);
    ],MANone);
    ("GetSizeMax",[
      ("This",AThis);
      ("pcbSize",ANone);
    ],MANone);
  ]);
  ("IPersistVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetClassID",[
      ("This",AThis);
      ("pClassID",ANone);
    ],MANone);
  ]);
  ("IProcessLockVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("AddRefOnProcess",[
      ("This",AThis);
    ],MANone);
    ("ReleaseRefOnProcess",[
      ("This",AThis);
    ],MANone);
  ]);
  ("IProgressNotifyVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("OnProgress",[
      ("This",AThis);
      ("dwProgressCurrent",ANone);
      ("dwProgressMaximum",ANone);
      ("fAccurate",ANone);
      ("fOwner",ANone);
    ],MANone);
  ]);
  ("IROTDataVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetComparisonData",[
      ("This",AThis);
      ("pbData",ANone);
      ("cbMax",ANone);
      ("pcbData",ANone);
    ],MANone);
  ]);
  ("IRootStorageVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("SwitchToFile",[
      ("This",AThis);
      ("pszFile",ANone);
    ],MANone);
  ]);
  ("IRunnableObjectVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetRunningClass",[
      ("This",AThis);
      ("lpClsid",ANone);
    ],MANone);
    ("Run",[
      ("This",AThis);
      ("pbc",ANone);
    ],MANone);
    ("IsRunning",[
      ("This",AThis);
    ],MANone);
    ("LockRunning",[
      ("This",AThis);
      ("fLock",ANone);
      ("fLastUnlockCloses",ANone);
    ],MANone);
    ("SetContainedObject",[
      ("This",AThis);
      ("fContained",ANone);
    ],MANone);
  ]);
  ("IRunningObjectTableVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Register",[
      ("This",AThis);
      ("grfFlags",ANone);
      ("punkObject",ANone);
      ("pmkObjectName",ANone);
      ("pdwRegister",ANone);
    ],MANone);
    ("Revoke",[
      ("This",AThis);
      ("dwRegister",ANone);
    ],MANone);
    ("IsRunning",[
      ("This",AThis);
      ("pmkObjectName",ANone);
    ],MANone);
    ("GetObjectA",[
      ("This",AThis);
      ("pmkObjectName",ANone);
      ("ppunkObject",ANone);
    ],MANone);
    ("NoteChangeTime",[
      ("This",AThis);
      ("dwRegister",ANone);
      ("pfiletime",ANone);
    ],MANone);
    ("GetTimeOfLastChange",[
      ("This",AThis);
      ("pmkObjectName",ANone);
      ("pfiletime",ANone);
    ],MANone);
    ("EnumRunning",[
      ("This",AThis);
      ("ppenumMoniker",ANone);
    ],MANone);
  ]);
  ("IStorageVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("CreateStream",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("grfMode",ANone);
      ("reserved1",ANone);
      ("reserved2",ANone);
      ("ppstm",ANone);
    ],MANone);
    ("OpenStream",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("reserved1",ANone);
      ("grfMode",ANone);
      ("reserved2",ANone);
      ("ppstm",ANone);
    ],MANone);
    ("CreateStorage",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("grfMode",ANone);
      ("reserved1",ANone);
      ("reserved2",ANone);
      ("ppstg",ANone);
    ],MANone);
    ("OpenStorage",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("pstgPriority",ANone);
      ("grfMode",ANone);
      ("snbExclude",ANone);
      ("reserved",ANone);
      ("ppstg",ANone);
    ],MANone);
    ("CopyTo",[
      ("This",AThis);
      ("ciidExclude",ANone);
      ("rgiidExclude",ANone);
      ("snbExclude",ANone);
      ("pstgDest",ANone);
    ],MANone);
    ("MoveElementTo",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("pstgDest",ANone);
      ("pwcsNewName",ANone);
      ("grfFlags",ANone);
    ],MANone);
    ("Commit",[
      ("This",AThis);
      ("grfCommitFlags",ANone);
    ],MANone);
    ("Revert",[
      ("This",AThis);
    ],MANone);
    ("EnumElements",[
      ("This",AThis);
      ("reserved1",ANone);
      ("reserved2",ANone);
      ("reserved3",ANone);
      ("ppenum",ANone);
    ],MANone);
    ("DestroyElement",[
      ("This",AThis);
      ("pwcsName",ANone);
    ],MANone);
    ("RenameElement",[
      ("This",AThis);
      ("pwcsOldName",ANone);
      ("pwcsNewName",ANone);
    ],MANone);
    ("SetElementTimes",[
      ("This",AThis);
      ("pwcsName",ANone);
      ("pctime",ANone);
      ("patime",ANone);
      ("pmtime",ANone);
    ],MANone);
    ("SetClass",[
      ("This",AThis);
      ("clsid",ANone);
    ],MANone);
    ("SetStateBits",[
      ("This",AThis);
      ("grfStateBits",ANone);
      ("grfMask",ANone);
    ],MANone);
    ("Stat",[
      ("This",AThis);
      ("pstatstg",ANone);
      ("grfStatFlag",ANone);
    ],MANone);
  ]);
  ("ISurrogateServiceVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Init",[
      ("This",AThis);
      ("rguidProcessID",ANone);
      ("pProcessLock",ANone);
      ("pfApplicationAware",ANone);
    ],MANone);
    ("ApplicationLaunch",[
      ("This",AThis);
      ("rguidApplID",ANone);
      ("appType",ANone);
    ],MANone);
    ("ApplicationFree",[
      ("This",AThis);
      ("rguidApplID",ANone);
    ],MANone);
    ("CatalogRefresh",[
      ("This",AThis);
      ("ulReserved",ANone);
    ],MANone);
    ("ProcessShutdown",[
      ("This",AThis);
      ("shutdownType",ANone);
    ],MANone);
  ]);
  ("IThumbnailExtractorVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("ExtractThumbnail",[
      ("This",AThis);
      ("pStg",ANone);
      ("ulLength",ANone);
      ("ulHeight",ANone);
      ("pulOutputLength",ANone);
      ("pulOutputHeight",ANone);
      ("phOutputBitmap",ANone);
    ],MANone);
    ("OnFileUpdated",[
      ("This",AThis);
      ("pStg",ANone);
    ],MANone);
  ]);
  ("ITimeAndNoticeControlVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("SuppressChanges",[
      ("This",AThis);
      ("res1",ANone);
      ("res2",ANone);
    ],MANone);
  ]);
  ("IUrlMonVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("AsyncGetClassBits",[
      ("This",AThis);
      ("rclsid",ANone);
      ("pszTYPE",ANone);
      ("pszExt",ANone);
      ("dwFileVersionMS",ANone);
      ("dwFileVersionLS",ANone);
      ("pszCodeBase",ANone);
      ("pbc",ANone);
      ("dwClassContext",ANone);
      ("riid",ANone);
      ("flags",ANone);
    ],MANone);
  ]);
  ]
