module annotations_wincodec

open annotations

let wincodec=[
  ("IWICBitmapClipperVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pISource",ANone);
      ("prc",ANone);
    ],MANone);
  ]);
  ("IWICBitmapCodecInfoVtbl",IAAutogen(Set.ofList []), "IWICComponentInfoVtbl", [
    ("GetContainerFormat",[
      ("This",AThis);
      ("pguidContainerFormat",ANone);
    ],MANone);
    ("GetPixelFormats",[
      ("This",AThis);
      ("cFormats",ANone);
      ("pguidPixelFormats",ANone);
      ("pcActual",ANone);
    ],MANone);
    ("GetColorManagementVersion",[
      ("This",AThis);
      ("cchColorManagementVersion",ANone);
      ("wzColorManagementVersion",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetDeviceManufacturer",[
      ("This",AThis);
      ("cchDeviceManufacturer",ANone);
      ("wzDeviceManufacturer",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetDeviceModels",[
      ("This",AThis);
      ("cchDeviceModels",ANone);
      ("wzDeviceModels",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetMimeTypes",[
      ("This",AThis);
      ("cchMimeTypes",ANone);
      ("wzMimeTypes",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetFileExtensions",[
      ("This",AThis);
      ("cchFileExtensions",ANone);
      ("wzFileExtensions",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("DoesSupportAnimation",[
      ("This",AThis);
      ("pfSupportAnimation",ANone);
    ],MANone);
    ("DoesSupportChromakey",[
      ("This",AThis);
      ("pfSupportChromakey",ANone);
    ],MANone);
    ("DoesSupportLossless",[
      ("This",AThis);
      ("pfSupportLossless",ANone);
    ],MANone);
    ("DoesSupportMultiframe",[
      ("This",AThis);
      ("pfSupportMultiframe",ANone);
    ],MANone);
    ("MatchesMimeType",[
      ("This",AThis);
      ("wzMimeType",ANone);
      ("pfMatches",ANone);
    ],MANone);
  ]);
  ("IWICBitmapCodecProgressNotificationVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("RegisterProgressNotification",[
      ("This",AThis);
      ("pfnProgressNotification",ANone);
      ("pvData",ANone);
      ("dwProgressFlags",ANone);
    ],MANone);
  ]);
  ("IWICBitmapDecoderInfoVtbl",IAAutogen(Set.ofList []), "IWICBitmapCodecInfoVtbl", [
    ("GetPatterns",[
      ("This",AThis);
      ("cbSizePatterns",ANone);
      ("pPatterns",ANone);
      ("pcPatterns",ANone);
      ("pcbPatternsActual",ANone);
    ],MANone);
    ("MatchesPattern",[
      ("This",AThis);
      ("pIStream",ANone);
      ("pfMatches",ANone);
    ],MANone);
    ("CreateInstance",[
      ("This",AThis);
      ("ppIBitmapDecoder",ANone);
    ],MANone);
  ]);
  ("IWICBitmapDecoderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("QueryCapability",[
      ("This",AThis);
      ("pIStream",ANone);
      ("pdwCapability",ANone);
    ],MANone);
    ("Initialize",[
      ("This",AThis);
      ("pIStream",ANone);
      ("cacheOptions",ANone);
    ],MANone);
    ("GetContainerFormat",[
      ("This",AThis);
      ("pguidContainerFormat",ANone);
    ],MANone);
    ("GetDecoderInfo",[
      ("This",AThis);
      ("ppIDecoderInfo",ANone);
    ],MANone);
    ("CopyPalette",[
      ("This",AThis);
      ("pIPalette",ANone);
    ],MANone);
    ("GetMetadataQueryReader",[
      ("This",AThis);
      ("ppIMetadataQueryReader",ANone);
    ],MANone);
    ("GetPreview",[
      ("This",AThis);
      ("ppIBitmapSource",ANone);
    ],MANone);
    ("GetColorContexts",[
      ("This",AThis);
      ("cCount",ANone);
      ("ppIColorContexts",ANone);
      ("pcActualCount",ANone);
    ],MANone);
    ("GetThumbnail",[
      ("This",AThis);
      ("ppIThumbnail",ANone);
    ],MANone);
    ("GetFrameCount",[
      ("This",AThis);
      ("pCount",ANone);
    ],MANone);
    ("GetFrame",[
      ("This",AThis);
      ("index",ANone);
      ("ppIBitmapFrame",ANone);
    ],MANone);
  ]);
  ("IWICBitmapEncoderInfoVtbl",IAAutogen(Set.ofList []), "IWICBitmapCodecInfoVtbl", [
    ("CreateInstance",[
      ("This",AThis);
      ("ppIBitmapEncoder",ANone);
    ],MANone);
  ]);
  ("IWICBitmapEncoderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pIStream",ANone);
      ("cacheOption",ANone);
    ],MANone);
    ("GetContainerFormat",[
      ("This",AThis);
      ("pguidContainerFormat",ANone);
    ],MANone);
    ("GetEncoderInfo",[
      ("This",AThis);
      ("ppIEncoderInfo",ANone);
    ],MANone);
    ("SetColorContexts",[
      ("This",AThis);
      ("cCount",ANone);
      ("ppIColorContext",ANone);
    ],MANone);
    ("SetPalette",[
      ("This",AThis);
      ("pIPalette",ANone);
    ],MANone);
    ("SetThumbnail",[
      ("This",AThis);
      ("pIThumbnail",ANone);
    ],MANone);
    ("SetPreview",[
      ("This",AThis);
      ("pIPreview",ANone);
    ],MANone);
    ("CreateNewFrame",[
      ("This",AThis);
      ("ppIFrameEncode",ANone);
      ("ppIEncoderOptions",ANone);
    ],MANone);
    ("Commit",[
      ("This",AThis);
    ],MANone);
    ("GetMetadataQueryWriter",[
      ("This",AThis);
      ("ppIMetadataQueryWriter",ANone);
    ],MANone);
  ]);
  ("IWICBitmapFlipRotatorVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pISource",ANone);
      ("options",ANone);
    ],MANone);
  ]);
  ("IWICBitmapFrameDecodeVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("GetMetadataQueryReader",[
      ("This",AThis);
      ("ppIMetadataQueryReader",ANone);
    ],MANone);
    ("GetColorContexts",[
      ("This",AThis);
      ("cCount",ANone);
      ("ppIColorContexts",ANone);
      ("pcActualCount",ANone);
    ],MANone);
    ("GetThumbnail",[
      ("This",AThis);
      ("ppIThumbnail",ANone);
    ],MANone);
  ]);
  ("IWICBitmapFrameEncodeVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pIEncoderOptions",ANone);
    ],MANone);
    ("SetSize",[
      ("This",AThis);
      ("uiWidth",ANone);
      ("uiHeight",ANone);
    ],MANone);
    ("SetResolution",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
    ("SetPixelFormat",[
      ("This",AThis);
      ("pPixelFormat",ANone);
    ],MANone);
    ("SetColorContexts",[
      ("This",AThis);
      ("cCount",ANone);
      ("ppIColorContext",ANone);
    ],MANone);
    ("SetPalette",[
      ("This",AThis);
      ("pIPalette",ANone);
    ],MANone);
    ("SetThumbnail",[
      ("This",AThis);
      ("pIThumbnail",ANone);
    ],MANone);
    ("WritePixels",[
      ("This",AThis);
      ("lineCount",ANone);
      ("cbStride",ANone);
      ("cbBufferSize",ANone);
      ("pbPixels",ANone);
    ],MANone);
    ("WriteSource",[
      ("This",AThis);
      ("pIBitmapSource",ANone);
      ("prc",ANone);
    ],MANone);
    ("Commit",[
      ("This",AThis);
    ],MANone);
    ("GetMetadataQueryWriter",[
      ("This",AThis);
      ("ppIMetadataQueryWriter",ANone);
    ],MANone);
  ]);
  ("IWICBitmapLockVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetSize",[
      ("This",AThis);
      ("puiWidth",ANone);
      ("puiHeight",ANone);
    ],MANone);
    ("GetStride",[
      ("This",AThis);
      ("pcbStride",ANone);
    ],MANone);
    ("GetDataPointer",[
      ("This",AThis);
      ("pcbBufferSize",ANone);
      ("ppbData",ANone);
    ],MANone);
    ("GetPixelFormat",[
      ("This",AThis);
      ("pPixelFormat",ANone);
    ],MANone);
  ]);
  ("IWICBitmapScalerVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pISource",ANone);
      ("uiWidth",ANone);
      ("uiHeight",ANone);
      ("mode",ANone);
    ],MANone);
  ]);
  ("IWICBitmapSourceTransformVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("CopyPixels",[
      ("This",AThis);
      ("prc",ANone);
      ("uiWidth",ANone);
      ("uiHeight",ANone);
      ("pguidDstFormat",ANone);
      ("dstTransform",ANone);
      ("nStride",ANone);
      ("cbBufferSize",ANone);
      ("pbBuffer",ANone);
    ],MANone);
    ("GetClosestSize",[
      ("This",AThis);
      ("puiWidth",ANone);
      ("puiHeight",ANone);
    ],MANone);
    ("GetClosestPixelFormat",[
      ("This",AThis);
      ("pguidDstFormat",ANone);
    ],MANone);
    ("DoesSupportTransform",[
      ("This",AThis);
      ("dstTransform",ANone);
      ("pfIsSupported",ANone);
    ],MANone);
  ]);
  ("IWICBitmapSourceVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetSize",[
      ("This",AThis);
      ("puiWidth",ANone);
      ("puiHeight",ANone);
    ],MANone);
    ("GetPixelFormat",[
      ("This",AThis);
      ("pPixelFormat",ANone);
    ],MANone);
    ("GetResolution",[
      ("This",AThis);
      ("pDpiX",ANone);
      ("pDpiY",ANone);
    ],MANone);
    ("CopyPalette",[
      ("This",AThis);
      ("pIPalette",ANone);
    ],MANone);
    ("CopyPixels",[
      ("This",AThis);
      ("prc",ANone);
      ("cbStride",ANone);
      ("cbBufferSize",ANone);
      ("pbBuffer",ANone);
    ],MANone);
  ]);
  ("IWICBitmapVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Lock",[
      ("This",AThis);
      ("prcLock",ANone);
      ("flags",ANone);
      ("ppILock",ANone);
    ],MANone);
    ("SetPalette",[
      ("This",AThis);
      ("pIPalette",ANone);
    ],MANone);
    ("SetResolution",[
      ("This",AThis);
      ("dpiX",ANone);
      ("dpiY",ANone);
    ],MANone);
  ]);
  ("IWICColorContextVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("InitializeFromFilename",[
      ("This",AThis);
      ("wzFilename",ANone);
    ],MANone);
    ("InitializeFromMemory",[
      ("This",AThis);
      ("pbBuffer",ANone);
      ("cbBufferSize",ANone);
    ],MANone);
    ("InitializeFromExifColorSpace",[
      ("This",AThis);
      ("value",ANone);
    ],MANone);
    ("GetType",[
      ("This",AThis);
      ("pType",ANone);
    ],MANone);
    ("GetProfileBytes",[
      ("This",AThis);
      ("cbBuffer",ANone);
      ("pbBuffer",ANone);
      ("pcbActual",ANone);
    ],MANone);
    ("GetExifColorSpace",[
      ("This",AThis);
      ("pValue",ANone);
    ],MANone);
  ]);
  ("IWICColorTransformVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pIBitmapSource",ANone);
      ("pIContextSource",ANone);
      ("pIContextDest",ANone);
      ("pixelFmtDest",ANone);
    ],MANone);
  ]);
  ("IWICComponentInfoVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetComponentType",[
      ("This",AThis);
      ("pType",ANone);
    ],MANone);
    ("GetCLSID",[
      ("This",AThis);
      ("pclsid",ANone);
    ],MANone);
    ("GetSigningStatus",[
      ("This",AThis);
      ("pStatus",ANone);
    ],MANone);
    ("GetAuthor",[
      ("This",AThis);
      ("cchAuthor",ANone);
      ("wzAuthor",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetVendorGUID",[
      ("This",AThis);
      ("pguidVendor",ANone);
    ],MANone);
    ("GetVersion",[
      ("This",AThis);
      ("cchVersion",ANone);
      ("wzVersion",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetSpecVersion",[
      ("This",AThis);
      ("cchSpecVersion",ANone);
      ("wzSpecVersion",ANone);
      ("pcchActual",ANone);
    ],MANone);
    ("GetFriendlyName",[
      ("This",AThis);
      ("cchFriendlyName",ANone);
      ("wzFriendlyName",ANone);
      ("pcchActual",ANone);
    ],MANone);
  ]);
  ("IWICDdsDecoderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetParameters",[
      ("This",AThis);
      ("pParameters",ANone);
    ],MANone);
    ("GetFrame",[
      ("This",AThis);
      ("arrayIndex",ANone);
      ("mipLevel",ANone);
      ("sliceIndex",ANone);
      ("ppIBitmapFrame",ANone);
    ],MANone);
  ]);
  ("IWICDdsEncoderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("SetParameters",[
      ("This",AThis);
      ("pParameters",ANone);
    ],MANone);
    ("GetParameters",[
      ("This",AThis);
      ("pParameters",ANone);
    ],MANone);
    ("CreateNewFrame",[
      ("This",AThis);
      ("ppIFrameEncode",ANone);
      ("pArrayIndex",ANone);
      ("pMipLevel",ANone);
      ("pSliceIndex",ANone);
    ],MANone);
  ]);
  ("IWICDdsFrameDecodeVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetSizeInBlocks",[
      ("This",AThis);
      ("pWidthInBlocks",ANone);
      ("pHeightInBlocks",ANone);
    ],MANone);
    ("GetFormatInfo",[
      ("This",AThis);
      ("pFormatInfo",ANone);
    ],MANone);
    ("CopyBlocks",[
      ("This",AThis);
      ("prcBoundsInBlocks",ANone);
      ("cbStride",ANone);
      ("cbBufferSize",ANone);
      ("pbBuffer",ANone);
    ],MANone);
  ]);
  ("IWICDevelopRawNotificationCallbackVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Notify",[
      ("This",AThis);
      ("NotificationMask",ANone);
    ],MANone);
  ]);
  ("IWICDevelopRawVtbl",IAAutogen(Set.ofList []), "IWICBitmapFrameDecodeVtbl", [
    ("QueryRawCapabilitiesInfo",[
      ("This",AThis);
      ("pInfo",ANone);
    ],MANone);
    ("LoadParameterSet",[
      ("This",AThis);
      ("ParameterSet",ANone);
    ],MANone);
    ("GetCurrentParameterSet",[
      ("This",AThis);
      ("ppCurrentParameterSet",ANone);
    ],MANone);
    ("SetExposureCompensation",[
      ("This",AThis);
      ("ev",ANone);
    ],MANone);
    ("GetExposureCompensation",[
      ("This",AThis);
      ("pEV",ANone);
    ],MANone);
    ("SetWhitePointRGB",[
      ("This",AThis);
      ("Red",ANone);
      ("Green",ANone);
      ("Blue",ANone);
    ],MANone);
    ("GetWhitePointRGB",[
      ("This",AThis);
      ("pRed",ANone);
      ("pGreen",ANone);
      ("pBlue",ANone);
    ],MANone);
    ("SetNamedWhitePoint",[
      ("This",AThis);
      ("WhitePoint",ANone);
    ],MANone);
    ("GetNamedWhitePoint",[
      ("This",AThis);
      ("pWhitePoint",ANone);
    ],MANone);
    ("SetWhitePointKelvin",[
      ("This",AThis);
      ("WhitePointKelvin",ANone);
    ],MANone);
    ("GetWhitePointKelvin",[
      ("This",AThis);
      ("pWhitePointKelvin",ANone);
    ],MANone);
    ("GetKelvinRangeInfo",[
      ("This",AThis);
      ("pMinKelvinTemp",ANone);
      ("pMaxKelvinTemp",ANone);
      ("pKelvinTempStepValue",ANone);
    ],MANone);
    ("SetContrast",[
      ("This",AThis);
      ("Contrast",ANone);
    ],MANone);
    ("GetContrast",[
      ("This",AThis);
      ("pContrast",ANone);
    ],MANone);
    ("SetGamma",[
      ("This",AThis);
      ("Gamma",ANone);
    ],MANone);
    ("GetGamma",[
      ("This",AThis);
      ("pGamma",ANone);
    ],MANone);
    ("SetSharpness",[
      ("This",AThis);
      ("Sharpness",ANone);
    ],MANone);
    ("GetSharpness",[
      ("This",AThis);
      ("pSharpness",ANone);
    ],MANone);
    ("SetSaturation",[
      ("This",AThis);
      ("Saturation",ANone);
    ],MANone);
    ("GetSaturation",[
      ("This",AThis);
      ("pSaturation",ANone);
    ],MANone);
    ("SetTint",[
      ("This",AThis);
      ("Tint",ANone);
    ],MANone);
    ("GetTint",[
      ("This",AThis);
      ("pTint",ANone);
    ],MANone);
    ("SetNoiseReduction",[
      ("This",AThis);
      ("NoiseReduction",ANone);
    ],MANone);
    ("GetNoiseReduction",[
      ("This",AThis);
      ("pNoiseReduction",ANone);
    ],MANone);
    ("SetDestinationColorContext",[
      ("This",AThis);
      ("pColorContext",ANone);
    ],MANone);
    ("SetToneCurve",[
      ("This",AThis);
      ("cbToneCurveSize",ANone);
      ("pToneCurve",ANone);
    ],MANone);
    ("GetToneCurve",[
      ("This",AThis);
      ("cbToneCurveBufferSize",ANone);
      ("pToneCurve",ANone);
      ("pcbActualToneCurveBufferSize",ANone);
    ],MANone);
    ("SetRotation",[
      ("This",AThis);
      ("Rotation",ANone);
    ],MANone);
    ("GetRotation",[
      ("This",AThis);
      ("pRotation",ANone);
    ],MANone);
    ("SetRenderMode",[
      ("This",AThis);
      ("RenderMode",ANone);
    ],MANone);
    ("GetRenderMode",[
      ("This",AThis);
      ("pRenderMode",ANone);
    ],MANone);
    ("SetNotificationCallback",[
      ("This",AThis);
      ("pCallback",ANone);
    ],MANone);
  ]);
  ("IWICEnumMetadataItemVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Next",[
      ("This",AThis);
      ("celt",ANone);
      ("rgeltSchema",ANone);
      ("rgeltId",ANone);
      ("rgeltValue",ANone);
      ("pceltFetched",ANone);
    ],MANone);
    ("Skip",[
      ("This",AThis);
      ("celt",ANone);
    ],MANone);
    ("Reset",[
      ("This",AThis);
    ],MANone);
    ("Clone",[
      ("This",AThis);
      ("ppIEnumMetadataItem",ANone);
    ],MANone);
  ]);
  ("IWICFastMetadataEncoderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Commit",[
      ("This",AThis);
    ],MANone);
    ("GetMetadataQueryWriter",[
      ("This",AThis);
      ("ppIMetadataQueryWriter",ANone);
    ],MANone);
  ]);
  ("IWICFormatConverterInfoVtbl",IAAutogen(Set.ofList []), "IWICComponentInfoVtbl", [
    ("GetPixelFormats",[
      ("This",AThis);
      ("cFormats",ANone);
      ("pPixelFormatGUIDs",ANone);
      ("pcActual",ANone);
    ],MANone);
    ("CreateInstance",[
      ("This",AThis);
      ("ppIConverter",ANone);
    ],MANone);
  ]);
  ("IWICFormatConverterVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("pISource",ANone);
      ("dstFormat",ANone);
      ("dither",ANone);
      ("pIPalette",ANone);
      ("alphaThresholdPercent",ANone);
      ("paletteTranslate",ANone);
    ],MANone);
    ("CanConvert",[
      ("This",AThis);
      ("srcPixelFormat",ANone);
      ("dstPixelFormat",ANone);
      ("pfCanConvert",ANone);
    ],MANone);
  ]);
  ("IWICImageEncoderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("WriteFrame",[
      ("This",AThis);
      ("pImage",ANone);
      ("pFrameEncode",ANone);
      ("pImageParameters",ANone);
    ],MANone);
    ("WriteFrameThumbnail",[
      ("This",AThis);
      ("pImage",ANone);
      ("pFrameEncode",ANone);
      ("pImageParameters",ANone);
    ],MANone);
    ("WriteThumbnail",[
      ("This",AThis);
      ("pImage",ANone);
      ("pEncoder",ANone);
      ("pImageParameters",ANone);
    ],MANone);
  ]);
  ("IWICImagingFactory2Vtbl",IAAutogen(Set.ofList []), "IWICImagingFactoryVtbl", [
    ("CreateImageEncoder",[
      ("This",AThis);
      ("pD2DDevice",ANone);
      ("ppWICImageEncoder",ANone);
    ],MANone);
  ]);
  ("IWICImagingFactoryVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("CreateDecoderFromFilename",[
      ("This",AThis);
      ("wzFilename",ANone);
      ("pguidVendor",ANone);
      ("dwDesiredAccess",ANone);
      ("metadataOptions",ANone);
      ("ppIDecoder",ANone);
    ],MANone);
    ("CreateDecoderFromStream",[
      ("This",AThis);
      ("pIStream",ANone);
      ("pguidVendor",ANone);
      ("metadataOptions",ANone);
      ("ppIDecoder",ANone);
    ],MANone);
    ("CreateDecoderFromFileHandle",[
      ("This",AThis);
      ("hFile",ANone);
      ("pguidVendor",ANone);
      ("metadataOptions",ANone);
      ("ppIDecoder",ANone);
    ],MANone);
    ("CreateComponentInfo",[
      ("This",AThis);
      ("clsidComponent",ANone);
      ("ppIInfo",ANone);
    ],MANone);
    ("CreateDecoder",[
      ("This",AThis);
      ("guidContainerFormat",ANone);
      ("pguidVendor",ANone);
      ("ppIDecoder",ANone);
    ],MANone);
    ("CreateEncoder",[
      ("This",AThis);
      ("guidContainerFormat",ANone);
      ("pguidVendor",ANone);
      ("ppIEncoder",ANone);
    ],MANone);
    ("CreatePalette",[
      ("This",AThis);
      ("ppIPalette",ANone);
    ],MANone);
    ("CreateFormatConverter",[
      ("This",AThis);
      ("ppIFormatConverter",ANone);
    ],MANone);
    ("CreateBitmapScaler",[
      ("This",AThis);
      ("ppIBitmapScaler",ANone);
    ],MANone);
    ("CreateBitmapClipper",[
      ("This",AThis);
      ("ppIBitmapClipper",ANone);
    ],MANone);
    ("CreateBitmapFlipRotator",[
      ("This",AThis);
      ("ppIBitmapFlipRotator",ANone);
    ],MANone);
    ("CreateStream",[
      ("This",AThis);
      ("ppIWICStream",ANone);
    ],MANone);
    ("CreateColorContext",[
      ("This",AThis);
      ("ppIWICColorContext",ANone);
    ],MANone);
    ("CreateColorTransformer",[
      ("This",AThis);
      ("ppIWICColorTransform",ANone);
    ],MANone);
    ("CreateBitmap",[
      ("This",AThis);
      ("uiWidth",ANone);
      ("uiHeight",ANone);
      ("pixelFormat",ANone);
      ("option",ANone);
      ("ppIBitmap",ANone);
    ],MANone);
    ("CreateBitmapFromSource",[
      ("This",AThis);
      ("pIBitmapSource",ANone);
      ("option",ANone);
      ("ppIBitmap",ANone);
    ],MANone);
    ("CreateBitmapFromSourceRect",[
      ("This",AThis);
      ("pIBitmapSource",ANone);
      ("x",ANone);
      ("y",ANone);
      ("width",ANone);
      ("height",ANone);
      ("ppIBitmap",ANone);
    ],MANone);
    ("CreateBitmapFromMemory",[
      ("This",AThis);
      ("uiWidth",ANone);
      ("uiHeight",ANone);
      ("pixelFormat",ANone);
      ("cbStride",ANone);
      ("cbBufferSize",ANone);
      ("pbBuffer",ANone);
      ("ppIBitmap",ANone);
    ],MANone);
    ("CreateBitmapFromHBITMAP",[
      ("This",AThis);
      ("hBitmap",ANone);
      ("hPalette",ANone);
      ("options",ANone);
      ("ppIBitmap",ANone);
    ],MANone);
    ("CreateBitmapFromHICON",[
      ("This",AThis);
      ("hIcon",ANone);
      ("ppIBitmap",ANone);
    ],MANone);
    ("CreateComponentEnumerator",[
      ("This",AThis);
      ("componentTypes",ANone);
      ("options",ANone);
      ("ppIEnumUnknown",ANone);
    ],MANone);
    ("CreateFastMetadataEncoderFromDecoder",[
      ("This",AThis);
      ("pIDecoder",ANone);
      ("ppIFastEncoder",ANone);
    ],MANone);
    ("CreateFastMetadataEncoderFromFrameDecode",[
      ("This",AThis);
      ("pIFrameDecoder",ANone);
      ("ppIFastEncoder",ANone);
    ],MANone);
    ("CreateQueryWriter",[
      ("This",AThis);
      ("guidMetadataFormat",ANone);
      ("pguidVendor",ANone);
      ("ppIQueryWriter",ANone);
    ],MANone);
    ("CreateQueryWriterFromReader",[
      ("This",AThis);
      ("pIQueryReader",ANone);
      ("pguidVendor",ANone);
      ("ppIQueryWriter",ANone);
    ],MANone);
  ]);
  ("IWICJpegFrameDecodeVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("DoesSupportIndexing",[
      ("This",AThis);
      ("pfIndexingSupported",ANone);
    ],MANone);
    ("SetIndexing",[
      ("This",AThis);
      ("options",ANone);
      ("horizontalIntervalSize",ANone);
    ],MANone);
    ("ClearIndexing",[
      ("This",AThis);
    ],MANone);
    ("GetAcHuffmanTable",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("tableIndex",ANone);
      ("pAcHuffmanTable",ANone);
    ],MANone);
    ("GetDcHuffmanTable",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("tableIndex",ANone);
      ("pDcHuffmanTable",ANone);
    ],MANone);
    ("GetQuantizationTable",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("tableIndex",ANone);
      ("pQuantizationTable",ANone);
    ],MANone);
    ("GetFrameHeader",[
      ("This",AThis);
      ("pFrameHeader",ANone);
    ],MANone);
    ("GetScanHeader",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("pScanHeader",ANone);
    ],MANone);
    ("CopyScan",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("scanOffset",ANone);
      ("cbScanData",ANone);
      ("pbScanData",ANone);
      ("pcbScanDataActual",ANone);
    ],MANone);
    ("CopyMinimalStream",[
      ("This",AThis);
      ("streamOffset",ANone);
      ("cbStreamData",ANone);
      ("pbStreamData",ANone);
      ("pcbStreamDataActual",ANone);
    ],MANone);
  ]);
  ("IWICJpegFrameEncodeVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetAcHuffmanTable",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("tableIndex",ANone);
      ("pAcHuffmanTable",ANone);
    ],MANone);
    ("GetDcHuffmanTable",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("tableIndex",ANone);
      ("pDcHuffmanTable",ANone);
    ],MANone);
    ("GetQuantizationTable",[
      ("This",AThis);
      ("scanIndex",ANone);
      ("tableIndex",ANone);
      ("pQuantizationTable",ANone);
    ],MANone);
    ("WriteScan",[
      ("This",AThis);
      ("cbScanData",ANone);
      ("pbScanData",ANone);
    ],MANone);
  ]);
  ("IWICMetadataQueryReaderVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetContainerFormat",[
      ("This",AThis);
      ("pguidContainerFormat",ANone);
    ],MANone);
    ("GetLocation",[
      ("This",AThis);
      ("cchMaxLength",ANone);
      ("wzNamespace",ANone);
      ("pcchActualLength",ANone);
    ],MANone);
    ("GetMetadataByName",[
      ("This",AThis);
      ("wzName",ANone);
      ("pvarValue",ANone);
    ],MANone);
    ("GetEnumerator",[
      ("This",AThis);
      ("ppIEnumString",ANone);
    ],MANone);
  ]);
  ("IWICMetadataQueryWriterVtbl",IAAutogen(Set.ofList []), "IWICMetadataQueryReaderVtbl", [
    ("SetMetadataByName",[
      ("This",AThis);
      ("wzName",ANone);
      ("pvarValue",ANone);
    ],MANone);
    ("RemoveMetadataByName",[
      ("This",AThis);
      ("wzName",ANone);
    ],MANone);
  ]);
  ("IWICPaletteVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("InitializePredefined",[
      ("This",AThis);
      ("ePaletteType",ANone);
      ("fAddTransparentColor",ANone);
    ],MANone);
    ("InitializeCustom",[
      ("This",AThis);
      ("pColors",ANone);
      ("cCount",ANone);
    ],MANone);
    ("InitializeFromBitmap",[
      ("This",AThis);
      ("pISurface",ANone);
      ("cCount",ANone);
      ("fAddTransparentColor",ANone);
    ],MANone);
    ("InitializeFromPalette",[
      ("This",AThis);
      ("pIPalette",ANone);
    ],MANone);
    ("GetType",[
      ("This",AThis);
      ("pePaletteType",ANone);
    ],MANone);
    ("GetColorCount",[
      ("This",AThis);
      ("pcCount",ANone);
    ],MANone);
    ("GetColors",[
      ("This",AThis);
      ("cCount",ANone);
      ("pColors",ANone);
      ("pcActualColors",ANone);
    ],MANone);
    ("IsBlackWhite",[
      ("This",AThis);
      ("pfIsBlackWhite",ANone);
    ],MANone);
    ("IsGrayscale",[
      ("This",AThis);
      ("pfIsGrayscale",ANone);
    ],MANone);
    ("HasAlpha",[
      ("This",AThis);
      ("pfHasAlpha",ANone);
    ],MANone);
  ]);
  ("IWICPixelFormatInfo2Vtbl",IAAutogen(Set.ofList []), "IWICPixelFormatInfoVtbl", [
    ("SupportsTransparency",[
      ("This",AThis);
      ("pfSupportsTransparency",ANone);
    ],MANone);
    ("GetNumericRepresentation",[
      ("This",AThis);
      ("pNumericRepresentation",ANone);
    ],MANone);
  ]);
  ("IWICPixelFormatInfoVtbl",IAAutogen(Set.ofList []), "IWICComponentInfoVtbl", [
    ("GetFormatGUID",[
      ("This",AThis);
      ("pFormat",ANone);
    ],MANone);
    ("GetColorContext",[
      ("This",AThis);
      ("ppIColorContext",ANone);
    ],MANone);
    ("GetBitsPerPixel",[
      ("This",AThis);
      ("puiBitsPerPixel",ANone);
    ],MANone);
    ("GetChannelCount",[
      ("This",AThis);
      ("puiChannelCount",ANone);
    ],MANone);
    ("GetChannelMask",[
      ("This",AThis);
      ("uiChannelIndex",ANone);
      ("cbMaskBuffer",ANone);
      ("pbMaskBuffer",ANone);
      ("pcbActual",ANone);
    ],MANone);
  ]);
  ("IWICPlanarBitmapFrameEncodeVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("WritePixels",[
      ("This",AThis);
      ("lineCount",ANone);
      ("pPlanes",ANone);
      ("cPlanes",ANone);
    ],MANone);
    ("WriteSource",[
      ("This",AThis);
      ("ppPlanes",ANone);
      ("cPlanes",ANone);
      ("prcSource",ANone);
    ],MANone);
  ]);
  ("IWICPlanarBitmapSourceTransformVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("DoesSupportTransform",[
      ("This",AThis);
      ("puiWidth",ANone);
      ("puiHeight",ANone);
      ("dstTransform",ANone);
      ("dstPlanarOptions",ANone);
      ("pguidDstFormats",ANone);
      ("pPlaneDescriptions",ANone);
      ("cPlanes",ANone);
      ("pfIsSupported",ANone);
    ],MANone);
    ("CopyPixels",[
      ("This",AThis);
      ("prcSource",ANone);
      ("uiWidth",ANone);
      ("uiHeight",ANone);
      ("dstTransform",ANone);
      ("dstPlanarOptions",ANone);
      ("pDstPlanes",ANone);
      ("cPlanes",ANone);
    ],MANone);
  ]);
  ("IWICPlanarFormatConverterVtbl",IAAutogen(Set.ofList []), "IWICBitmapSourceVtbl", [
    ("Initialize",[
      ("This",AThis);
      ("ppPlanes",ANone);
      ("cPlanes",ANone);
      ("dstFormat",ANone);
      ("dither",ANone);
      ("pIPalette",ANone);
      ("alphaThresholdPercent",ANone);
      ("paletteTranslate",ANone);
    ],MANone);
    ("CanConvert",[
      ("This",AThis);
      ("pSrcPixelFormats",ANone);
      ("cSrcPlanes",ANone);
      ("dstPixelFormat",ANone);
      ("pfCanConvert",ANone);
    ],MANone);
  ]);
  ("IWICProgressCallbackVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("Notify",[
      ("This",AThis);
      ("uFrameNum",ANone);
      ("operation",ANone);
      ("dblProgress",ANone);
    ],MANone);
  ]);
  ("IWICProgressiveLevelControlVtbl",IAAutogen(Set.ofList []), "IUnknownVtbl", [
    ("GetLevelCount",[
      ("This",AThis);
      ("pcLevels",ANone);
    ],MANone);
    ("GetCurrentLevel",[
      ("This",AThis);
      ("pnLevel",ANone);
    ],MANone);
    ("SetCurrentLevel",[
      ("This",AThis);
      ("nLevel",ANone);
    ],MANone);
  ]);
  ("IWICStreamVtbl",IAManual, "IStreamVtbl", [
    ("InitializeFromIStream",[
      ("This",AThis);
      ("pIStream",ANone);
    ],MANone);
    ("InitializeFromFilename",[
      ("This",AThis);
      ("wzFileName",ANone);
      ("dwDesiredAccess",ANone);
    ],MANone);
    ("InitializeFromMemory",[
      ("This",AThis);
      ("pbBuffer",ANone);
      ("cbBufferSize",ANone);
    ],MANone);
    ("InitializeFromIStreamRegion",[
      ("This",AThis);
      ("pIStream",ANone);
      ("ulOffset",ANone);
      ("ulMaxSize",ANone);
    ],MANone);
  ]);
  ]

