---
modules:
    - name: d3d11
      output-path: ../../d3d11on12/src
      include-path: 
        - .\Include\10.0.14393.0\um\
        - .\Include\10.0.14393.0\shared\
        - .\Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d3d11.h
      no-winapi-gen: false
      no-enum-conversion: true

    - name: d2d1
      output-path: ../../d2d1/src
      include-path: 
        - .\Include\10.0.14393.0\um\
        - .\Include\10.0.14393.0\shared\
        - .\Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d2d1effectauthor.h
          - name: d2d1.h
            uses:
              - dxgi_safe
              - dwrite_safe
          - name: d2d1_1.h
            uses:
              - d2d1_safe
              - dxgi_safe
              - dwrite_safe
          - name: d2d1_2.h
            uses:
              - d2d1_safe
              - d2d1_1_safe
              - dxgi_safe
              - dwrite_safe
          - name: d2d1_3.h
            uses:
              - d2d1_safe
              - d2d1_1_safe
              - d2d1_2_safe
              - dxgi_safe
              - dwrite_safe
      no-winapi-gen: false
      no-enum-conversion: true
      
    - name: d3d11on12
      output-path: ../../d3d11on12/src
      include-path: 
        - .\Include\10.0.14393.0\um\
        - .\Include\10.0.14393.0\shared\
        - .\Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d3d11on12.h
            uses:
              - d3d11_safe
      no-winapi-gen: false
      no-enum-conversion: true

    - name: d3d12_dxgi
      output-path: ../../dx_dxgi/src/
      include-path: 
        - .\Include\10.0.14393.0\um\
        - .\Include\10.0.14393.0\shared\
        - .\Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d3d12sdklayers.h
            uses:
              - d3dcommon_safe
          - name: dxgiformat.h
          - name: dxgitype.h
          - name: d3d12.h
          - name: d3dcommon.h
          - name: dxgi.h
          - name: dxgi1_2.h
            uses:
              - dxgi_safe
          - name: dxgi1_3.h
            uses:
              - dxgi_safe
              - dxgi1_2_safe
          - name: dxgi1_4.h
            uses:
              - dxgi_safe
              - dxgi1_2_safe
              - dxgi1_3_safe
          - name: dxgi1_5.h
      no-winapi-gen: false
      no-enum-conversion: false

    - name: d3d12shader
      output-path: ../../dx_dxgi/src/
      include-path: 
        - Include\10.0.14393.0\um\
        - Include\10.0.14393.0\shared\
        - Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: d3d12shader.h
      no-winapi-gen: false
      no-enum-conversion: false

    - name: dwrite
      output-path: ../../dwrite/src
      include-path: 
        - .\Include\10.0.14393.0\um\
        - .\Include\10.0.14393.0\shared\
        - .\Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/dwrite_pch.h
      headers:
          - name: dwrite.h
          - name: dwrite_1.h
            uses:
              - dwrite_safe
          - name: dwrite_2.h
          - name: dwrite_3.h
      no-winapi-gen: false
      no-enum-conversion: true

    - name: wincodec
      output-path: ../../d3d11on12/src
      include-path: 
        - .\Include\10.0.14393.0\um\
        - .\Include\10.0.14393.0\shared\
        - .\Include\10.0.14393.0\ucrt\
      precompiled-header: ./PCH/Common_PCH.h
      headers:
          - name: DocumentTarget.h
          - name: urlmon.h
          - name: ocidl.h
          - name: objidlbase.h
          - name: objidl.h
          - name: wincodec.h
      no-winapi-gen: false
      no-enum-conversion: true

